//--------------------------------------------------------------------------------------
// File: XboxHardwareTimer.h
//
// Desc: Contains a class for doing performance measurements of the Xbox 360 CPU.
//
// Xbox Advanced Technology Group.
// Copyright (C) Microsoft Corporation. All rights reserved.
//--------------------------------------------------------------------------------------

#include "XboxHardwareTimer.h"

//--------------------------------------------------------------------------------------
// Name: XboxHardwareTimer
// Desc: Constructor
//--------------------------------------------------------------------------------------
XboxHardwareTimer::XboxHardwareTimer() : m_uiEventSampleIndex( 0 ),
                                         m_uiReportIndex( 0 )
{
}


//--------------------------------------------------------------------------------------
// Name: XboxHardwareTimer::operator new
// Desc: This overloaded operator new is used to place the timer in non-cacheable memory
//       so it won't affect the caches and the results being measured.
//--------------------------------------------------------------------------------------
VOID* XboxHardwareTimer::operator new( size_t size )
{
    return XPhysicalAlloc( sizeof( XboxHardwareTimer ),
                           MAXULONG_PTR, 0,
                           PAGE_READWRITE | PAGE_NOCACHE );
}


//--------------------------------------------------------------------------------------
// Name: XboxHardwareTimer::operator delete
// Desc: Operator delete to match the overloaded operator new
//--------------------------------------------------------------------------------------
VOID XboxHardwareTimer::operator delete( VOID* ptr )
{
    XPhysicalFree( ptr );
}


//--------------------------------------------------------------------------------------
// Name: GetNumReports
// Desc: Gets the current number of reports. Reports are generated by MakeReports
//       which is called by StopTimer
//--------------------------------------------------------------------------------------
UINT XboxHardwareTimer::GetNumReports() const
{
    return m_uiReportIndex;
}


//--------------------------------------------------------------------------------------
// Name: GetReport
// Desc: Gets a report given an index
//--------------------------------------------------------------------------------------
const XboxEventSample* XboxHardwareTimer::GetReport( UINT uiReport ) const
{
    assert( uiReport < GetNumReports() );
    return &m_Reports[uiReport];
}


//--------------------------------------------------------------------------------------
// Name: MakeReports
// Desc: builds a report after timing
//--------------------------------------------------------------------------------------
VOID XboxHardwareTimer::MakeReports()
{
    // must be an even number of event samples
    assert( !( m_uiEventSampleIndex & 0x00000001 ) );

    m_uiReportIndex = 0;

    BOOL* pbFinished = new BOOL[m_uiEventSampleIndex];
    ZeroMemory( pbFinished, m_uiEventSampleIndex * sizeof( BOOL ) );

    for( UINT i = 0; i < m_uiEventSampleIndex; i++ )
    {
        if( !pbFinished[i] )
        {
            // find corresponing end EventSample
            int last = -1;
            for( UINT j = i + 1; j < m_uiEventSampleIndex; j++ )
            {
                if( !pbFinished[j] &&
                    strcmp( m_EventSamples[i].strName,
                            m_EventSamples[j].strName ) == 0 &&
                    m_EventSamples[i].ID == m_EventSamples[j].ID )
                {
                    last = j;
                }
            }
            assert( last != -1 );

            assert( m_uiReportIndex < MAX_REPORTS );

            m_Reports[m_uiReportIndex].strName = m_EventSamples[i].strName;
            for( DWORD counter = 0; counter < NumPerfCounters; ++counter )
            {
                // Calculate the elapsed count.
                DWORD delta = m_EventSamples[last].Counters[counter] - m_EventSamples[i].Counters[counter];
                // Subtract off the calibration amount (measured on an empty timer) but
                // make sure the result doesn't go negative.
                if( m_CalibrationCounters[counter] > delta )
                    delta = 0;
                else
                    delta -= m_CalibrationCounters[counter];
                m_Reports[m_uiReportIndex].Counters[counter] = delta;
            }

            m_uiReportIndex++;


            pbFinished[i] = TRUE;
            pbFinished[last] = TRUE;
        }
    }

    delete [] pbFinished;
}


//--------------------------------------------------------------------------------------
// Name: StartTiming
// Desc: Start the timing run - initialize all hardware and data structures for a
//       timing run.
//--------------------------------------------------------------------------------------
VOID XboxHardwareTimer::StartTiming()
{
    // Set up the Performance Monitor Counters using one of the standard setups.
    // There are many to choose from. If the setup is changed then
    // GetCounterName() will no longer be correct.
    DmPMCInstallAndStart( PMC_SETUP_OVERVIEW_PB0T0 );

    // Set the number of recorded events to zero.
    m_uiEventSampleIndex = 0;

    // Calibrate the timers - attempt to adjust for timer overhead by measuring an
    // empty timing block.
    StartTimer( "Calibration" );
    StopTimer( "Calibration" );

    for( DWORD i = 0; i < NumPerfCounters; ++i )
    {
        m_CalibrationCounters[i] = m_EventSamples[1].Counters[i] - m_EventSamples[0].Counters[i];
    }

    // Remove the calibration event from the record.
    m_uiEventSampleIndex = 0;
}


//--------------------------------------------------------------------------------------
// Name: StopTiming
// Desc: Stop the timing run and generate reports
//--------------------------------------------------------------------------------------
VOID XboxHardwareTimer::StopTiming()
{
    MakeReports();
}


//--------------------------------------------------------------------------------------
// Name: GetCounterName
// Desc: Gets the name of a set event counter
//--------------------------------------------------------------------------------------
const CHAR* XboxHardwareTimer::GetCounterName( UINT uiEvent ) const
{
    switch( uiEvent )
    {
        case 0:
            return "Cycles";
        case 1:
            return "L1 miss cycles";
        case 2:
            return "L2 misses";
        case 3:
            return "Instr";
    }

    return "";
}
