//--------------------------------------------------------------------------------------
// Tasks.h
//
// Task definitions for all tasks used in the sample
//
// XNA Developer Connection
// Copyright (C) Microsoft Corporation. All rights reserved.
//--------------------------------------------------------------------------------------
#pragma once

//
// Task Identifiers
//

#define TASKID(Area,Number,Priority,Reschedulable,Async ) (WORD)( (WORD)(Area) << 11 | (WORD)(Number) << 5 | (WORD)(Priority) << 2 | (WORD)(Reschedulable) << 1 | (WORD)(Async) << 0 )
																		  // unused = bit 15
#define TASK_AREA( taskid )					( ( (taskid) >> 11 ) & 0xF )  // area = bits 11-14
#define TASK_NUMBER( taskid )				( ( (taskid) >> 5 )  & 0x3F ) // number = bits 5-10
#define TASK_PRIORITY( taskid )				( ( (taskid) >> 2 )  & 0x7 )  // pri = bits 2-4 
																		  // (lower number = higher priority)
#define TASK_RESCHEDULEABLE( taskid )	    ( ( (taskid) >> 1 )  & 0x1 )  // rescheduable = bit 0 (bReschedulable = 1)
#define TASK_ASYNC( taskid )				( ( (taskid) >> 0 )  & 0x1 )  // async = bit 0 (bAsync = 1)

#define PRIORITY_0  0
#define PRIORITY_1  1
#define PRIORITY_2  2
#define PRIORITY_3  3

#define RESCHEDULEABLE      1
#define NOTRESCHEDULEABLE   0

#define ASYNC               1
#define SYNC                0

//
// Task Areas
//

#define TASKAREA_NONE						(0x00)
#define TASKAREA_APP						(0x01)
#define TASKAREA_USERINPUT					(0x02)
#define TASKAREA_NETWORKMESSAGE             (0x03)
#define TASKAREA_XSESSION                   (0x04)
#define TASKAREA_XOVERLAPPED                (0x05)
#define TASKAREA_PRESENCE                   (0x06)
#define TASKAREA_CONTEXT                    (0x07)


//
// APP tasks
//
#define TASK_APP_CHANGE_STATE		        TASKID( TASKAREA_APP, 0x0, 0x1, NOTRESCHEDULEABLE, SYNC )

//
// Network message tasks
//
#define TASK_NETMSG_QUERY_SESSION           TASKID( TASKAREA_NETWORKMESSAGE, 0x0,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_RESP_SESSION            TASKID( TASKAREA_NETWORKMESSAGE, 0x1,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_JOIN_SESSION            TASKID( TASKAREA_NETWORKMESSAGE, 0x2,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_JOIN_RESPONSE           TASKID( TASKAREA_NETWORKMESSAGE, 0x3,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_JOIN_SESSION_PARTY      TASKID( TASKAREA_NETWORKMESSAGE, 0x4,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_JOIN_RESPONSE_PARTY     TASKID( TASKAREA_NETWORKMESSAGE, 0x5,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_PLAYER_INFO             TASKID( TASKAREA_NETWORKMESSAGE, 0x6,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_WAVE                    TASKID( TASKAREA_NETWORKMESSAGE, 0x7,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_START_SESSION           TASKID( TASKAREA_NETWORKMESSAGE, 0x8,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_END_SESSION             TASKID( TASKAREA_NETWORKMESSAGE, 0x9,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_FOUND_SESSION           TASKID( TASKAREA_NETWORKMESSAGE, 0xA,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_REGISTER                TASKID( TASKAREA_NETWORKMESSAGE, 0xB,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_REGISTERED              TASKID( TASKAREA_NETWORKMESSAGE, 0xC,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_SCORE_POINT             TASKID( TASKAREA_NETWORKMESSAGE, 0xD,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_POINT_TOTAL             TASKID( TASKAREA_NETWORKMESSAGE, 0xE,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_HEARTBEAT               TASKID( TASKAREA_NETWORKMESSAGE, 0x10, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_GOODBYE                 TASKID( TASKAREA_NETWORKMESSAGE, 0x11, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_VOICE                   TASKID( TASKAREA_NETWORKMESSAGE, 0x12, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_MUTE                    TASKID( TASKAREA_NETWORKMESSAGE, 0x13, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_MIGRATE                 TASKID( TASKAREA_NETWORKMESSAGE, 0x14, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_LEFT_SESSION            TASKID( TASKAREA_NETWORKMESSAGE, 0x15, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_SEND                    TASKID( TASKAREA_NETWORKMESSAGE, 0x16, PRIORITY_1/*high priority message*/, NOTRESCHEDULEABLE, SYNC )
#define TASK_NETMSG_RECV                    TASKID( TASKAREA_NETWORKMESSAGE, 0x17, PRIORITY_1/*high priority message*/, NOTRESCHEDULEABLE, SYNC )


//
// XSession tasks. For now, all synchronously executed
//
#define TASK_XSESSION_CREATE		        TASKID( TASKAREA_XSESSION, 0x0,  PRIORITY_2, NOTRESCHEDULEABLE, ASYNC/*Async*/ )
#define TASK_XSESSION_CREATED		        TASKID( TASKAREA_XSESSION, 0x1,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_JOIN		            TASKID( TASKAREA_XSESSION, 0x2,  PRIORITY_2, NOTRESCHEDULEABLE, ASYNC/*Async*/  )
#define TASK_XSESSION_LEAVE		            TASKID( TASKAREA_XSESSION, 0x3,  PRIORITY_2, NOTRESCHEDULEABLE, ASYNC/*Async*/  )
#define TASK_XSESSION_JOINED_LOCAL		    TASKID( TASKAREA_XSESSION, 0x4,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_JOINED_REMOTE		    TASKID( TASKAREA_XSESSION, 0x5,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_LEFT_LOCAL		    TASKID( TASKAREA_XSESSION, 0x6,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_LEFT_REMOTE		    TASKID( TASKAREA_XSESSION, 0x7,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_MODIFY		        TASKID( TASKAREA_XSESSION, 0x8,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_START		            TASKID( TASKAREA_XSESSION, 0x9,  PRIORITY_2, NOTRESCHEDULEABLE, ASYNC/*Async*/  )
#define TASK_XSESSION_STARTED		        TASKID( TASKAREA_XSESSION, 0xA,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_END		            TASKID( TASKAREA_XSESSION, 0xB,  PRIORITY_2, NOTRESCHEDULEABLE, ASYNC/*Async*/ )
#define TASK_XSESSION_ENDED		            TASKID( TASKAREA_XSESSION, 0xC,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_DELETE		        TASKID( TASKAREA_XSESSION, 0xD,  PRIORITY_2, NOTRESCHEDULEABLE, ASYNC/*Async*/ )
#define TASK_XSESSION_DELETED		        TASKID( TASKAREA_XSESSION, 0xE,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_DELETEMGR		        TASKID( TASKAREA_XSESSION, 0xF,  PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_WRITESTATS		    TASKID( TASKAREA_XSESSION, 0x10, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_WROTESTATS		    TASKID( TASKAREA_XSESSION, 0x11, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_CONNECTING		    TASKID( TASKAREA_XSESSION, 0x12, PRIORITY_2, RESCHEDULEABLE/*Rescheduleable*/, SYNC )
#define TASK_XSESSION_CONNECTED		        TASKID( TASKAREA_XSESSION, 0x13, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_MIGRATE		        TASKID( TASKAREA_XSESSION, 0x14, PRIORITY_2, NOTRESCHEDULEABLE, ASYNC/*Async*/ )
#define TASK_XSESSION_MIGRATING		        TASKID( TASKAREA_XSESSION, 0x15, PRIORITY_2, RESCHEDULEABLE/*Rescheduleable*/, SYNC )
#define TASK_XSESSION_MIGRATED		        TASKID( TASKAREA_XSESSION, 0x16, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_REGISTER_HOST_BEGIN   TASKID( TASKAREA_XSESSION, 0x20, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_REGISTER_HOST_WAIT    TASKID( TASKAREA_XSESSION, 0x21, PRIORITY_2, RESCHEDULEABLE/*Rescheduleable*/, SYNC )
#define TASK_XSESSION_REGISTER		        TASKID( TASKAREA_XSESSION, 0x22, PRIORITY_2, NOTRESCHEDULEABLE, ASYNC/*Async*/ )
#define TASK_XSESSION_REGISTERED		    TASKID( TASKAREA_XSESSION, 0x23, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_SEARCH		        TASKID( TASKAREA_XSESSION, 0x24, PRIORITY_2, NOTRESCHEDULEABLE, ASYNC/*Async*/ )
#define TASK_XSESSION_SEARCH_DONE		    TASKID( TASKAREA_XSESSION, 0x25, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_XSESSION_TASKGROUPDONE		    TASKID( TASKAREA_XSESSION, 0x26, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )

//
// XOverlapped tasks
// Note that overlapped tasks have the highest priorities (0 and 1) so that they are pushed to the top of the 
// task processing queue for immediate execution once their preconditions have been met. Cancelling a 
// pending overlapped operation has the highest priority
//
#define TASK_XOVERLAPPED_WAIT		        TASKID( TASKAREA_XOVERLAPPED, 0x0, PRIORITY_1, RESCHEDULEABLE/*Rescheduleable*/, SYNC )
#define TASK_XOVERLAPPED_CANCEL		        TASKID( TASKAREA_XOVERLAPPED, 0x1, PRIORITY_0, NOTRESCHEDULEABLE, SYNC )
#define TASK_XOVERLAPPED_CANCEL_DONE		TASKID( TASKAREA_XOVERLAPPED, 0x2, PRIORITY_0, NOTRESCHEDULEABLE, SYNC )

//
// Presence tasks
//
#define TASK_PRESENCE_ENUMFRIENDS           TASKID( TASKAREA_PRESENCE, 0x0, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_PRESENCE_ENUM		            TASKID( TASKAREA_PRESENCE, 0x1, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_PRESENCE_ENUMFRIENDS_DONE      TASKID( TASKAREA_PRESENCE, 0x2, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASK_PRESENCE_ENUM_DONE		        TASKID( TASKAREA_PRESENCE, 0x3, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )

//
// Context tasks
#define TASKAREA_CONTEXT_UPDATE_RP		    TASKID( TASKAREA_CONTEXT, 0x0, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
#define TASKAREA_CONTEXT_UPDATE_RP_DONE	    TASKID( TASKAREA_CONTEXT, 0x1, PRIORITY_2, NOTRESCHEDULEABLE, SYNC )
