#if 0
//
// Generated by 2.0.21256.0
//
//   fxc /nologo /Tvs_3_0 /Emain
//    /FhD:\Git\RXDK360-Samples\Graphics\CubicBezierPatch\DebugVS.h
//    /Vng_DebugVS
//    D:\Git\RXDK360-Samples\Graphics\CubicBezierPatch\DebugVS.hlsl
//
//
// Parameters:
//
//   row_major float4x4 matWorldViewProj;
//   float4 vColor;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   matWorldViewProj c0       4
//   vColor           c4       1
//

// Shader type: vertex 

xvs_3_0
defconst matWorldViewProj, float, matrix_rows, [4, 4], c0-3
defconst vColor, float, vector, [1, 4], c4
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=1
config VsResource=1

dcl_index r0.x
dcl_color o0


    exec
    vfetch r1, r0.x, position
    alloc position
    exec
    mul r0, r1.w, c3.xwzy
    mad r0, r1.z, c2.xwzy, r0
    mad r0, r1.y, c1.xzyw, r0.xzwy
    mad oPos, r1.x, c0, r0.xzyw
    alloc interpolators
    exece
    mov o0, c4

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_DebugVS[] =
{
    0x102a1101, 0x000000f0, 0x00000078, 0x00000000, 0x00000024, 0x00000000, 
    0x000000bc, 0x00000000, 0x00000000, 0x00000094, 0x0000001c, 0x00000087, 
    0xfffe0300, 0x00000002, 0x0000001c, 0x00000000, 0x00000080, 0x00000044, 
    0x00020000, 0x00040000, 0x00000058, 0x00000000, 0x00000068, 0x00020004, 
    0x00010000, 0x00000070, 0x00000000, 0x6d617457, 0x6f726c64, 0x56696577, 
    0x50726f6a, 0x00ababab, 0x00020003, 0x00040004, 0x00010000, 0x00000000, 
    0x76436f6c, 0x6f7200ab, 0x00010003, 0x00010004, 0x00010000, 0x00000000, 
    0x76735f33, 0x5f300032, 0x2e302e32, 0x31323536, 0x2e3000ab, 0x00000000, 
    0x00000078, 0x00010001, 0x00000000, 0x00000000, 0x00001021, 0x00000001, 
    0x00000001, 0x00000001, 0x00000290, 0x00000003, 0x0000f0a0, 0x00001008, 
    0x10011003, 0x00001200, 0xc2000000, 0x00004004, 0x00001200, 0xc4000000, 
    0x00001008, 0x00002200, 0x00000000, 0x05f81000, 0x00000688, 0x00000000, 
    0xc80f0000, 0x001b8800, 0xa1010300, 0xc80f0000, 0x00c68800, 0xab010200, 
    0xc80f0000, 0x00b13494, 0xab010100, 0xc80f803e, 0x006c0034, 0xab010000, 
    0xc80f8000, 0x00000000, 0x22040400, 0x00000000, 0x00000000, 0x00000000
};
