//--------------------------------------------------------------------------------------
// SkeletalPostProcessing.cpp
//
// Demonstrates a variety of skeleton joint data postprocessing filters.  These filters
// are useful for refining skeleton joint positions for certain game scenarios where
// joint position data needs to be more consistent for gameplay or aesthetic reasons.
// Some filters are intended for use in general situations, while others may be needed
// only in very specific situations.  Finally, each filter usually presents a tradeoff
// between motion fidelity and consistency - for example, the arms up filter can
// provide much more consistent arm positions when the user raises their arms above their
// head, but the filter removes some expressiveness in this scenario, such as the user
// waving their hands above their head.
//
// Copyright (C) Microsoft Corporation. All rights reserved.
//--------------------------------------------------------------------------------------

#include <assert.h>
#include <xtl.h>

#include <xavatar.h>
#include <xgraphics.h>

#include <AtgApp.h>
#include <AtgFont.h>
#include <AtgHelp.h>
#include <AtgInput.h>
#include <AtgSimpleShaders.h>
#include <AtgDebugDraw.h>
#include <AtgUtil.h>
#include <AtgNuiCommon.h>
#include <AtgNuiVisualization.h>

#include "AvatarRenderer.h"

#include "PatchCommon.h"
#include "SkeletonToFrameFilter.h"
#include "PatchLegs.h"
#include "PatchArmsUp.h"
#include "PatchConstraints.h"
#include "PatchBaseballSwing.h"


//--------------------------------------------------------------------------------------
// Callouts for labeling the gamepad on the help screen
//--------------------------------------------------------------------------------------
ATG::HELP_CALLOUT g_HelpCallouts[] =
{
    { ATG::HELP_BACK_BUTTON,    ATG::HELP_PLACEMENT_1, L"Display help" },
    { ATG::HELP_START_BUTTON,   ATG::HELP_PLACEMENT_1, L"Toggle UI" },
    { ATG::HELP_LEFT_SHOULDER,  ATG::HELP_PLACEMENT_1, L"Toggle debug info" },
    { ATG::HELP_LEFT_STICK,     ATG::HELP_PLACEMENT_1, L"Move Camera" },
    { ATG::HELP_RIGHT_STICK,    ATG::HELP_PLACEMENT_1, L"Rotate Camera" },
    { ATG::HELP_X_BUTTON,       ATG::HELP_PLACEMENT_1, L"Toggle preprocessing filters" },
    { ATG::HELP_B_BUTTON,       ATG::HELP_PLACEMENT_1, L"Cycle debug skeletons" },
    { ATG::HELP_A_BUTTON,       ATG::HELP_PLACEMENT_1, L"Cycle active filter set" },
    { ATG::HELP_Y_BUTTON,       ATG::HELP_PLACEMENT_1, L"Toggle Proportion Matching" },
};

// A single bit mask for each filter.  This will allow us to combine and select filters for simultaneous use.
static const DWORD FILTER_MASK_ARMS_UP          = (1<<1);
static const DWORD FILTER_MASK_HIP_RAISE        = (1<<2);
static const DWORD FILTER_MASK_CLIPPED_LEGS     = (1<<3);
static const DWORD FILTER_MASK_BASEBALL_SWING   = (1<<4);
static const DWORD FILTER_MASK_JOINT_SMOOTHING  = (1<<10);
static const DWORD FILTER_MASK_JOINT_CONSTRAINT = (1<<11);

// g_FilterMaskSets defines the specific filter combinations presented in the UI.
// Note that the order of the filters is defined by the order the filters are added to the
// filter stack in Sample::Initialize().
static const DWORD g_FilterMaskSets[] =
{
    FILTER_MASK_JOINT_CONSTRAINT,
    FILTER_MASK_ARMS_UP | FILTER_MASK_HIP_RAISE,
    FILTER_MASK_CLIPPED_LEGS,
    FILTER_MASK_JOINT_SMOOTHING | FILTER_MASK_BASEBALL_SWING
};
static const DWORD g_FilterMaskSetCount = ARRAYSIZE(g_FilterMaskSets);

static const DWORD NUM_HELP_CALLOUTS = ARRAYSIZE( g_HelpCallouts );

// Predicated tiling constants
static const DWORD g_dwTileWidth   = 1280;
static const DWORD g_dwTileHeight  = 256;
static const DWORD g_dwFrameWidth  = 1280;
static const DWORD g_dwFrameHeight = 720;
static const D3DRECT g_tiles[3] = 
{
    {             0,              0,  g_dwTileWidth,  g_dwTileHeight },
    {             0, g_dwTileHeight,  g_dwTileWidth, g_dwTileHeight * 2 },
    {             0, g_dwTileHeight * 2,  g_dwTileWidth, g_dwFrameHeight },
};

//--------------------------------------------------------------------------------------
// Name: class SampleDebugRenderer
// Desc: Implements the IFilterDebugRenderer class, which is used to present debug messages
// generated by skeleton filters.  This interface allows the skeleton filters to avoid
// taking a dependency on title-specific UI presentation code.  This specific implementation
// draws the debug messages on the right side of the sample's display, using the ATG::Font
// text drawing class.
//--------------------------------------------------------------------------------------
class SampleDebugRenderer : public IFilterDebugRenderer
{
protected:
    ATG::Font* m_pFont;
    FLOAT m_YPos;

public:
    SampleDebugRenderer( ATG::Font* pFont )
    {
        m_pFont = pFont;
        m_YPos = 0.0f;
    }
    
    virtual VOID SetTextYPos( FLOAT fYPos )
    {
        m_YPos = fYPos;
    }

    virtual FLOAT GetTextYPos() const
    {
        return m_YPos;
    }

    virtual VOID DrawTextLine( FLOAT fXScale, FLOAT fYScale, DWORD Color, FLOAT fRightOffset, BOOL bNewline, const WCHAR* strFormat, ... )
    {
        WCHAR strLine[1024];
        va_list pArgList;
        va_start( pArgList, strFormat );
        _vsnwprintf_s( strLine, _TRUNCATE, strFormat, pArgList );
        va_end( pArgList );

        m_pFont->SetScaleFactors( fXScale, fYScale );
        m_pFont->DrawText( -fRightOffset, m_YPos, Color, strLine, ATGFONT_RIGHT );

        if( bNewline )
        {
            DrawEmptyLine( fYScale );
        }
    }

    virtual VOID DrawEmptyLine( FLOAT fYScale )
    {
        m_YPos += 20.0f * fYScale;
    }

protected:
    virtual VOID StartRendering()
    {
        m_YPos = 60.0f;
        m_pFont->SetScaleFactors( 1, 1 );
        m_pFont->Begin();
    }

    virtual VOID EndRendering()
    {
        m_pFont->End();
        m_pFont->SetScaleFactors( 1, 1 );
    }
};

//--------------------------------------------------------------------------------------
// Name: class Sample
// Desc: Main class to run this application.
//--------------------------------------------------------------------------------------
class Sample : public ATG::Application
{
public:
    Sample() : m_bDrawHelp( FALSE ),
               m_dwCurFrontBuffer(0),
               m_pAvatarRenderer( NULL ),
               m_pAvatarRendererUnfiltered( NULL ),
               m_pAvatarNuiMapper( NULL ),
               m_pAvatarNuiMapperUnfiltered( NULL ),
               m_fLastNuiTime( 0.0f ),
               m_AvatarBodyType( XAVATAR_BODY_TYPE_UNKNOWN )
    {
    }

    virtual ~Sample()
    {
        // Note that this code will never actually be executed, as quitting a sample
        // simply reboots the dev kit; shutting down the system is not necessary in this
        // case. If it is necessary to shut down the system, this is the correct way to
        // do so.
        if( m_pAvatarRenderer )
            delete m_pAvatarRenderer;
        if( m_pAvatarRendererUnfiltered )
            delete m_pAvatarRendererUnfiltered;

        // Shutdown XAvatar and release memory
        XAvatarShutdown();
        NuiSkeletonTrackingDisable();
        NuiShutdown( );
    }

private:
    virtual HRESULT Initialize();
    virtual HRESULT Update();
    HRESULT         UpdateSkeletonTracking();
    VOID            CreateRenderTargets();
    virtual HRESULT Render();
    HRESULT         RenderBackground();
    VOID            RenderOverlays();
    VOID            RenderDebugSkeleton();
    VOID            RenderAvatarLabel( const XMMATRIX matWorld, const WCHAR* strLabel );

    VOID            CreateAvatarMappers();
    HRESULT         UpdateAnimation();
    HRESULT         UpdateBasis();

private:
    ATG::Timer                  m_Timer;
    ATG::Font                   m_Font;
    ATG::Help                   m_Help;
    BOOL                        m_bDrawHelp;
    BOOL                        m_bDrawUI;
    BOOL                        m_bMatchProportions;

    // View parameters
    FLOAT                       m_fLookPitch;
    FLOAT                       m_fLookYaw;
    XMVECTOR                    m_vEyePt;
    XMVECTOR                    m_vUp;
    XMMATRIX                    m_matView;
    XMMATRIX                    m_matProj; 
    XMMATRIX                    m_matWorld;
    XMMATRIX                    m_matWorldUnfiltered;

    // Rendering surfaces and textures
    D3DSurface*                 m_pBackBuffer;
    D3DSurface*                 m_pDepthBuffer;
    D3DTexture*                 m_pFrontBuffer[2];
    DWORD                       m_dwCurFrontBuffer;

    D3DTexture*                 m_pTextureGrass;
    D3DTexture*                 m_pTextureSky;
    D3DVertexDeclaration*       m_pBackgroundVertexDeclaration;
    D3DVertexShader*            m_pBackgroundVertexShader;
    D3DPixelShader*             m_pBackgroundPixelShader;
    ATG::PackedResource         m_Resource;

    IXAvatarNuiMapper*          m_pAvatarNuiMapper;
    IXAvatarNuiMapper*          m_pAvatarNuiMapperUnfiltered;
    XAVATAR_BODY_TYPE           m_AvatarBodyType;

    NUI_SKELETON_FRAME          m_Skeleton;
    UINT                        m_iCurrentTrackingID;
    UINT                        m_iCurrentSkeletonIndex;

    Bat                         m_Bat[ 2 ];
    NUI_SKELETON_FRAME          m_DebugSkeleton[2];
    BOOL                        m_bShowDebugSkeleton;

    HRESULT                     m_hrNuiResult;

    AvatarRenderer*             m_pAvatarRenderer;
    AvatarRenderer*             m_pAvatarRendererUnfiltered;

    FLOAT                       m_fLastNuiTime;

    // Visualize the depth and color buffers
    const NUI_IMAGE_FRAME*      m_pImageFrame;
    const NUI_IMAGE_FRAME*      m_pDepthFrame;
    const NUI_IMAGE_FRAME*      m_pSmallDepthFrame;

    ATG::NuiVisualization       m_pip;
    HANDLE                      m_hImage;
    HANDLE                      m_hDepth;
    HANDLE                      m_hSmallDepth;
    HANDLE                      m_hFrameEndEvent;

    // Skeleton filtering state
    DWORD                       m_dwFilterSetIndex;
    DWORD                       m_dwFilterMask;
    BOOL                        m_bShowFilterDebugInfo;

    // Skeleton filter framework
    FrameFilterStack            m_FilterStack;
    SampleDebugRenderer*        m_pFilterDebugRenderer;
};


//-------------------------------------------------------------------------------------
// Name: main()
// Desc: The application's entry point
//-------------------------------------------------------------------------------------
INT __cdecl main()
{
    Sample MyAtgApp;
    ZeroMemory( &MyAtgApp.m_d3dpp, sizeof( MyAtgApp.m_d3dpp ) );

    MyAtgApp.m_d3dpp.BackBufferWidth        = 1280;
    MyAtgApp.m_d3dpp.BackBufferHeight       = 720;
    MyAtgApp.m_d3dpp.BackBufferCount        = 1;
    MyAtgApp.m_d3dpp.MultiSampleType        = D3DMULTISAMPLE_4_SAMPLES;
    MyAtgApp.m_d3dpp.EnableAutoDepthStencil = FALSE;
    MyAtgApp.m_d3dpp.DisableAutoBackBuffer  = TRUE;
    MyAtgApp.m_d3dpp.DisableAutoFrontBuffer = TRUE;
    MyAtgApp.m_d3dpp.SwapEffect             = D3DSWAPEFFECT_DISCARD;
    MyAtgApp.m_d3dpp.PresentationInterval   = D3DPRESENT_INTERVAL_TWO;

    MyAtgApp.m_dwDeviceCreationFlags       |= D3DCREATE_BUFFER_2_FRAMES | D3DCREATE_CREATE_THREAD_ON_1;

    MyAtgApp.Run();
}

//--------------------------------------------------------------------------------------
// Name: Initialize()
// Desc: Creates all graphics resources and initializes rendering and animation systems.
//--------------------------------------------------------------------------------------
HRESULT Sample::Initialize()
{
    m_iCurrentSkeletonIndex = 0;
    m_iCurrentTrackingID = 0;
    m_bShowDebugSkeleton = TRUE;
    m_bDrawUI = TRUE;
    m_bMatchProportions = TRUE;
    m_hrNuiResult = E_FAIL;

    // Initialize the avatar library
    static const DWORD dwAssetLoadHardwareThread = 5;
    if( FAILED( XAvatarInitialize(      XAVATAR_COORDINATE_SYSTEM_RIGHT_HANDED, 
                                        0, 
                                        dwAssetLoadHardwareThread,
                                        0,    
                                        0) ) ) 
    {
        ATG_PrintError( "Unable to load Avatar asset pack\n");
        return E_FAIL;
    }
    
    m_hFrameEndEvent = CreateEvent( NULL,
                                    FALSE,  // auto-reset
                                    FALSE,  // create unsignaled
                                    "NuiFrameEndEvent" );

    if ( !m_hFrameEndEvent )
    {
        ATG_PrintError( "Failed to create NuiFrameEndEvent\n" );
        return E_FAIL;
    }
    
    HRESULT hr = NuiInitialize( NUI_INITIALIZE_FLAG_USES_SKELETON |
                                NUI_INITIALIZE_FLAG_USES_COLOR |
                                NUI_INITIALIZE_FLAG_USES_DEPTH_AND_PLAYER_INDEX |
                                NUI_INITIALIZE_FLAG_NUI_GUIDE_DISABLED,
                                NUI_INITIALIZE_DEFAULT_HARDWARE_THREAD );

    if ( FAILED(hr))
    {
        ATG::NuiPrintError( hr, "NuiInitialize" );
        return E_FAIL;
    }

    hr = NuiSetFrameEndEvent( m_hFrameEndEvent, 0 );
    if( FAILED(hr) )
    {
        ATG::NuiPrintError( hr, "NuiSetFrameEndEvent" );
        return E_FAIL;
    }
    
    // Open the color stream
    hr = NuiImageStreamOpen( NUI_IMAGE_TYPE_COLOR, NUI_IMAGE_RESOLUTION_640x480, 0, 1, NULL, &m_hImage );
    if ( FAILED (hr) )
    {
        ATG::NuiPrintError( hr, "NuiImageStreamOpen" );
        return E_FAIL;
    }

    // Open the depth stream
    hr = NuiImageStreamOpen( NUI_IMAGE_TYPE_DEPTH_AND_PLAYER_INDEX, NUI_IMAGE_RESOLUTION_320x240, 0, 1, NULL, &m_hDepth );
    if ( FAILED (hr) )
    {
        ATG::NuiPrintError( hr, "NuiImageStreamOpen" );
        return E_FAIL;
    }

    // Open the small depth stream
    hr = NuiImageStreamOpen( NUI_IMAGE_TYPE_DEPTH_AND_PLAYER_INDEX_80x60, NUI_IMAGE_RESOLUTION_80x60, 0, 1, NULL, &m_hSmallDepth );
    if ( FAILED (hr) )
    {
        ATG::NuiPrintError( hr, "NuiImageStreamOpen" );
        return E_FAIL;
    }

    hr = NuiSkeletonTrackingEnable( NULL, 0 );
    if ( FAILED( hr ))
    {
        ATG::NuiPrintError( hr, "NuiSkeletonTrackingEnable" );
    }

    // Obtain the avatar metadata for the user.  If the call fails, (the user doesn't
    // have an avatar associated with their profile yet or no one is 
    // signed in) then just load a random avatar.
    XAVATAR_METADATA metadata;
    if( ERROR_SUCCESS != XAvatarGetMetadataLocalUser( 0, &metadata, NULL ) )
    {
        if ( ERROR_SUCCESS != XAvatarGetMetadataRandom( XAVATAR_BODY_TYPE_ALL, 1, &metadata, NULL ) )
        {
            return E_FAIL;
        }
    }

    m_pAvatarRenderer = new AvatarRenderer( m_pd3dDevice, metadata );
    m_pAvatarRendererUnfiltered = new AvatarRenderer( m_pd3dDevice, metadata );

    m_AvatarBodyType = XAvatarMetadataGetBodyType( &metadata );


    // Create background vertex shader
    static const D3DVERTEXELEMENT9 backgroundDecl[] =
    {
        { 0,  0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT,  D3DDECLUSAGE_POSITION, 0 },
        { 0, 12, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT,  D3DDECLUSAGE_TEXCOORD, 0 },
        D3DDECL_END()
    };

    if( FAILED( hr = m_pd3dDevice->CreateVertexDeclaration( backgroundDecl, &m_pBackgroundVertexDeclaration ) ) )
        ATG::FatalError( "Error %#X creating Vertex Declaration\n", hr );

    VOID* pCode = NULL;
    if( FAILED( hr = ATG::LoadFile( "game:\\Media\\Shaders\\background_vs.xvu", &pCode ) ) )
        ATG::FatalError( "Error %#X creating Vertex Shader\n", hr );

    if( FAILED( hr = m_pd3dDevice->CreateVertexShader( ( DWORD* )pCode, &m_pBackgroundVertexShader ) ) )
        ATG::FatalError( "Error %#X creating Vertex Shader\n", hr );
    ATG::UnloadFile( pCode );

    // Create background pixel shader
    if( FAILED( hr = ATG::LoadFile( "game:\\Media\\Shaders\\background_ps.xpu", &pCode ) ) )
        ATG::FatalError( "Error %#X creating Pixel Shader\n", hr );

    if( FAILED( hr = m_pd3dDevice->CreatePixelShader( ( DWORD* )pCode, &m_pBackgroundPixelShader ) ) )
        ATG::FatalError( "Error %#X creating Pixel Shader\n", hr );
    ATG::UnloadFile( pCode );


    // Initialize view parameters
    XVIDEO_MODE VideoMode;
    XGetVideoMode( &VideoMode );
    FLOAT fAspectRatio = VideoMode.fIsWideScreen == TRUE ? (16.0f / 9.0f) : (4.0f / 3.0f);
    m_matProj    = XMMatrixPerspectiveFovRH( XM_PI/4, fAspectRatio, 0.01f, 20.0f ); 
    static const XMVECTORF32 g_svEyePt = {-1.0f,1.0f,2.0f,0.0f};
    static const XMVECTORF32 g_svUp = {0.0f,1.0f,0.0f,0.0f};
    m_vEyePt     = g_svEyePt;
    m_vUp        = g_svUp;
    m_fLookPitch = 0.0f;
    m_fLookYaw   = 0.0f;

    CreateRenderTargets();

    // Create the font
    if( FAILED( m_Font.Create( "d:\\Media\\Fonts\\Arial_16.xpr" ) ) )
        return ATGAPPERR_MEDIANOTFOUND;

    // Confine text drawing to the title safe area
    m_Font.SetWindow( ATG::GetTitleSafeArea() );

    // Create the help
    if( FAILED( m_Help.Create( "d:\\Media\\Help\\Help.xpr" ) ) )
        return ATGAPPERR_MEDIANOTFOUND;

    ATG::SimpleShaders::Initialize( NULL, NULL );

    // Initialize the Picture in Picture visualization
    if( FAILED( m_pip.Initialize( m_pd3dDevice, NUI_INITIALIZE_FLAG_USES_COLOR |
                                                NUI_INITIALIZE_FLAG_USES_DEPTH_AND_PLAYER_INDEX |
                                                NUI_INITIALIZE_FLAG_USES_SKELETON, 
                                                NUI_IMAGE_RESOLUTION_640x480 ) ) )
    {
        ATG_PrintError ( "Picture in Picture initialization failed" );
    }

    if( FAILED( hr = m_Resource.Create( "d:\\Media\\Resource.xpr" ) ) )
        return ATGAPPERR_MEDIANOTFOUND;
    m_pTextureGrass = m_Resource.GetTexture( "Ground" );
    m_pTextureSky = m_Resource.GetTexture( "Sky" );
    
    // Create the Avatar NUI Mapper
    CreateAvatarMappers();

    // Initialize the filter stack
    m_FilterStack.Initialize();

    // Add the filters to the filter stack.  The order of addition dictates
    // the order of filter application.  Each filter has an associated bitmask
    // so a subset of filters in the stack can be selected or ignored.
    m_FilterStack.AddFilter( new SkeletonToFrameFilter<FilterJointSmoothing>(), FILTER_MASK_JOINT_SMOOTHING );
    m_FilterStack.AddFilter( new SkeletonToFrameFilter<FilterJointConstraints>(), FILTER_MASK_JOINT_CONSTRAINT );
    m_FilterStack.AddFilter( new SkeletonToFrameFilter<FilterHipHeight>(), FILTER_MASK_HIP_RAISE );
    m_FilterStack.AddFilter( new SkeletonToFrameFilter<FilterArmsUp>(), FILTER_MASK_ARMS_UP );
    m_FilterStack.AddFilter( new SkeletonToFrameFilter<FilterClippedLegs>(), FILTER_MASK_CLIPPED_LEGS );
    m_FilterStack.AddFilter( new SkeletonToFrameFilter<FilterBaseballSwing>(), FILTER_MASK_BASEBALL_SWING );

    m_dwFilterSetIndex = 0;
    m_dwFilterMask = g_FilterMaskSets[m_dwFilterSetIndex];
    m_bShowFilterDebugInfo = FALSE;

    // Initialize the filter debug renderer.
    m_pFilterDebugRenderer = new SampleDebugRenderer( &m_Font );

    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: CreateRenderTargets()
// Desc: Create RenderTargets, Back/Front Buffers, and Depth Stencil
//--------------------------------------------------------------------------------------
VOID Sample::CreateRenderTargets()
{
    D3DSURFACE_PARAMETERS params = {0};

    m_pd3dDevice->CreateRenderTarget(
        g_dwTileWidth, g_dwTileHeight, D3DFMT_X8R8G8B8, D3DMULTISAMPLE_4_SAMPLES, 0, 0, &m_pBackBuffer, &params );

    params.Base = m_pBackBuffer->Size / GPU_EDRAM_TILE_SIZE;
    params.HierarchicalZBase = 0;
    m_pd3dDevice->CreateDepthStencilSurface(
        g_dwTileWidth, g_dwTileHeight, D3DFMT_D24S8, D3DMULTISAMPLE_4_SAMPLES, 0, 0, &m_pDepthBuffer, &params );

    m_pd3dDevice->CreateTexture(
        g_dwFrameWidth, g_dwFrameHeight, 1, 0, D3DFMT_LE_X8R8G8B8, 0, &m_pFrontBuffer[0], NULL );
    m_pd3dDevice->CreateTexture(
        g_dwFrameWidth, g_dwFrameHeight, 1, 0, D3DFMT_LE_X8R8G8B8, 0, &m_pFrontBuffer[1], NULL );
    
}


//--------------------------------------------------------------------------------------
// Name: UpdateSkeletonTracking()
// Desc: Read the data from the camera stream synchronously each frame and pass the
//       depthmap on to the skeleton tracking. 
// The Nui API will wait up to NUI_CAMERA_TIMEOUT_DEFAULT ms for a new skeleton.
//--------------------------------------------------------------------------------------
HRESULT Sample::UpdateSkeletonTracking()
{
    if( WAIT_OBJECT_0 != WaitForSingleObject( m_hFrameEndEvent, NUI_FRAME_END_TIMEOUT_DEFAULT ) )
    {
        return E_FAIL;
    }

    // Get data from the next image frame
    HRESULT hrImage = NuiImageStreamGetNextFrame( m_hImage, 0, &m_pImageFrame );
    // Get data from the next camera depth frame
    HRESULT hrDepth = NuiImageStreamGetNextFrame( m_hSmallDepth, 0, &m_pSmallDepthFrame );
    if( SUCCEEDED(hrDepth) )
    {
        hrDepth = NuiImageStreamGetNextFrame( m_hDepth, 0, &m_pDepthFrame );
    }
    m_hrNuiResult = NuiSkeletonGetNextFrame( 0, &m_Skeleton );

    if ( SUCCEEDED( hrImage ) )
    {
        m_pip.SetColorTexture( m_pImageFrame->pFrameTexture );
        NuiImageStreamReleaseFrame( m_hImage, m_pImageFrame );
    }
    
    if ( SUCCEEDED( hrDepth ) )
    {
        m_pip.SetDepthTexture( m_pDepthFrame->pFrameTexture );
        m_FilterStack.FilterDepthTexture( m_pDepthFrame->pFrameTexture, m_pSmallDepthFrame->pFrameTexture );
        NuiImageStreamReleaseFrame( m_hDepth, m_pDepthFrame );
        NuiImageStreamReleaseFrame( m_hSmallDepth, m_pSmallDepthFrame );
    }

    if ( m_hrNuiResult == E_PENDING || FAILED ( m_hrNuiResult ) )
    {
        return m_hrNuiResult;
    }
    else
    {
        // If the last tracking ID no longer exists in the skeleton data, then switch to
        // the first tracked skeleton we can find. If none is tracked, then leave the current 
        // tracking ID as is and try again next frame.
        for ( int i = NUI_SKELETON_COUNT - 1; i >= 0 ; --i )
        {
            if ( m_Skeleton.SkeletonData[ i ].eTrackingState == NUI_SKELETON_TRACKED )
            {
                m_iCurrentSkeletonIndex = i;

                if ( m_iCurrentTrackingID == m_Skeleton.SkeletonData[i].dwTrackingID )
                {
                    break;
                }
            }
        }

        m_iCurrentTrackingID = m_Skeleton.SkeletonData[ m_iCurrentSkeletonIndex ].dwTrackingID;
    }

    return S_OK;
}


VOID Sample::CreateAvatarMappers()
{
    // Recreate the avatar NUI Mapper for the filtered data.
    SAFE_RELEASE( m_pAvatarNuiMapper );

    HRESULT hr;

    if( FAILED( hr = XAvatarCreateNuiMapper( m_pAvatarRenderer->GetSkeleton(), m_AvatarBodyType, &m_pAvatarNuiMapper ) ) )
        ATG::FatalError( "Error %#X creating Nui Mapper\n", hr );

    // Recreate the avatar NUI Mapper for the unfiltered data.
    SAFE_RELEASE( m_pAvatarNuiMapperUnfiltered );

    if( FAILED( hr = XAvatarCreateNuiMapper( m_pAvatarRendererUnfiltered->GetSkeleton(), m_AvatarBodyType, &m_pAvatarNuiMapperUnfiltered ) ) )
        ATG::FatalError( "Error %#X creating Nui Mapper\n", hr );

    // Reset avatar mapper options for both avatar renderers.
    XAVATAR_NUI_MAPPER_OPTIONS options = { 0 };
    m_pAvatarNuiMapper->GetOptions( &options );

    options.GeneralOptions.MirrorSkeleton = TRUE;
    options.GeneralOptions.PreventSelfIntersection = FALSE;
    options.GeneralOptions.RescaleToUserProportions = m_bMatchProportions;

    // Note that we opt to use the avatar remapping library temporal filter, to smooth motion across render frames.
    options.GeneralOptions.SkeletonDataIsFiltered = FALSE;

    options.GeneralOptions.DisableJumping = FALSE;
    m_pAvatarNuiMapper->SetOptions( &options );
    m_pAvatarNuiMapperUnfiltered->SetOptions( &options );

    // Reset the skeleton filter states.
    m_FilterStack.ResetFilterState();
}


//--------------------------------------------------------------------------------------
// Name: Update()
// Desc: Called once per frame.  Entry point for animating the scene.
//--------------------------------------------------------------------------------------
HRESULT Sample::Update()
{
    PIXBeginNamedEvent( 0, __FUNCTION__ );

    // Get elapsed time
    FLOAT fDeltaRenderTime = ( FLOAT )m_Timer.GetElapsedTime();

    // Get current gamepad state
    ATG::GAMEPAD* pGamepad = ATG::Input::GetMergedInput();

    // The Back button toggles the help screen.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_BACK )
        m_bDrawHelp = !m_bDrawHelp;

    // The Start button hides all UI.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_START )
        m_bDrawUI = !m_bDrawUI;

    // The X button toggles whether the filters are enabled or not.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_X )
        m_FilterStack.SetEnabled( !m_FilterStack.IsEnabled() );

    // The B button cycles through debug skeleton views.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_B )
    {
        m_bShowDebugSkeleton = !m_bShowDebugSkeleton;
    }

    // The A button cycles the active filter set.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_A )
    {
        m_dwFilterSetIndex = ( m_dwFilterSetIndex + 1 ) % g_FilterMaskSetCount;
        m_dwFilterMask = g_FilterMaskSets[m_dwFilterSetIndex];
        m_FilterStack.ResetFilterState();
    }

    // The left shoulder button toggles filter debug info.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_LEFT_SHOULDER )
    {
        m_bShowFilterDebugInfo = !m_bShowFilterDebugInfo;
    }

    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_Y )
    {
        m_bMatchProportions = !m_bMatchProportions;
        CreateAvatarMappers();
    }

    // Rotate view
    m_fLookYaw     -= pGamepad->fX2 * fDeltaRenderTime;
    m_fLookPitch   -= pGamepad->fY2 * fDeltaRenderTime;
    m_fLookYaw     = fmodf( m_fLookYaw, XM_2PI );
    m_fLookPitch   = fmodf( m_fLookPitch, XM_2PI );

    XMMATRIX lookAtMatrix   = XMMatrixRotationRollPitchYaw( m_fLookPitch, m_fLookYaw, 0.0f );
    static const XMVECTORF32 g_vTransform = {0.0f,0.0f,-1.0f,1.0f};
    XMVECTOR m_vLookToZ     = XMVector3Transform(g_vTransform, lookAtMatrix);

    // Move viewing position
    m_vEyePt = XMVectorAdd(m_vEyePt, XMVectorScale(lookAtMatrix.r[0], fDeltaRenderTime * pGamepad->fX1));
    m_vEyePt = XMVectorAdd(m_vEyePt, XMVectorScale(lookAtMatrix.r[2], fDeltaRenderTime * -pGamepad->fY1));

    m_matView               = XMMatrixLookToRH( m_vEyePt, m_vLookToZ, m_vUp );

    // Get the skeleton
    UpdateSkeletonTracking();

    // Convert the skeleton to avatar skinning data.  NUI joint positions are converted
    // to avatar joint rotations.

    if( m_pAvatarNuiMapper && m_pAvatarNuiMapperUnfiltered )
    {
        FLOAT fCurrentNuiTime = (FLOAT)m_Timer.GetAbsoluteTime();
        FLOAT fDeltaNuiTime = fCurrentNuiTime - m_fLastNuiTime;

        // if we successfully retrieved skeleton data, set the data. At most this
        // will be set at 30Hz
        if( SUCCEEDED( m_hrNuiResult ) )
        {
            m_pAvatarNuiMapperUnfiltered->SetNuiSkeletonData( &m_Skeleton, m_iCurrentTrackingID );
        }

        // Capture the unfiltered skeleton data to the debug skeleton.
        if( m_bShowDebugSkeleton )
        {
            XMemCpy( &m_DebugSkeleton[0], &m_Skeleton, sizeof(NUI_SKELETON_FRAME) );
            if( g_FilterMaskSets[ m_dwFilterSetIndex ] & FILTER_MASK_BASEBALL_SWING )
            {
                m_Bat[ 0 ].Update( &m_DebugSkeleton[ 0 ].SkeletonData[ m_iCurrentSkeletonIndex ] );
            }
        }

        const NUI_SKELETON_FRAME* pFrame = &m_Skeleton;
        
        if( SUCCEEDED( m_hrNuiResult ) )
        {
            // Post process the skeleton data using the filter stack.  
            // If filtering is disabled, pFrame will point to an unchanged m_Skeleton.
            pFrame = m_FilterStack.FilterFrame( &m_Skeleton, fDeltaNuiTime, m_dwFilterMask );
        }

        m_pAvatarNuiMapper->SetNuiSkeletonData( pFrame, m_iCurrentTrackingID );
        
        // Capture the filtered skeleton data to the debug skeleton.
        if( m_bShowDebugSkeleton )
        {
            XMemCpy( &m_DebugSkeleton[1], pFrame, sizeof(NUI_SKELETON_FRAME) );
            if( g_FilterMaskSets[ m_dwFilterSetIndex ] & FILTER_MASK_BASEBALL_SWING )
            {
                m_Bat[ 1 ].Update( &m_DebugSkeleton[ 1 ].SkeletonData[ m_iCurrentSkeletonIndex ] );
            }
        }

        // Send the filtered skeleton data to the color & depth view skeletons.
        m_pip.SetSkeletons( pFrame );

        // Convert the skeleton to avatar skinning data.  NUI joint positions are converted
        // to avatar joint rotations. For this sample this update should run at 60Hz since
        // it uses PRESENT_INTERVAL_ONE and the m_pAvatarNuiMapper extrapolates data
        m_pAvatarNuiMapper->Update( fDeltaRenderTime );
        m_pAvatarNuiMapperUnfiltered->Update( fDeltaRenderTime );
        
        m_fLastNuiTime = fCurrentNuiTime;

        UpdateBasis();     // Update the rotation of the avatar to match with the skeleton
    }

    // Update the animation and avatar with the newly converted skinning data
    UpdateAnimation();

    PIXEndNamedEvent();
    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: UpdateAnimation()
// Desc: Updates the animation stream and blends between the previous and next frames.
//       Called once per frame.
//--------------------------------------------------------------------------------------
HRESULT Sample::UpdateAnimation()
{
    if( SUCCEEDED( m_hrNuiResult ) && m_pAvatarNuiMapper && m_pAvatarNuiMapperUnfiltered )
    {
        // Animation data - updated every frame from the NUI skeleton
        XAVATAR_SKELETON_POSE_JOINT AvatarJointPose[ XAVATAR_MAX_SKELETON_JOINTS ]; 

        for ( DWORD j = 0; j < m_pAvatarRenderer->GetSkeleton()->Count; ++j )
        {
            m_pAvatarNuiMapper->GetJointPose( j, &AvatarJointPose[j], NULL );
        }
        m_pAvatarRenderer->SetJoints( AvatarJointPose );
        m_pAvatarRenderer->Update();

        for ( DWORD j = 0; j < m_pAvatarRendererUnfiltered->GetSkeleton()->Count; ++j )
        {
            m_pAvatarNuiMapperUnfiltered->GetJointPose( j, &AvatarJointPose[j], NULL );
        }
        m_pAvatarRendererUnfiltered->SetJoints( AvatarJointPose );
        m_pAvatarRendererUnfiltered->Update();

        return S_OK;
    }
    else
    {
        return E_FAIL;
    }
}


//--------------------------------------------------------------------------------------
// Name: UpdateBasis()
// Desc: Rotate Avatar with user.
//--------------------------------------------------------------------------------------
HRESULT Sample::UpdateBasis( )
{
    XAVATAR_NUI_MAPPER_TRANSFORM_INFO info;

    assert( m_pAvatarNuiMapper );
    if ( SUCCEEDED( m_pAvatarNuiMapper->GetAvatarTransformInfo( &info ) ) )
    {
        XMMATRIX rotMtx = XMMatrixRotationY( info.YawInRadians );
        XMMATRIX transMtx = XMMatrixTranslation( info.Position.x, info.Position.y, info.Position.z );

        m_matWorld = rotMtx * transMtx;
    }

    assert( m_pAvatarNuiMapperUnfiltered );
    if ( SUCCEEDED( m_pAvatarNuiMapperUnfiltered->GetAvatarTransformInfo( &info ) ) )
    {
        XMMATRIX rotMtx = XMMatrixRotationY( info.YawInRadians );
        XMMATRIX transMtx = XMMatrixTranslation( info.Position.x, info.Position.y, info.Position.z );

        m_matWorldUnfiltered = rotMtx * transMtx * XMMatrixTranslation( -1.0f, 0, 0 );
    }

    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: RenderBackground()
// Desc: Renders the background.
//--------------------------------------------------------------------------------------
HRESULT Sample::RenderBackground()
{
    struct FloorVert
    {
        float    x, y, z;
        float    u, v;
    };

    PIXBeginNamedEvent( 0xFFFFFFFF, "Background Render" );

    m_pd3dDevice->SetRenderState_Inline( D3DRS_ZENABLE, TRUE );
    m_pd3dDevice->SetRenderState_Inline( D3DRS_ZWRITEENABLE, TRUE );
    m_pd3dDevice->SetRenderState_Inline( D3DRS_DEPTHBIAS, 0 );
    m_pd3dDevice->SetRenderState_Inline( D3DRS_ALPHABLENDENABLE, FALSE );
    m_pd3dDevice->SetRenderState_Inline( D3DRS_ALPHATESTENABLE, FALSE );
    m_pd3dDevice->SetRenderState_Inline( D3DRS_VIEWPORTENABLE, TRUE );

    m_pd3dDevice->SetVertexDeclaration( m_pBackgroundVertexDeclaration );
    m_pd3dDevice->SetVertexShader( m_pBackgroundVertexShader );
    m_pd3dDevice->SetPixelShader( m_pBackgroundPixelShader );

    FLOAT floorWidth = 31.0f;
    FloorVert floorVerts[4] = 
    {
        {  floorWidth, 0.0f, -floorWidth, 8.0f, 0.0f },
        { -floorWidth, 0.0f, -floorWidth, 0.0f, 0.0f },
        {  floorWidth, 0.0f,  floorWidth, 8.0f, 8.0f },
        { -floorWidth, 0.0f,  floorWidth, 0.0f, 8.0f }
    };

    INT skySections = 40;
    FloorVert skyVerts[82];

    FloorVert* skyVert = skyVerts;

    const FLOAT uOffset = .12f;
    for ( INT i = 0; i < skySections + 1; i ++ )
    {
        FLOAT width = 6.0f;

        skyVert->x = sinf( (i * 2 * D3DX_PI) / skySections ) * width;
        skyVert->y = 0.0f;
        skyVert->z = cosf( (i * 2 * D3DX_PI) / skySections ) * width;
        skyVert->u = -(2*i) / (FLOAT)skySections + uOffset;
        skyVert->v = 1.0f;
        skyVert++;

        skyVert->x = sinf( (i * 2 * D3DX_PI) / skySections ) * width;
        skyVert->y = 17.0f;
        skyVert->z = cosf( (i * 2 * D3DX_PI) / skySections ) * width;
        skyVert->u = -(2*i) / (FLOAT)skySections + uOffset;
        skyVert->v = -4.5f;
        skyVert++;
    }

    XMMATRIX id = XMMatrixIdentity();
    m_pd3dDevice->SetSamplerState(0, D3DSAMP_ADDRESSU, D3DTADDRESS_WRAP);
    m_pd3dDevice->SetSamplerState(0, D3DSAMP_ADDRESSV, D3DTADDRESS_WRAP);

    m_pd3dDevice->SetVertexShaderConstantF( 0, (FLOAT*)&m_matView, 4 );
    m_pd3dDevice->SetVertexShaderConstantF( 4, (FLOAT*)&m_matProj, 4 );
    m_pd3dDevice->SetRenderState( D3DRS_CULLMODE, D3DCULL_NONE );

    m_pd3dDevice->SetTexture( 0, m_pTextureGrass );
    m_pd3dDevice->DrawPrimitiveUP( D3DPT_TRIANGLESTRIP, 2, &floorVerts, sizeof(FloorVert) );

    m_pd3dDevice->SetTexture( 0, m_pTextureSky );
    m_pd3dDevice->SetSamplerState(0, D3DSAMP_ADDRESSV, D3DTADDRESS_CLAMP);
    m_pd3dDevice->DrawPrimitiveUP( D3DPT_TRIANGLESTRIP, skySections*2, &skyVerts, sizeof(FloorVert) );

    PIXEndNamedEvent();

    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: Render()
// Desc: Renders the scene.
//--------------------------------------------------------------------------------------
HRESULT Sample::Render()
{
    PIXBeginNamedEvent( 0, __FUNCTION__ );
    {
        // Render scene
        static const D3DVECTOR4 clearColor = { 0.75f, 0.78f, 0.86f, 1.0f };
        m_pd3dDevice->SetRenderTarget( 0, m_pBackBuffer );
        m_pd3dDevice->SetDepthStencilSurface( m_pDepthBuffer );
        m_pd3dDevice->BeginTiling( 0, ARRAYSIZE(g_tiles), g_tiles, &clearColor, 1, 0 );

        RenderBackground();

        PIXBeginNamedEvent( 0xFFFFFFFF, "Avatar Render" );
        {
            if( m_Skeleton.SkeletonData[ m_iCurrentSkeletonIndex ].eTrackingState == NUI_SKELETON_TRACKED )
            {
                m_pAvatarRenderer->Render( m_matWorld, m_matView, m_matProj );
                m_pAvatarRendererUnfiltered->Render( m_matWorldUnfiltered, m_matView, m_matProj );
            }
        }

        PIXEndNamedEvent();

        RenderDebugSkeleton();

        if( m_bDrawUI )
        {
            RenderOverlays();

            // Draw the raw depth and image map with skeleton overlaid as visualization.
            const FLOAT drawWidth = 200.0f;
            const FLOAT drawHeight = drawWidth * 3.0f / 4.0f;
            const FLOAT drawX = 50.0f;
            const FLOAT drawY = 720.0f - 50.0f - drawHeight;
            const FLOAT border = 10.0f;
            m_pip.BeginRender();
            m_pip.RenderColorStream( drawX, drawY, drawWidth, drawHeight );
            m_pip.RenderSkeletons( drawX, drawY, drawWidth, drawHeight, TRUE, TRUE );
            m_pip.RenderDepthStream( drawX + drawWidth + border, drawY, drawWidth, drawHeight );
            m_pip.RenderSkeletons( drawX + drawWidth + border, drawY, drawWidth, drawHeight, TRUE, FALSE );
            m_pip.EndRender();
        }

        m_pd3dDevice->EndTiling( 0, NULL, m_pFrontBuffer[m_dwCurFrontBuffer], NULL, 1, 0, NULL );
        
        // Present the backbuffer contents to the display
        m_pd3dDevice->SynchronizeToPresentationInterval();
        m_pd3dDevice->Swap( m_pFrontBuffer[ m_dwCurFrontBuffer ], NULL );
        // Flip buffers
        m_dwCurFrontBuffer = ( m_dwCurFrontBuffer + 1 ) & 1;

        m_Timer.MarkFrame();
    }
    PIXEndNamedEvent();
    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: RenderDebugSkeleton()
// Desc: Renders joint positions from a NUI_SKELETON_DATA structure in 3D.
//--------------------------------------------------------------------------------------
VOID Sample::RenderDebugSkeleton()
{
    if( !m_bShowDebugSkeleton )
    {
        return;
    }

    // Apply a translation and scale to place the skeleton to the left of the postprocessed avatar.
    XMMATRIX matVP = XMMatrixTranslation( -2, 0.75f, 0 ) * XMMatrixScaling( 1, 1, -1 ) * m_matView * m_matProj;
    ATG::DebugDraw::SetViewProjection( matVP );

    m_pd3dDevice->SetRenderState( D3DRS_LINEWIDTH, ATG::FtoDW( 4.0f ) );

    for( DWORD i = 1; i < NUI_SKELETON_POSITION_COUNT; ++i )
    {
        // Draw a thick line from current joint to parent joint.
        DWORD EndIndex = i;
        DWORD StartIndex = g_SkeletonParentIndex[i];

        XMVECTOR vStart = m_DebugSkeleton[0].SkeletonData[m_iCurrentSkeletonIndex].SkeletonPositions[StartIndex];
        XMVECTOR vEnd = m_DebugSkeleton[0].SkeletonData[m_iCurrentSkeletonIndex].SkeletonPositions[EndIndex];

        // Select the color based on tracking state.
        DWORD Color = 0xFF00FF00;
        switch( m_DebugSkeleton[0].SkeletonData[m_iCurrentSkeletonIndex].eSkeletonPositionTrackingState[EndIndex] )
        {
        case NUI_SKELETON_POSITION_INFERRED:
            Color = 0xFFFF0000;
            break;
        case NUI_SKELETON_POSITION_NOT_TRACKED:
            continue;
        }

        ATG::DebugDraw::DrawLineSegment( *(XMFLOAT3*)&vStart, *(XMFLOAT3*)&vEnd, Color );
    }

    if( g_FilterMaskSets[ m_dwFilterSetIndex ] & FILTER_MASK_BASEBALL_SWING )
    {
        XMVECTOR vStart = m_Bat[ 0 ].Start();
        XMVECTOR vEnd   = m_Bat[ 0 ].End();
        ATG::DebugDraw::DrawLineSegment( *(XMFLOAT3*)&vStart, *(XMFLOAT3*)&vEnd, 0xFF0000FF );
    }

    // Apply a translation and scale to place the skeleton to the left of the postprocessed avatar.
    matVP = XMMatrixTranslation( 1, 0.75f, 0 ) * XMMatrixScaling( 1, 1, -1 ) * m_matView * m_matProj;
    ATG::DebugDraw::SetViewProjection( matVP );

    for( DWORD i = 1; i < NUI_SKELETON_POSITION_COUNT; ++i )
    {
        // Draw a thick line from current joint to parent joint.
        DWORD EndIndex = i;
        DWORD StartIndex = g_SkeletonParentIndex[i];

        XMVECTOR vStart = m_DebugSkeleton[1].SkeletonData[m_iCurrentSkeletonIndex].SkeletonPositions[StartIndex];
        XMVECTOR vEnd = m_DebugSkeleton[1].SkeletonData[m_iCurrentSkeletonIndex].SkeletonPositions[EndIndex];

        // Select the color based on tracking state.
        DWORD Color = 0xFF00FF00;
        switch( m_DebugSkeleton[1].SkeletonData[m_iCurrentSkeletonIndex].eSkeletonPositionTrackingState[EndIndex] )
        {
        case NUI_SKELETON_POSITION_INFERRED:
            Color = 0xFFFF0000;
            break;
        case NUI_SKELETON_POSITION_NOT_TRACKED:
            continue;
        }

        ATG::DebugDraw::DrawLineSegment( *(XMFLOAT3*)&vStart, *(XMFLOAT3*)&vEnd, Color );
    }

    if( g_FilterMaskSets[ m_dwFilterSetIndex ] & FILTER_MASK_BASEBALL_SWING )
    {
        XMVECTOR vStart = m_Bat[ 1 ].Start();
        XMVECTOR vEnd   = m_Bat[ 1 ].End();
        ATG::DebugDraw::DrawLineSegment( *(XMFLOAT3*)&vStart, *(XMFLOAT3*)&vEnd, 0xFF0000FF );
    }

}


//--------------------------------------------------------------------------------------
// Name: RenderOverlays()
// Desc: Show title, timers, and help.
//--------------------------------------------------------------------------------------
VOID Sample::RenderOverlays()
{
    PIXBeginNamedEvent( 0, __FUNCTION__ );
    {
        if( m_bDrawHelp )
        {
            m_Help.Render( &m_Font, g_HelpCallouts, NUM_HELP_CALLOUTS );
        }
        else
        {
            m_Font.Begin();

            m_Font.SetScaleFactors( 1.2f, 1.2f );
            m_Font.DrawText( 0, 0, 0xffffffff, L"Skeletal Post Processing" );

            m_Font.SetScaleFactors( 1.0f, 1.0f );
            m_Font.DrawText( 0, 0, 0xffffff00, m_Timer.GetFrameRate(), ATGFONT_RIGHT );

            if( m_FilterStack.IsEnabled() )
            {
                WCHAR strFilterNames[256] = L"Active Filters: ";
                const WCHAR* strComma = L"";
                DWORD FilterCount = m_FilterStack.GetFilterCount();
                for( DWORD i = 0; i < FilterCount; ++i )
                {
                    if( ( m_FilterStack.GetFilterMask(i) & m_dwFilterMask ) != 0 )
                    {
                        wcscat_s( strFilterNames, strComma );
                        strComma = L", ";
                        wcscat_s( strFilterNames, m_FilterStack.GetFilter(i)->GetName() );
                    }
                }
                m_Font.SetScaleFactors( 0.7f, 1.0f );
                m_Font.DrawText( 0, 30, 0xffffffff, strFilterNames );
                m_Font.SetScaleFactors( 1.0f, 1.0f );
            }

            if (m_bMatchProportions)
            {
                m_Font.DrawText( 0, 60, 0xFFFFFF00, L"Proportion Matching: ON" );
            }
            else
            {
                m_Font.DrawText( 0, 60, 0xFFFFFF00, L"Proportion Matching: OFF" );
            }

            RenderAvatarLabel( m_matWorld, L"Post Processed\nJoints" );
            RenderAvatarLabel( m_matWorldUnfiltered, L"Raw\nJoints" );

            m_Font.End();

            if( m_bShowFilterDebugInfo )
            {
                m_FilterStack.DebugRenderUI( m_pFilterDebugRenderer, m_dwFilterMask );
            }
        }
    }
    PIXEndNamedEvent();
}

//--------------------------------------------------------------------------------------
// Name: RenderAvatarLabel()
// Desc: Renders a centered text label above the origin of the given world matrix.
//--------------------------------------------------------------------------------------
VOID Sample::RenderAvatarLabel( const XMMATRIX matWorld, const WCHAR* strLabel )
{
    // save the safe rect font rectangle
    D3DRECT SafeWindow;
    m_Font.GetWindow( SafeWindow );

    D3DVIEWPORT9 Viewport;
    m_pd3dDevice->GetViewport( &Viewport );

    // set a full screen font rectangle that does not have safe rect boundaries
    m_Font.SetWindow( 0, 0, Viewport.Width, Viewport.Height );

    // apply a vertical offset from the avatar's origin in model space
    const XMVECTOR vLabelPosition = { 0, 1.9f, 0, 1 };

    // transform model space into homogemous screen space
    XMVECTOR vLabelPositionScreen = XMVector3TransformCoord( vLabelPosition, matWorld * m_matView * m_matProj );

    // apply viewport transformation to get screen pixel coordinates
    vLabelPositionScreen *= XMVectorSet( (FLOAT)Viewport.Width / 2.0f, (FLOAT)Viewport.Height / -2.0f, 0, 0 );
    vLabelPositionScreen += XMVectorSet( (FLOAT)Viewport.Width / 2.0f, (FLOAT)Viewport.Height / 2.0f, 0, 0 );

    // clip to screen
    if( vLabelPositionScreen.y > 0 && vLabelPositionScreen.y < (FLOAT)Viewport.Height && 
        vLabelPositionScreen.x > 0 && vLabelPositionScreen.x < (FLOAT)Viewport.Width )
    {
        // draw text
        m_Font.DrawText( vLabelPositionScreen.x, vLabelPositionScreen.y, 0xFFFFFFFF, strLabel, ATGFONT_CENTER_X );
    }

    // restore original font rectangle
    m_Font.SetWindow( SafeWindow );
}
