//--------------------------------------------------------------------------------------
// ZSprite.cpp
//
// Demonstrates how to create and render a z-sprite. The z-sprite is generated by
// rendering a model into an offscreen texture and an offscreen z-buffer. It is then
// rendered into the main scene to recreate the original image with correct z values.
//
// Z-sprites are useful to decouple the update rate of an object from the global frame
// rate. For instance, even if the framerate is 60Hz, objects can be updated at 30Hz to
// lighten the load. Note that this is really a tradeoff between the cost of rendering
// the object from scratch and the (hopefully, much cheaper) cost of rendering the
// z-sprite.
//
// Xbox Advanced Technology Group.
// Copyright (C) Microsoft Corporation. All rights reserved.
//--------------------------------------------------------------------------------------
#include <xtl.h>
#include <xgraphics.h>
#include <xboxmath.h>
#include <AtgApp.h>
#include <AtgFont.h>
#include <AtgHelp.h>
#include <AtgInput.h>
#include <AtgMesh.h>
#include <AtgResource.h>
#include <AtgUtil.h>


//--------------------------------------------------------------------------------------
// Callouts for labelling the gamepad on the help screen
//--------------------------------------------------------------------------------------
ATG::HELP_CALLOUT g_HelpCallouts[] =
{
    { ATG::HELP_LEFT_STICK,   ATG::HELP_PLACEMENT_2, L"Move\ncamera" },
    { ATG::HELP_START_BUTTON, ATG::HELP_PLACEMENT_1, L"Pause" },
    { ATG::HELP_BACK_BUTTON,  ATG::HELP_PLACEMENT_2, L"Display\nhelp" },
};
#define NUM_HELP_CALLOUTS (sizeof(g_HelpCallouts) / sizeof(g_HelpCallouts[0]))


//--------------------------------------------------------------------------------------
// Global constants
//--------------------------------------------------------------------------------------
const FLOAT NEAR_PLANE = 1.0f;
const FLOAT FAR_PLANE = 20.0f;


//--------------------------------------------------------------------------------------
// Name: class CZSprite
// Desc: Class to implement a zsprite
//--------------------------------------------------------------------------------------
class CZSprite
{
    LPDIRECT3DDEVICE9 m_pd3dDevice;
    DWORD m_dwWidth;
    DWORD m_dwHeight;

public:
    LPDIRECT3DSURFACE9 m_pZSpriteImageRT;
    LPDIRECT3DTEXTURE9 m_pZSpriteImageTexture;       // Texture ptr for image data

    LPDIRECT3DSURFACE9 m_pZSpriteDepthBuffer;
    LPDIRECT3DTEXTURE9 m_pZSpriteDepthBufferTexture; // Texture ptr for depth data

    LPDIRECT3DVERTEXDECLARATION9 m_pZSpriteVertexDecl;
    LPDIRECT3DVERTEXSHADER9 m_pZSpriteVertexShader;      // Vertex shader handle
    LPDIRECT3DPIXELSHADER9 m_pZSpritePixelShader;       // Pixel shader handle

    struct VERTEX
    {
        XMFLOAT4 pos;
        XMFLOAT2 tex;
    };
    VERTEX  m_ZSpriteVertices[4];         // Vertices for the quad

public:
    // Creation function
    HRESULT Create( LPDIRECT3DDEVICE9 pd3dDevice, DWORD dwWidth, DWORD dwHeight );
    HRESULT Render();
            CZSprite();
};


//--------------------------------------------------------------------------------------
// Name: class Sample
// Desc: Main class to run this application.
//--------------------------------------------------------------------------------------
class Sample : public ATG::Application
{
    ATG::Timer m_Timer;                 // Timer
    ATG::Font m_Font;                  // Font for text display
    ATG::Help m_Help;                  // Application help
    BOOL m_bDrawHelp;

    ATG::Mesh m_Mesh;                  // Mesh for teapot model
    XMFLOAT3 m_vViewAngle;            // View angle of camera
    FLOAT m_fPlaneZCoord;          // Attributes of an intersecting plane

    XMMATRIX m_matView;
    XMMATRIX m_matWorld;
    XMMATRIX m_matProj;

    CZSprite m_pZSprite;              // The z-sprite

    VOID    SetViewTransform();          // Sets the view transform
    HRESULT RenderToZSprite();           // Render a scene into the z-sprite

    LPDIRECT3DVERTEXDECLARATION9 m_pTeapotVertexDecl;
    LPDIRECT3DVERTEXSHADER9 m_pTeapotVertexShader;
    LPDIRECT3DPIXELSHADER9 m_pTeapotPixelShader;

    LPDIRECT3DVERTEXDECLARATION9 m_pQuadVertexDecl;
    LPDIRECT3DVERTEXSHADER9 m_pQuadVertexShader;
    LPDIRECT3DPIXELSHADER9 m_pQuadPixelShader;

public:
    HRESULT Initialize();                // Initialize the sample
    HRESULT Render();                    // Render the scene
    HRESULT Update();                 // Perform per-frame updates
};


//--------------------------------------------------------------------------------------
// Name: main()
// Desc: Entry point to the program.
//--------------------------------------------------------------------------------------
VOID __cdecl main()
{
    Sample atgApp;
    ATG::GetVideoSettings( &atgApp.m_d3dpp.BackBufferWidth, &atgApp.m_d3dpp.BackBufferHeight );
    atgApp.Run();
}


//--------------------------------------------------------------------------------------
// Name: Initialize()
// Desc: Performs initialization
//--------------------------------------------------------------------------------------
HRESULT Sample::Initialize()
{
    HRESULT hr;

    m_bDrawHelp = FALSE;

    // Create the font
    if( FAILED( m_Font.Create( "game:\\Media\\Fonts\\Arial_16.xpr" ) ) )
        return ATGAPPERR_MEDIANOTFOUND;

    // Confine text drawing to the title safe area
    m_Font.SetWindow( ATG::GetTitleSafeArea() );

    // Create the help
    if( FAILED( m_Help.Create( "game:\\Media\\Help\\Help.xpr" ) ) )
        return ATGAPPERR_MEDIANOTFOUND;

    // Load our geometry
    if( FAILED( hr = m_Mesh.Create( "game:\\Media\\Meshes\\Teapot.xbg" ) ) )
        return ATGAPPERR_MEDIANOTFOUND;

    // Create a full-screen zsprite
    if( FAILED( hr = m_pZSprite.Create( m_pd3dDevice, m_d3dpp.BackBufferWidth, m_d3dpp.BackBufferHeight ) ) )
    {
        ATG_PrintError( "Could not create z-sprite!\n" );
        return hr;
    }

    // Create shaders for rendering into the zsprite. These shaders output the color to
    // COLOR0 and the depth value to COLOR1.
    {
        static const D3DVERTEXELEMENT9 decl[] =
        {
            { 0, 0, D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
            D3DDECL_END()
        };
        m_pd3dDevice->CreateVertexDeclaration( decl, &m_pTeapotVertexDecl );

        if( FAILED( hr = ATG::LoadVertexShader( "game:\\Media\\Shaders\\TeapotVS.xvu", &m_pTeapotVertexShader ) ) )
        {
            ATG_PrintError( "Could not load vertex shader!\n" );
            return hr;
        }

        if( FAILED( hr = ATG::LoadPixelShader( "game:\\Media\\Shaders\\TeapotPS.xpu", &m_pTeapotPixelShader ) ) )
        {
            ATG_PrintError( "Could not load pixel shader!\n" );
            return hr;
        }
    }

    // Create shaders for rendering a simple, green quad
    {
        static const D3DVERTEXELEMENT9 decl[] =
        {
            { 0, 0, D3DDECLTYPE_FLOAT3, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
            D3DDECL_END()
        };
        m_pd3dDevice->CreateVertexDeclaration( decl, &m_pQuadVertexDecl );

        if( FAILED( hr = ATG::LoadVertexShader( "game:\\Media\\Shaders\\QuadVS.xvu", &m_pQuadVertexShader ) ) )
        {
            ATG_PrintError( "Could not load vertex shader!\n" );
            return hr;
        }

        if( FAILED( hr = ATG::LoadPixelShader( "game:\\Media\\Shaders\\QuadPS.xpu", &m_pQuadPixelShader ) ) )
        {
            ATG_PrintError( "Could not load pixel shader!\n" );
            return hr;
        }
    }

    // Set the view transform based on view angle
    m_vViewAngle = XMFLOAT3( 0.0f, 0.0f, 0.0f );
    SetViewTransform();

    // Render some objects to the z-sprite
    if( FAILED( RenderToZSprite() ) )
        return E_FAIL;

    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: SetViewTransform()
// Desc: Sets the view transform based on the view angle
//--------------------------------------------------------------------------------------
VOID Sample::SetViewTransform()
{
    XMVECTOR vCameraPos = XMVectorSet( 0.0f, 0.0f, -8.0f, 0.0f );
    XMVECTOR vLookAt = XMVectorSet( 0.0f, 0.0f, 0.0f, 0.0f );
    XMVECTOR vUp = XMVectorSet( 0.0f, 1.0f, 0.0f, 0.0f );

    // Determine the aspect ratio
    FLOAT fAspectRatio = ( FLOAT )m_d3dpp.BackBufferWidth / ( FLOAT )m_d3dpp.BackBufferHeight;

    // Create a rotation matrix for our view angle
    XMMATRIX matRotate = XMMatrixRotationRollPitchYaw( m_vViewAngle.x, m_vViewAngle.y, m_vViewAngle.z );

    // Transform our camera position (on the Z axis)
    XMVECTOR vEyePos = XMVector3TransformCoord( vCameraPos, matRotate );

    // Use that eye position and look at the origin
    m_matWorld = XMMatrixIdentity();
    m_matView = XMMatrixLookAtLH( vEyePos, vLookAt, vUp );
    m_matProj = XMMatrixPerspectiveFovLH( XM_PI / 3, fAspectRatio, NEAR_PLANE, FAR_PLANE );
}


//--------------------------------------------------------------------------------------
// Name: Update()
// Desc: Performs per-frame updates
//--------------------------------------------------------------------------------------
HRESULT Sample::Update()
{
    FLOAT fTime = ( FLOAT )m_Timer.GetAppTime();
    FLOAT fElapsedTime = ( FLOAT )m_Timer.GetElapsedTime();

    // Move the plane back and forth
    m_fPlaneZCoord = cosf( fTime ) * 3.0f;

    // Get the current gamepad status
    ATG::GAMEPAD* pGamepad = ATG::Input::GetMergedInput();

    // Toggle help
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_BACK )
        m_bDrawHelp = !m_bDrawHelp;

    // Let the user pause the animation
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_START )
    {
        static BOOL bPaused = FALSE;
        bPaused = !bPaused;

        if( bPaused )   m_Timer.Stop();
        else
            m_Timer.Start();
    }

    // Move the camera based off the gamepad
    if( pGamepad->fX1 != 0.0f || pGamepad->fY1 != 0.0f )
    {
        FLOAT fX1 = pGamepad->fX1;
        FLOAT fY1 = pGamepad->fY1;

        m_vViewAngle.y -= fX1 * 1.0f * fElapsedTime;
        if( m_vViewAngle.y > XM_PI * 2 ) m_vViewAngle.y -= XM_PI * 2;
        else if( m_vViewAngle.y < 0.0f )  m_vViewAngle.y += XM_PI * 2;

        m_vViewAngle.x += fY1 * 1.0f * fElapsedTime;
        if( m_vViewAngle.x > +1.0f )      m_vViewAngle.x = +1.0f;
        else if( m_vViewAngle.x < -1.0f ) m_vViewAngle.x = -1.0f;

        SetViewTransform();

        // If the camera moved, we need to re-render to the Z-sprite.
        // Note: we don't want to do this every frame, as that would defeat
        // the point of using z-sprites. A sophisticated app might use an
        // error metric to determine re-render conditions
        RenderToZSprite();
    }

    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: RenderToZSprite()
// Desc: Renders some stuff into the texture and the depth buffer for our z-sprite.
//--------------------------------------------------------------------------------------
HRESULT Sample::RenderToZSprite()
{
    // Save the old render target
    LPDIRECT3DSURFACE9 pBackBuffer;
    LPDIRECT3DSURFACE9 pDepthBuffer;
    m_pd3dDevice->GetBackBuffer( 0, 0, D3DBACKBUFFER_TYPE_MONO, &pBackBuffer );
    m_pd3dDevice->GetDepthStencilSurface( &pDepthBuffer );

    // Set the rendertarget to be our z-sprite surfaces
    m_pd3dDevice->SetRenderTarget( 0, m_pZSprite.m_pZSpriteImageRT );
    m_pd3dDevice->SetDepthStencilSurface( m_pZSprite.m_pZSpriteDepthBuffer );

    // Clear the render target
    // Note that zbuffer pixels may not actually get set to 1.0f during
    // the clear, due to possible hierarchial-z tricks during the clear.
    // Therefore, we will either (1) need to clear untouched pixels
    // ourselves by drawing a huge background quad at the end of the
    // scene, or (2) ensure that we use alpha-blending/alpha-testing to
    // make sure none of the untouched pixels are drawn when the z-sprite
    // is rendered to the main scene.
    m_pd3dDevice->Clear( 0, NULL, D3DCLEAR_TARGET | D3DCLEAR_ZBUFFER | D3DCLEAR_STENCIL,
                         0x00000000, 1.0f, 0L );

    m_pd3dDevice->SetRenderState( D3DRS_ZENABLE, TRUE );
    m_pd3dDevice->SetRenderState( D3DRS_ZWRITEENABLE, TRUE );
    m_pd3dDevice->SetRenderState( D3DRS_CULLMODE, D3DCULL_CCW );
    m_pd3dDevice->SetRenderState( D3DRS_ALPHABLENDENABLE, FALSE );

    m_pd3dDevice->SetVertexDeclaration( m_pTeapotVertexDecl );
    m_pd3dDevice->SetVertexShader( m_pTeapotVertexShader );
    m_pd3dDevice->SetPixelShader( m_pTeapotPixelShader );

    XMFLOAT4 c30( 0.0f, 0.0f, -2.0f, 0.0f );
    XMFLOAT4 c31( 1.0f, 1.0f, 1.0f / ( FAR_PLANE - NEAR_PLANE ), 1.0f );
    m_pd3dDevice->SetVertexShaderConstantF( 30, ( FLOAT* )&c30, 1 );
    m_pd3dDevice->SetVertexShaderConstantF( 31, ( FLOAT* )&c31, 1 );

    // List of positions for our models
    static XMFLOAT3 vTeapotPositions[] =
    {
        XMFLOAT3( 1.0f, 0.0f, -2.0f ),
        XMFLOAT3( -1.0f, 0.0f, 0.0f ),
        XMFLOAT3( -2.0f, 0.0f, -1.5f ),
        XMFLOAT3( 3.0f, 0.0f, 2.0f ),
    };

    for( DWORD i = 0; i < 4; i++ )
    {
        XMFLOAT4 light_Diffuse;
        XMFLOAT3 light_Direction;
        light_Diffuse.x = ( i == 0 || i == 2 ) ? 1.0f : 0.0f;
        light_Diffuse.y = ( i == 1 || i == 2 ) ? 1.0f : 0.0f;
        light_Diffuse.z = ( i == 1 || i == 3 ) ? 1.0f : 0.0f;
        light_Diffuse.w = 1.0f;
        light_Direction = XMFLOAT3( -0.5f, -1.0f, 1.0f );

        // Render the object
        XMMATRIX matWorld = XMMatrixTranslation( vTeapotPositions[i].x,
                                                 vTeapotPositions[i].y,
                                                 vTeapotPositions[i].z );

        XMMATRIX matAll;
        matAll = XMMatrixMultiply( matWorld, m_matView );
        matAll = XMMatrixMultiply( matAll, m_matProj );
        matAll = XMMatrixTranspose( matAll );
        m_pd3dDevice->SetVertexShaderConstantF( 4, ( FLOAT* )&matAll, 4 );
        m_pd3dDevice->SetVertexShaderConstantF( 20, ( FLOAT* )&light_Direction, 1 );
        m_pd3dDevice->SetVertexShaderConstantF( 22, ( FLOAT* )&light_Diffuse, 1 );

        m_Mesh.Render();
    }

    // Resolve the frame buffer to the offscreen texture
    m_pd3dDevice->Resolve( D3DRESOLVE_RENDERTARGET0, NULL, m_pZSprite.m_pZSpriteImageTexture,
                           NULL, 0, 0, NULL, 0, 0, NULL );
    m_pd3dDevice->Resolve( D3DRESOLVE_DEPTHSTENCIL, NULL, m_pZSprite.m_pZSpriteDepthBufferTexture,
                           NULL, 0, 0, NULL, 0, 0, NULL );

    // Restore state
    m_pd3dDevice->SetPixelShader( NULL );
    m_pd3dDevice->SetVertexShader( NULL );
    m_pd3dDevice->SetRenderTarget( 0, pBackBuffer );
    m_pd3dDevice->SetRenderTarget( 1, NULL );
    m_pd3dDevice->SetDepthStencilSurface( pDepthBuffer );
    pBackBuffer->Release();
    pDepthBuffer->Release();

    // Since drawing z-sprites is fill-bound, use an optimization to make the z-sprite
    // to be just big enough to hold the rendered image. Here we are using bounding
    // spheres, but a real app may do something more sophisticated.

    // Calculate screen extents for the geometry drawn
    // TODO: Final HW may provide a way to query screen extents.
    FLOAT xmin = +1.0f, xmax = -1.0f;
    FLOAT ymin = +1.0f, ymax = -1.0f;

    static FLOAT fZNear = 2.0f;
    static FLOAT fTeapotRadius = 1.74f;

    for( DWORD i = 0; i < 4; i++ )
    {
        // Compute the screen space position of each object's bounding sphere
        XMVECTOR vPosView, vScreenPos;
        vPosView = XMVector3Transform( XMLoadFloat3( &vTeapotPositions[i] ), m_matView );
        vScreenPos = XMVector4Transform( vPosView, m_matProj );
        vScreenPos.x /= vScreenPos.w;
        vScreenPos.y /= vScreenPos.w;
        FLOAT fScreenRadius = fTeapotRadius * fZNear / vPosView.z;

        // Record min/max extents
        xmin = min( xmin, max( -1.0f, vScreenPos.x - fScreenRadius ) );
        xmax = max( xmax, min( +1.0f, vScreenPos.x + fScreenRadius ) );
        ymin = min( ymin, max( -1.0f, vScreenPos.y - fScreenRadius ) );
        ymax = max( ymax, min( +1.0f, vScreenPos.y + fScreenRadius ) );
    }

    // Setup the z-sprite quad to use the smallest rect possible
    FLOAT sx1 = xmin - 0.5f / m_d3dpp.BackBufferWidth;
    FLOAT sx2 = xmax - 0.5f / m_d3dpp.BackBufferWidth;
    FLOAT sy1 = ymin - 0.5f / m_d3dpp.BackBufferHeight;
    FLOAT sy2 = ymax - 0.5f / m_d3dpp.BackBufferHeight;

    m_pZSprite.m_ZSpriteVertices[0].pos = XMFLOAT4( sx1, sy1, 0.0f, 1.0f );
    m_pZSprite.m_ZSpriteVertices[1].pos = XMFLOAT4( sx2, sy1, 0.0f, 1.0f );
    m_pZSprite.m_ZSpriteVertices[2].pos = XMFLOAT4( sx2, sy2, 0.0f, 1.0f );
    m_pZSprite.m_ZSpriteVertices[3].pos = XMFLOAT4( sx1, sy2, 0.0f, 1.0f );
    m_pZSprite.m_ZSpriteVertices[0].tex = XMFLOAT2( ( 1 + xmin ) / 2, ( 1 - ymin ) / 2 );
    m_pZSprite.m_ZSpriteVertices[1].tex = XMFLOAT2( ( 1 + xmax ) / 2, ( 1 - ymin ) / 2 );
    m_pZSprite.m_ZSpriteVertices[2].tex = XMFLOAT2( ( 1 + xmax ) / 2, ( 1 - ymax ) / 2 );
    m_pZSprite.m_ZSpriteVertices[3].tex = XMFLOAT2( ( 1 + xmin ) / 2, ( 1 - ymax ) / 2 );

    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: Render()
// Desc: Sets up render states, clears the viewport, and renders the scene.
//--------------------------------------------------------------------------------------
HRESULT Sample::Render()
{
    // Clear the viewport
    m_pd3dDevice->Clear( 0L, NULL, D3DCLEAR_TARGET | D3DCLEAR_ZBUFFER | D3DCLEAR_STENCIL,
                         0xff404080, 1.0f, 0L );

    // Set our render states
    m_pd3dDevice->SetRenderState( D3DRS_ZENABLE, TRUE );

    // Draw a plane. Note that the z-sprite will intersect correctly with the
    // plane regardless of whether we draw the plane first, or the z-sprite.
    {
        m_pd3dDevice->SetRenderState( D3DRS_CULLMODE, D3DCULL_NONE );
        m_pd3dDevice->SetRenderState( D3DRS_ALPHABLENDENABLE, FALSE );

        FLOAT v[4][3] =
        {
            { -5.0f,-1.0f, m_fPlaneZCoord },
            {  5.0f,-1.0f, m_fPlaneZCoord },
            {  5.0f, 1.0f, m_fPlaneZCoord },
            { -5.0f, 1.0f, m_fPlaneZCoord },
        };

        XMMATRIX matAll;
        matAll = XMMatrixMultiply( m_matView, m_matProj );
        matAll = XMMatrixTranspose( matAll );
        m_pd3dDevice->SetVertexShaderConstantF( 4, ( FLOAT* )&matAll, 4 );
        m_pd3dDevice->SetVertexDeclaration( m_pQuadVertexDecl );
        m_pd3dDevice->SetVertexShader( m_pQuadVertexShader );
        m_pd3dDevice->SetPixelShader( m_pQuadPixelShader );

        m_pd3dDevice->DrawPrimitiveUP( D3DPT_QUADLIST, 1, v, sizeof( v[0] ) );
    }

    // Render the zsprite
    m_pZSprite.Render();

    // Show title, frame rate, and help
    m_Timer.MarkFrame();
    if( m_bDrawHelp )
    {
        m_Help.Render( &m_Font, g_HelpCallouts, NUM_HELP_CALLOUTS );
    }
    else
    {
        m_Font.Begin();
        m_Font.SetScaleFactors( 1.2f, 1.2f );
        m_Font.DrawText( 0, 0, 0xffffffff, L"ZSprite" );
        m_Font.SetScaleFactors( 1.0f, 1.0f );
        m_Font.DrawText( 0, 0, 0xffffff00, m_Timer.GetFrameRate(), ATGFONT_RIGHT );
        m_Font.End();
    }

    // Present the scene
    m_pd3dDevice->Present( NULL, NULL, NULL, NULL );

    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: CZSprite()
// Desc: Constructor
//--------------------------------------------------------------------------------------
CZSprite::CZSprite()
{
    m_pZSpriteImageRT = NULL;
    m_pZSpriteImageTexture = NULL;
    m_pZSpriteDepthBuffer = NULL;
    m_pZSpriteDepthBufferTexture = NULL;

    m_pZSpriteVertexShader = NULL;
    m_pZSpritePixelShader = NULL;
}


//--------------------------------------------------------------------------------------
// Name: CreateZSprite()
// Desc: Performs initialization
//--------------------------------------------------------------------------------------
HRESULT CZSprite::Create( LPDIRECT3DDEVICE9 pd3dDevice, DWORD dwWidth, DWORD dwHeight )
{
    HRESULT hr;

    m_pd3dDevice = pd3dDevice;
    m_dwWidth = dwWidth;
    m_dwHeight = dwHeight;

    D3DSURFACE_PARAMETERS SurfaceParameters = { 0 };

    // Create a render target and a depth buffer for rendering to the z-sprite
    SurfaceParameters.Base = 0;
    if( FAILED( m_pd3dDevice->CreateRenderTarget( m_dwWidth, m_dwHeight, ( D3DFORMAT )MAKESRGBFMT( D3DFMT_A8R8G8B8 ),
                                                  D3DMULTISAMPLE_NONE, 0L, FALSE, &m_pZSpriteImageRT,
                                                  &SurfaceParameters ) ) )
        return E_FAIL;

    SurfaceParameters.Base = XGSurfaceSize( m_dwWidth, m_dwHeight, ( D3DFORMAT )MAKESRGBFMT( D3DFMT_A8R8G8B8 ), D3DMULTISAMPLE_NONE );
    if( FAILED( m_pd3dDevice->CreateDepthStencilSurface( m_dwWidth, m_dwHeight, D3DFMT_D24S8,
                                                         D3DMULTISAMPLE_NONE, 0L, 0L, &m_pZSpriteDepthBuffer,
                                                         &SurfaceParameters ) ) )
        return E_FAIL;

    // Create a color texture and a depth texture for the z-sprite
    if( FAILED( m_pd3dDevice->CreateTexture( m_dwWidth, m_dwHeight, 1, 0, ( D3DFORMAT )MAKESRGBFMT( D3DFMT_A8R8G8B8 ),
                                             D3DPOOL_DEFAULT, &m_pZSpriteImageTexture, NULL ) ) )
        return E_FAIL;

    if( FAILED( m_pd3dDevice->CreateTexture( m_dwWidth, m_dwHeight, 1, 0, D3DFMT_D24S8,
                                             D3DPOOL_DEFAULT, &m_pZSpriteDepthBufferTexture, NULL ) ) )
        return E_FAIL;

    // Create the z-sprite vertex shaders
    {
        static const D3DVERTEXELEMENT9 decl[] =
        {
            { 0,  0, D3DDECLTYPE_FLOAT4, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
            { 0, 16, D3DDECLTYPE_FLOAT2, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0 },
            D3DDECL_END()
        };
        if( FAILED( hr = m_pd3dDevice->CreateVertexDeclaration( decl, &m_pZSpriteVertexDecl ) ) )
            return hr;

        if( FAILED( hr = ATG::LoadVertexShader( "game:\\Media\\Shaders\\ZSpriteVS.xvu", &m_pZSpriteVertexShader ) ) )
        {
            ATG_PrintError( "Could not load vertex shader!\n" );
            return hr;
        }
    }

    // Create the z-sprite pixel shader
    if( FAILED( hr = ATG::LoadPixelShader( "game:\\Media\\Shaders\\ZSpritePS.xpu", &m_pZSpritePixelShader ) ) )
    {
        ATG_PrintError( "Could not load pixel shader!\n" );
        return hr;
    }

    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: Render()
// Desc: Renders the ZSprite
//--------------------------------------------------------------------------------------
HRESULT CZSprite::Render()
{
    // Set render states for the z-sprite
    m_pd3dDevice->SetRenderState( D3DRS_ZENABLE, TRUE );
    m_pd3dDevice->SetRenderState( D3DRS_ZWRITEENABLE, TRUE );
    m_pd3dDevice->SetRenderState( D3DRS_ALPHABLENDENABLE, TRUE );
    m_pd3dDevice->SetRenderState( D3DRS_SRCBLEND, D3DBLEND_SRCALPHA );
    m_pd3dDevice->SetRenderState( D3DRS_DESTBLEND, D3DBLEND_INVSRCALPHA );

    // Set textures for the z-sprite
    m_pd3dDevice->SetTexture( 0, m_pZSpriteImageTexture );
    m_pd3dDevice->SetTexture( 1, m_pZSpriteDepthBufferTexture );
    m_pd3dDevice->SetSamplerState( 0, D3DSAMP_ADDRESSU, D3DTADDRESS_CLAMP );
    m_pd3dDevice->SetSamplerState( 0, D3DSAMP_ADDRESSV, D3DTADDRESS_CLAMP );
    m_pd3dDevice->SetSamplerState( 1, D3DSAMP_ADDRESSU, D3DTADDRESS_CLAMP );
    m_pd3dDevice->SetSamplerState( 1, D3DSAMP_ADDRESSV, D3DTADDRESS_CLAMP );
    m_pd3dDevice->SetSamplerState( 0, D3DSAMP_MINFILTER, D3DTEXF_POINT );
    m_pd3dDevice->SetSamplerState( 0, D3DSAMP_MAGFILTER, D3DTEXF_POINT );
    m_pd3dDevice->SetSamplerState( 1, D3DSAMP_MINFILTER, D3DTEXF_POINT );
    m_pd3dDevice->SetSamplerState( 1, D3DSAMP_MAGFILTER, D3DTEXF_POINT );

    // Set the shaders for rendering the z-sprite
    m_pd3dDevice->SetVertexDeclaration( m_pZSpriteVertexDecl );
    m_pd3dDevice->SetVertexShader( m_pZSpriteVertexShader );
    m_pd3dDevice->SetPixelShader( m_pZSpritePixelShader );

    // Draw the z-sprite
    m_pd3dDevice->DrawPrimitiveUP( D3DPT_QUADLIST, 1, m_ZSpriteVertices,
                                   sizeof( m_ZSpriteVertices[0] ) );

    // Restore state
    m_pd3dDevice->SetVertexShader( NULL );
    m_pd3dDevice->SetPixelShader( NULL );
    m_pd3dDevice->SetTexture( 0, NULL );
    m_pd3dDevice->SetTexture( 1, NULL );

    return S_OK;
}

