//-----------------------------------------------------------------------------
// File: Messages.h
//
// Desc: Class and type definitions for the Messages used by the Video sample
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------

#pragma once

#include <vector>

const DWORD                         MAX_REMOTE_MACHINES = 3;                                      // Max remote machines
const DWORD                         MAX_REMOTE_PLAYERS = MAX_REMOTE_MACHINES * XUSER_MAX_COUNT;  // Max players

const DWORD                         NONCE_BYTES = 8;      // Larger means less chance of random matches
const DWORD                         MAX_GAME_NAME_LENGTH = 12;     // Includes null

// Sending out one network packet for each 20ms packet worth of voice would
// waste a lot of bandwidth in packet overhead.  Instead, we'll coalesce many
// voice packets together, and send at regular intervals
const FLOAT                         VOICE_PACKET_INTERVAL = 0.1f;   // 100ms = 10 times/s
const DWORD                         MAX_VOICE_PER_PACKET = 5 * 4;  // 5 packets per player = 100ms

// Maximum Size of Video Packets to be Created by XVID
const DWORD                         MAX_VIDEO_PACKET_SIZE = 1024;


//-----------------------------------------------------------------------------
// Message IDs
//
// A "host" is the player who started the game.
// A "client" is a potential player. A client is not currently playing a game.
// A "player" is anyone playing a game.
// Broadcast messages are sent via a UDP broadcast socket
// Direct    messages are sent via a UDP direct socket
// Reliable  messages are sent via a TCP socket (and relayed if needed)
//-----------------------------------------------------------------------------
enum
{                       // From     To      Type        Expected response
    //-----------------------------------------------------
    MSG_FIND_GAME,      // client   host    broadcast   MSG_GAME_FOUND
    MSG_GAME_FOUND,     // host     client  broadcast   <none>
    MSG_JOIN_GAME,      // client   host    reliable    MSG_JOIN_APPROVED/DENIED
    MSG_JOIN_APPROVED,  // host     client  reliable    <none>
    MSG_JOIN_DENIED,    // host     client  reliable    <none>
    MSG_MACHINE_JOINED, // host     player  reliable    <none>
    MSG_HEARTBEAT,      // player   player  direct      <none>
    MSG_VOICEINFO,      // player   player  reliable    <none>
    MSG_VIDEOINFO,      // player   player  reliable    <none>
    MSG_VOICEDATA,      // player   player  direct      <none>
    MSG_VIDEODATA,      // player   player  direct      <none>
};

//-----------------------------------------------------------------------------
// Message payloads
//-----------------------------------------------------------------------------
// Pack to minimize network traffic
#pragma pack( push )
#pragma pack( 1 )


//-----------------------------------------------------------------------------
// Local Player struct used by some messages
//-----------------------------------------------------------------------------
struct Player
{
    XUID xuid;                            // player'x XUID
    CHAR strGamertag[ XUSER_NAME_SIZE ];  // player's name
};

//-----------------------------------------------------------------------------
// Local Machine struct used by some messages
//-----------------------------------------------------------------------------
struct Machine
{
    XNADDR xnAddr;
    BYTE byNumPlayers;
    Player Players[ XUSER_MAX_COUNT ];
};


//-----------------------------------------------------------------------------
// Local Nonce struct used by some messages
//-----------------------------------------------------------------------------
struct Nonce
{
    // Used for client verification. The larger the number of NONCE_BYTES,
    // the less likely there is to be an accidental match between client & host
    BYTE byRandom[ NONCE_BYTES ];
};

//-----------------------------------------------------------------------------
// Broadcast by a client looking for available games
//-----------------------------------------------------------------------------
struct MsgFindGame
{
    Nonce nonce;    // Generated by client; used to verify host response
};

//-----------------------------------------------------------------------------
// Broadcast by a host in response to a MSG_FIND_GAME
//-----------------------------------------------------------------------------
struct MsgGameFound
{
    Nonce nonce;                          // used for client verification
    XNKID xnHostKeyID;                    // host key ID
    XNKEY xnHostKey;                      // host key
    XNADDR xnHostAddr;                     // host XNet address
    BYTE byNumPlayers;                   // number of players in game
    XCAMRESOLUTION Resolution;             // 
    WCHAR strGameName[ MAX_GAME_NAME_LENGTH ]; // game name
};

//-----------------------------------------------------------------------------
// Sent from a client to a host to join a game
//-----------------------------------------------------------------------------
struct MsgJoinGame
{
    Machine NewMachine;
};

//-----------------------------------------------------------------------------
// Sent from a host to a client in response to a MSG_JOIN_GAME
//-----------------------------------------------------------------------------
struct MsgJoinApproved
{
    Machine Host;
    BYTE byNumMachines;
    Machine Machines[ MAX_REMOTE_MACHINES ];
};

//-----------------------------------------------------------------------------
// Sent from a host to other players to notify them that a new machine has
// joined
//-----------------------------------------------------------------------------
struct MsgMachineJoined
{
    Machine NewMachine; // The latest machine to joining the game
};


enum VOICEINFO
{
    VOICEINFO_ADDMIC,
    VOICEINFO_REMOVEMIC,
    VOICEINFO_ADDREMOTEMUTE,
    VOICEINFO_REMOVEREMOTEMUTE,
};

enum VIDEOINFO
{
    VOICEINFO_ADDCAMERA,
    VOICEINFO_REMOVECAMERA,
};


// The VOICEINFO message is a little bit strange - since it
// must be sent reliably, it gets relayed by the host.  This
// means we need to identify the source and destination players
// inside the packet itself.  The only consistent player identifer
// we have in this sample is player name - ideally, this should
// be replaced with a smaller unique player identifier
struct MsgVoiceInfo
{
    VOICEINFO action;             // Action requested
    XUID xuidSrc;            // XUID of source player
    XUID xuidDest;           // XUID of destination player
};

struct MsgVideoInfo
{
    VIDEOINFO action;
    XNADDR xnaddrSrc;
    XNADDR xnaddrDest;
};


struct VoicePacket
{
    XUID xuidSrc;
    BYTE byData[XHV_VOICECHAT_MODE_PACKET_SIZE];
};

struct MsgVoiceData
{
    WORD wVoicePackets;
    VoicePacket VoicePackets[MAX_VOICE_PER_PACKET];
};

struct MsgVideoData
{
    WORD wVideoDataSize;
    BYTE byData[MAX_VIDEO_PACKET_SIZE];
};

#pragma pack( pop )



//-----------------------------------------------------------------------------
// Name: class Message
// Desc: Message object sent between players and hosts
//-----------------------------------------------------------------------------
class Message
{
    WORD m_cbGameData;
    BYTE m_byMessageId;

    union
    {
        MsgFindGame m_FindGame;
        MsgGameFound m_GameFound;
        MsgJoinGame m_JoinGame;
        MsgJoinApproved m_JoinApproved;
        MsgMachineJoined m_MachineJoined;
        MsgVoiceInfo m_VoiceInfo;
        MsgVideoInfo m_VideoInfo;
        MsgVideoData m_VideoData;
        MsgVoiceData m_VoiceData;
    };

public:

    explicit    Message( BYTE byMessageId = 0 ) : m_byMessageId( byMessageId )
    {
        m_cbGameData = ( WORD )GetEncryptedSize();
    }
                ~Message()
                {
                }

    BYTE        GetId() const
    {
        return m_byMessageId;
    }
    INT         GetMaxSize() const
    {
        return sizeof( *this );
    }

    MsgFindGame& GetFindGame()
    {
        return m_FindGame;
    }
    MsgGameFound& GetGameFound()
    {
        return m_GameFound;
    }
    MsgJoinGame& GetJoinGame()
    {
        return m_JoinGame;
    }
    MsgJoinApproved& GetJoinApproved()
    {
        return m_JoinApproved;
    }
    MsgMachineJoined& GetMachineJoined()
    {
        return m_MachineJoined;
    }
    MsgVoiceInfo& GetMsgVoiceInfo()
    {
        return m_VoiceInfo;
    }
    MsgVideoInfo& GetMsgVideoInfo()
    {
        return m_VideoInfo;
    }
    MsgVideoData& GetMsgVideoData()
    {
        return m_VideoData;
    }
    MsgVoiceData& GetMsgVoiceData()
    {
        return m_VoiceData;
    }

    INT         GetEncryptedSize() const
    {
        switch( m_byMessageId )
        {
            case MSG_FIND_GAME:
                return sizeof( BYTE ) + sizeof( MsgFindGame );
            case MSG_GAME_FOUND:
                return sizeof( BYTE ) + sizeof( MsgGameFound );
            case MSG_JOIN_GAME:
                return sizeof( BYTE ) + sizeof( MsgJoinGame );
            case MSG_JOIN_APPROVED:
                return sizeof( BYTE ) + sizeof( MsgJoinApproved );
            case MSG_JOIN_DENIED:
                return sizeof( BYTE );
            case MSG_MACHINE_JOINED:
                return sizeof( BYTE ) + sizeof( MsgMachineJoined );
            case MSG_HEARTBEAT:
                return sizeof( BYTE );
            case MSG_VOICEINFO:
                return sizeof( BYTE ) + sizeof( MsgVoiceInfo );
            case MSG_VIDEOINFO:
                return sizeof( BYTE ) + sizeof( MsgVideoInfo );
            case MSG_VOICEDATA:
                return sizeof( BYTE );
            case MSG_VIDEODATA:
                return sizeof( BYTE );
            default:
                assert( FALSE ); return 0;
        }
    }

    INT         GetUnEncryptedSize() const
    {
        switch( m_byMessageId )
        {
            case MSG_FIND_GAME:
                return 0;
            case MSG_GAME_FOUND:
                return 0;
            case MSG_JOIN_GAME:
                return 0;
            case MSG_JOIN_APPROVED:
                return 0;
            case MSG_JOIN_DENIED:
                return 0;
            case MSG_MACHINE_JOINED:
                return 0;
            case MSG_HEARTBEAT:
                return 0;
            case MSG_VOICEINFO:
                return 0;
            case MSG_VIDEOINFO:
                return 0;
            case MSG_VOICEDATA:
                return sizeof( WORD ) + m_VoiceData.wVoicePackets * sizeof( VoicePacket );
            case MSG_VIDEODATA:
                return sizeof( WORD ) + m_VideoData.wVideoDataSize;
            default:
                assert( FALSE ); return 0;
        }
    }

    // Total message size = Encrypted + UnEncrypted + 1 WORD for cbGameData
    INT         GetSize() const
    {
        return sizeof( WORD ) + GetEncryptedSize() + GetUnEncryptedSize();
    }
    static INT  GetHeaderSize()
    {
        return sizeof( WORD ) + sizeof( BYTE );
    }
};

//-----------------------------------------------------------------------------
// Name: class PendingMessage
// Desc: Used for parsing Messages out of a TCP stream.  Since fragments
//          of a given message could come in individually, they must be
//          buffered until complete
//-----------------------------------------------------------------------------
class PendingMessage
{
public:
            PendingMessage() : m_nBytesReceived( 0 )
            {
            }

    HRESULT Read( SOCKET sock );   // Read message from socket
    VOID    Reset()
    {
        m_nBytesReceived = 0;
    }

    Message m_msg;              // Buffer space for message
    INT m_nBytesReceived;   // # of bytes received in message
};


//-----------------------------------------------------------------------------
// Name: struct ClientSocket
// Desc: Keeps track of socket and associated data for reliable client
//          connections
//-----------------------------------------------------------------------------
struct ClientSocket
{
    SOCKET sock;       // Socket
    SOCKADDR_IN sa;         // Address of client
    BOOL bAccepted;  // Sent JoinAccepted message
    FLOAT fTimeout;   // Timer for timing out connections
    PendingMessage msgPending; // Pending message
};

typedef std::vector <ClientSocket>  SocketList;
