//--------------------------------------------------------------------------------------
// Compression.cpp
//
// This sample demonstrates how to use the XMemCompress and XMemDecompress APIs as well
// as native file compression on files generated by the xbcompress tool.
//
// Game Technology Group.
// Copyright (C) Microsoft Corporation. All rights reserved.
//--------------------------------------------------------------------------------------
#include <xtl.h>
#include <xbdm.h>
#include <xcompress.h>
#include <AtgInput.h>
#include "AtgConsole.h"
#include <cassert>

//--------------------------------------------------------------------------------------
// Globals
//--------------------------------------------------------------------------------------

// Console for output
ATG::Console    g_Console;

// Compression block size
const DWORD     g_dwCompressionBlock = 0x8000;

// Sample file names and size
const CHAR*     g_strCompressibleFile = "e:\\compressible.bin";
const CHAR*     g_strUncompressibleFile = "e:\\uncompressible.bin";

const CHAR*     g_strCompressibleDestFile = "e:\\compressible.lzx";
const CHAR*     g_strUncompressibleDestFile = "e:\\uncompressible.lzx";

const CHAR*     g_strTransparentCompressedFile = "game:\\media\\Compression.lzx";

const DWORD     g_dwFileSize = 0xFFFFF;

//--------------------------------------------------------------------------------------
// Name: CompressFile
// Desc: Compresses input file and save to the out file. The dwBlockSize parameter
//       specifies the size of a block to compress in bytes. dwBlockSize must be power
//       of two in size.
//--------------------------------------------------------------------------------------
BOOL CompressFile( const CHAR* strInFileName, const CHAR* strOutFileName, DWORD dwBlockSize )
{
    HRESULT hr;
    BOOL fSucceeded = TRUE;
    HANDLE hInFile = INVALID_HANDLE_VALUE;
    HANDLE hOutFile = INVALID_HANDLE_VALUE;
    BYTE* pBlockSrc = NULL;
    XCOMPRESS_FILE_HEADER_LZXNATIVE FileHeader = {0};
    XCOMPRESS_BLOCK_HEADER_LZXNATIVE* pBlockHeader = NULL;
    XMEMCOMPRESSION_CONTEXT CompressionContext = {0};
    BOOL fContextCreated = FALSE;

    hInFile = CreateFile( strInFileName, GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_FLAG_SEQUENTIAL_SCAN, NULL );
    if( hInFile == INVALID_HANDLE_VALUE )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Populate file header
    if( dwBlockSize < 32768 )
        dwBlockSize = 32768;
    FileHeader.Common.Identifier = XCOMPRESS_FILE_IDENTIFIER_LZXNATIVE;
    FileHeader.Common.Version = XCOMPRESS_SET_FILE_VERSION( XCOMPRESS_LZXNATIVE_VERSION_MAJOR,
                                                            XCOMPRESS_LZXNATIVE_VERSION_MINOR );
    FileHeader.CodecParams.WindowSize = dwBlockSize;
    FileHeader.CodecParams.CompressionPartitionSize = dwBlockSize;
    LARGE_INTEGER FileSize;
    GetFileSizeEx( hInFile, ( LARGE_INTEGER* )&FileSize );
    FileHeader.UncompressedSizeLow = FileSize.LowPart;
    FileHeader.UncompressedSizeHigh = FileSize.HighPart;
    FileHeader.UncompressedBlockSize = dwBlockSize;

    // Create compression context
    hr = XMemCreateCompressionContext( XMEMCODEC_LZX, &FileHeader.CodecParams,
                                       FileHeader.ContextFlags, &CompressionContext );
    if( FAILED( hr ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }
    fContextCreated = TRUE;

    // Create block header to be twice as big as the block size.
    // This ensures that if by chance, the compressed data is larger
    // then the source data, the buffer will not have to be reallocated.
    pBlockHeader = ( XCOMPRESS_BLOCK_HEADER_LZXNATIVE* )malloc( ( dwBlockSize * 2 ) + sizeof
                                                                ( XCOMPRESS_BLOCK_HEADER_LZXNATIVE ) );
    if( pBlockHeader == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Create source buffer
    pBlockSrc = ( BYTE* )malloc( dwBlockSize );
    if( pBlockSrc == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Create output compressed file
    hOutFile = CreateFile( strOutFileName, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_FLAG_SEQUENTIAL_SCAN, NULL );
    if( hOutFile == INVALID_HANDLE_VALUE )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Start compressing the file. The file header will be written when
    // compression is completed.
    LARGE_INTEGER DistanceToMove;
    DistanceToMove.QuadPart = ( LONGLONG )sizeof( XCOMPRESS_FILE_HEADER_LZXNATIVE );
    SetFilePointerEx( hOutFile, DistanceToMove, NULL, FILE_BEGIN );

    DWORD dwUncompressedBlockSize = 0;
    DWORD dwBytesWritten;
    ULARGE_INTEGER uBytesRemaining;
    ULARGE_INTEGER uCompressedSize;

    uCompressedSize.QuadPart = 0;

    for( uBytesRemaining.LowPart = FileHeader.UncompressedSizeLow,
         uBytesRemaining.HighPart = FileHeader.UncompressedSizeHigh;
         uBytesRemaining.QuadPart > 0ull;
         uBytesRemaining.QuadPart -= dwUncompressedBlockSize )
    {
        dwUncompressedBlockSize = ( DWORD )min( uBytesRemaining.QuadPart,
                                                ( ULONGLONG )FileHeader.UncompressedBlockSize );

        // Read uncompressed block
        DWORD dwBytesRead;
        if( !ReadFile( hInFile, pBlockSrc, dwUncompressedBlockSize, &dwBytesRead, NULL ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        // Compress block
        DWORD dwCompressedSize = dwBlockSize * 2;
        hr = XMemCompress( CompressionContext, pBlockHeader + 1, &dwCompressedSize, pBlockSrc,
                           dwUncompressedBlockSize );
        if( FAILED( hr ) || hr == XMCDERR_MOREDATA )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        // Update file header
        if( dwCompressedSize > FileHeader.CompressedBlockSizeMax )
            FileHeader.CompressedBlockSizeMax = dwCompressedSize;

        uCompressedSize.QuadPart += dwCompressedSize;

        // Write compressed block
        pBlockHeader->CompressedBlockSize = dwCompressedSize;

        if( !WriteFile( hOutFile, pBlockHeader, dwCompressedSize + sizeof( XCOMPRESS_BLOCK_HEADER_LZXNATIVE ),
                        &dwBytesWritten, NULL ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }
    }

    // Update file header

    FileHeader.CompressedSizeLow = uCompressedSize.LowPart;
    FileHeader.CompressedSizeHigh = uCompressedSize.HighPart;

    // Write the file header
    DistanceToMove.QuadPart = ( LONGLONG )0;
    SetFilePointerEx( hOutFile, DistanceToMove, NULL, FILE_BEGIN );
    if( !WriteFile( hOutFile, &FileHeader, sizeof( XCOMPRESS_FILE_HEADER_LZXNATIVE ), &dwBytesWritten, NULL ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }


BAIL_ON_FAILURE:
    if( pBlockHeader )
        free( pBlockHeader );

    if( pBlockSrc )
        free( pBlockSrc );

    if( fContextCreated )
        XMemDestroyCompressionContext( CompressionContext );

    if( hInFile != INVALID_HANDLE_VALUE )
        CloseHandle( hInFile );

    if( hOutFile != INVALID_HANDLE_VALUE )
    {
        CloseHandle( hOutFile );
        if( !fSucceeded )
            DeleteFile( strOutFileName );
    }
    return fSucceeded;
}


//--------------------------------------------------------------------------------------
// Name: DeompressFile
// Desc: Decompresses an already compressed file. The file is originally compressed with 
//       CompressFile or the xbcompress tool.
//--------------------------------------------------------------------------------------
BOOL DecompressFile( const CHAR* strInFileName, const CHAR* strOutFileName )
{
    DWORD dwBytesRead;
    HRESULT hr;
    BOOL fSucceeded = TRUE;
    HANDLE hInFile = INVALID_HANDLE_VALUE;
    HANDLE hOutFile = INVALID_HANDLE_VALUE;
    BYTE* pBlockDest = NULL;
    XCOMPRESS_BLOCK_HEADER_LZXNATIVE* pBlockHeader = NULL;
    XCOMPRESS_FILE_HEADER_LZXNATIVE FileHeader = {0};
    XMEMDECOMPRESSION_CONTEXT DecompressionContext = {0};
    BOOL fContextCreated = FALSE;

    hInFile = CreateFile( strInFileName, GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_FLAG_SEQUENTIAL_SCAN, NULL );
    if( hInFile == INVALID_HANDLE_VALUE )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Read and check file identifier
    if( !ReadFile( hInFile, &FileHeader.Common.Identifier, sizeof( DWORD ), &dwBytesRead, NULL ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    if( FileHeader.Common.Identifier != XCOMPRESS_FILE_IDENTIFIER_LZXNATIVE )
    {
        // Incorrect file identifier
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Read and check compression algorithm version
    if( !ReadFile( hInFile, ( BYTE* )&FileHeader + sizeof( DWORD ), sizeof( XCOMPRESS_FILE_HEADER ) - sizeof
                   ( DWORD ), &dwBytesRead, NULL ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    if( ( XCOMPRESS_GET_FILE_VERSION_MAJOR( FileHeader.Common.Version ) != XCOMPRESS_LZXNATIVE_VERSION_MAJOR ) ||
        ( XCOMPRESS_GET_FILE_VERSION_MINOR( FileHeader.Common.Version ) != XCOMPRESS_LZXNATIVE_VERSION_MINOR ) )
    {
        // Version mismatch between xbcompress and runtime.
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    if( !ReadFile( hInFile, ( BYTE* )&FileHeader + sizeof( XCOMPRESS_FILE_HEADER ), sizeof
                   ( XCOMPRESS_FILE_HEADER_LZXNATIVE ) - sizeof( XCOMPRESS_FILE_HEADER ), &dwBytesRead, NULL ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Create decompression context
    hr = XMemCreateDecompressionContext( XMEMCODEC_LZX, &FileHeader.CodecParams,
                                         FileHeader.ContextFlags, &DecompressionContext );
    if( FAILED( hr ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }
    fContextCreated = TRUE;

    pBlockHeader = ( XCOMPRESS_BLOCK_HEADER_LZXNATIVE* )malloc( FileHeader.CompressedBlockSizeMax + sizeof
                                                                ( XCOMPRESS_BLOCK_HEADER_LZXNATIVE ) );
    if( pBlockHeader == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    pBlockDest = ( BYTE* )malloc( FileHeader.UncompressedBlockSize );
    if( pBlockDest == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Create output decompressed file
    hOutFile = CreateFile( strOutFileName, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_FLAG_SEQUENTIAL_SCAN, NULL );
    if( hOutFile == INVALID_HANDLE_VALUE )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    DWORD dwUncompressedBlockSize = 0;
    ULARGE_INTEGER uBytesRemaining;

    for( uBytesRemaining.LowPart = FileHeader.UncompressedSizeLow,
         uBytesRemaining.HighPart = FileHeader.UncompressedSizeHigh;
         uBytesRemaining.QuadPart > 0ull;
         uBytesRemaining.QuadPart -= dwUncompressedBlockSize )
    {
        dwUncompressedBlockSize = ( DWORD )min( uBytesRemaining.QuadPart,
                                                ( ULONGLONG )FileHeader.UncompressedBlockSize );

        // Read compressed block header
        if( !ReadFile( hInFile, pBlockHeader, sizeof( XCOMPRESS_BLOCK_HEADER_LZXNATIVE ), &dwBytesRead, NULL ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        // Read compressed block
        if( !ReadFile( hInFile, pBlockHeader->pCompressedData, pBlockHeader->CompressedBlockSize, &dwBytesRead,
                       NULL ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        // Decompress block
        hr = XMemDecompress( DecompressionContext, pBlockDest, &dwUncompressedBlockSize, pBlockHeader->pCompressedData,
                             pBlockHeader->CompressedBlockSize );
        if( FAILED( hr ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        DWORD dwBytesWritten;
        if( !WriteFile( hOutFile, pBlockDest, dwUncompressedBlockSize, &dwBytesWritten, NULL ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }
    }

BAIL_ON_FAILURE:
    if( pBlockDest )
        free( pBlockDest );

    if( pBlockHeader )
        free( pBlockHeader );

    if( fContextCreated )
        XMemDestroyDecompressionContext( DecompressionContext );

    if( hInFile != INVALID_HANDLE_VALUE )
        CloseHandle( hInFile );

    if( hOutFile != INVALID_HANDLE_VALUE )
    {
        CloseHandle( hOutFile );
        if( !fSucceeded )
            DeleteFile( strOutFileName );
    }

    return fSucceeded;
}


//--------------------------------------------------------------------------------------
// Name: DeompressFileToMemory
// Desc: Decompresses an already compressed file to memory. The file is originally 
//       compressed with CompressFile or the xbcompress tool.
//--------------------------------------------------------------------------------------
BOOL DecompressFileToMemory( const CHAR* strFileName, VOID** pDestination, DWORD* pdwDestSize )
{
    DWORD dwBytesRead;
    HRESULT hr;
    BOOL fSucceeded = TRUE;
    HANDLE hFile = INVALID_HANDLE_VALUE;
    BYTE* pFileDest = NULL;
    XCOMPRESS_BLOCK_HEADER_LZXNATIVE* pBlockHeader = NULL;
    XCOMPRESS_FILE_HEADER_LZXNATIVE FileHeader = {0};
    XMEMDECOMPRESSION_CONTEXT DecompressionContext = {0};
    BOOL fContextCreated = FALSE;


    hFile = CreateFile( strFileName, GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_FLAG_SEQUENTIAL_SCAN, NULL );
    if( hFile == INVALID_HANDLE_VALUE )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Read and check file identifier
    if( !ReadFile( hFile, &FileHeader.Common.Identifier, sizeof( DWORD ), &dwBytesRead, NULL ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    if( FileHeader.Common.Identifier != XCOMPRESS_FILE_IDENTIFIER_LZXNATIVE )
    {
        // Incorrect file identifier
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Read and check compression algorithm version
    if( !ReadFile( hFile, ( BYTE* )&FileHeader + sizeof( DWORD ), sizeof( XCOMPRESS_FILE_HEADER ) - sizeof
                   ( DWORD ), &dwBytesRead, NULL ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    if( ( XCOMPRESS_GET_FILE_VERSION_MAJOR( FileHeader.Common.Version ) != XCOMPRESS_LZXNATIVE_VERSION_MAJOR ) ||
        ( XCOMPRESS_GET_FILE_VERSION_MINOR( FileHeader.Common.Version ) != XCOMPRESS_LZXNATIVE_VERSION_MINOR ) )
    {
        // Version mismatch between xbcompress and runtime.
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    if( !ReadFile( hFile, ( BYTE* )&FileHeader + sizeof( XCOMPRESS_FILE_HEADER ), sizeof
                   ( XCOMPRESS_FILE_HEADER_LZXNATIVE ) - sizeof( XCOMPRESS_FILE_HEADER ), &dwBytesRead, NULL ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Check the file size does not exceed 4 GB
    if( FileHeader.UncompressedSizeHigh != 0 )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Create decompression context
    hr = XMemCreateDecompressionContext( XMEMCODEC_LZX, &FileHeader.CodecParams,
                                         FileHeader.ContextFlags, &DecompressionContext );
    if( FAILED( hr ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }
    fContextCreated = TRUE;

    // Allocate a memory buffer to hold the full uncompressed file
    pFileDest = ( BYTE* )malloc( FileHeader.UncompressedSizeLow );
    if( pFileDest == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    pBlockHeader = ( XCOMPRESS_BLOCK_HEADER_LZXNATIVE* )malloc( FileHeader.CompressedBlockSizeMax + sizeof
                                                                ( XCOMPRESS_BLOCK_HEADER_LZXNATIVE ) );
    if( pBlockHeader == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    BYTE* pBlockDest = pFileDest;
    DWORD dwUncompressedBlockSize = 0;

    for( DWORD dwBytesRemaining = FileHeader.UncompressedSizeLow; dwBytesRemaining > 0;
         dwBytesRemaining -= dwUncompressedBlockSize )
    {
        dwUncompressedBlockSize = min( dwBytesRemaining, FileHeader.UncompressedBlockSize );

        // Read compressed block header
        if( !ReadFile( hFile, pBlockHeader, sizeof( XCOMPRESS_BLOCK_HEADER_LZXNATIVE ), &dwBytesRead, NULL ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        // Read compressed block
        if( !ReadFile( hFile, pBlockHeader->pCompressedData, pBlockHeader->CompressedBlockSize, &dwBytesRead, NULL ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        // Decompress block
        hr = XMemDecompress( DecompressionContext, pBlockDest, &dwUncompressedBlockSize, pBlockHeader->pCompressedData,
                             pBlockHeader->CompressedBlockSize );
        if( FAILED( hr ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        pBlockDest += dwUncompressedBlockSize;
    }

    *pDestination = pFileDest;
    pFileDest = NULL;       // Prevent pointer from freeing
    *pdwDestSize = FileHeader.UncompressedSizeLow;


BAIL_ON_FAILURE:
    if( pFileDest )
        free( pFileDest );

    if( pBlockHeader )
        free( pBlockHeader );

    if( fContextCreated )
        XMemDestroyDecompressionContext( DecompressionContext );

    if( hFile != INVALID_HANDLE_VALUE )
        CloseHandle( hFile );

    return fSucceeded;
}


//--------------------------------------------------------------------------------------
// Name: CompressFileStreaming
// Desc: Compresses input file and save to the out file using streaming compression API. 
//       The dwBlockSize parameter specifies the size of a block to compress in bytes. 
//       dwBlockSize must be power of two in size.
//--------------------------------------------------------------------------------------
BOOL CompressFileStreaming( const CHAR* strInFileName, const CHAR* strOutFileName, DWORD dwBlockSize )
{
    HRESULT hr;
    BOOL fSucceeded = TRUE;
    HANDLE hInFile = INVALID_HANDLE_VALUE;
    HANDLE hOutFile = INVALID_HANDLE_VALUE;
    XMEMCOMPRESSION_CONTEXT CompressionContext = {0};
    VOID* pBlockDst = NULL;
    VOID* pBlockSrc = NULL;
    BOOL fContextCreated = FALSE;

    hInFile = CreateFile( strInFileName, GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_FLAG_SEQUENTIAL_SCAN, NULL );
    if( hInFile == INVALID_HANDLE_VALUE )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    LARGE_INTEGER FileSize;
    GetFileSizeEx( hInFile, ( LARGE_INTEGER* )&FileSize );

    XMEMCODEC_PARAMETERS_LZX CodecParams;
    CodecParams.Flags = 0;
    CodecParams.WindowSize = dwBlockSize;
    CodecParams.CompressionPartitionSize = dwBlockSize;

    // Create compression context
    hr = XMemCreateCompressionContext( XMEMCODEC_LZX, &CodecParams, XMEMCOMPRESS_STREAM, &CompressionContext );
    if( FAILED( hr ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }
    fContextCreated = TRUE;

    // Create a destination block buffer to be twice as big as the block size.
    // This ensures that if by chance, the compressed data is larger
    // then the source data, the buffer will not have to be reallocated.
    pBlockDst = malloc( dwBlockSize * 2 );
    if( pBlockDst == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Create source buffer
    pBlockSrc = ( BYTE* )malloc( dwBlockSize );
    if( pBlockSrc == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Create output compressed file
    hOutFile = CreateFile( strOutFileName, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_FLAG_SEQUENTIAL_SCAN, NULL );
    if( hOutFile == INVALID_HANDLE_VALUE )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    DWORD dwUncompressedBlockSize = 0;
    for(; FileSize.QuadPart >= 0ll; FileSize.QuadPart -= dwUncompressedBlockSize )
    {
        dwUncompressedBlockSize = ( DWORD )min( FileSize.QuadPart, ( LONGLONG )dwBlockSize );

        // Read uncompressed block
        DWORD dwBytesRead = 0;
        if( dwUncompressedBlockSize > 0 )
        {
            if( !ReadFile( hInFile, pBlockSrc, dwUncompressedBlockSize, &dwBytesRead, NULL ) )
            {
                fSucceeded = FALSE;
                goto BAIL_ON_FAILURE;
            }
        }

        // Compress block
        DWORD dwDstSize = dwBlockSize * 2;
        DWORD dwSrcSize = dwBytesRead;
        hr = XMemCompressStream( CompressionContext, pBlockDst, &dwDstSize, pBlockSrc, &dwSrcSize );
        if( FAILED( hr ) || hr == XMCDERR_MOREDATA )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        if( dwDstSize > 0 )
        {
            DWORD dwBytesWritten;
            if( !WriteFile( hOutFile, pBlockDst, dwDstSize, &dwBytesWritten, NULL ) )
            {
                fSucceeded = FALSE;
                goto BAIL_ON_FAILURE;
            }
        }

        if( dwBytesRead == 0 )
            break;
    }

BAIL_ON_FAILURE:
    if( pBlockDst )
        free( pBlockDst );

    if( pBlockSrc )
        free( pBlockSrc );

    if( fContextCreated )
        XMemDestroyCompressionContext( CompressionContext );

    if( hInFile != INVALID_HANDLE_VALUE )
        CloseHandle( hInFile );

    if( hOutFile != INVALID_HANDLE_VALUE )
    {
        CloseHandle( hOutFile );
        if( !fSucceeded )
            DeleteFile( strOutFileName );
    }

    return fSucceeded;
}

#pragma warning(push)
// Disable spurious /analyze warning: 
// Invalid data: accessing 'argument 2', the readable size is 'dwBlockSize' bytes...
#pragma warning(disable:6385)

//--------------------------------------------------------------------------------------
// Name: DeompressFileStreaming
// Desc: Decompresses an already compressed file using the streaming compression API.
//--------------------------------------------------------------------------------------
BOOL DecompressFileStreaming( const CHAR* strInFileName, const CHAR* strOutFileName, DWORD dwBlockSize )
{
    HRESULT hr;
    BOOL fSucceeded = TRUE;
    HANDLE hInFile = INVALID_HANDLE_VALUE;
    HANDLE hOutFile = INVALID_HANDLE_VALUE;
    BYTE* pBlockDst = NULL;
    BYTE* pBlockSrc = NULL;
    XMEMDECOMPRESSION_CONTEXT DecompressionContext = {0};
    BOOL fContextCreated = FALSE;

    hInFile = CreateFile( strInFileName, GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_FLAG_SEQUENTIAL_SCAN, NULL );
    if( hInFile == INVALID_HANDLE_VALUE )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    LARGE_INTEGER FileSize;
    GetFileSizeEx( hInFile, ( LARGE_INTEGER* )&FileSize );

    XMEMCODEC_PARAMETERS_LZX CodecParams;
    CodecParams.Flags = 0;
    CodecParams.WindowSize = dwBlockSize;
    CodecParams.CompressionPartitionSize = dwBlockSize;

    // Create decompression context
    hr = XMemCreateDecompressionContext( XMEMCODEC_LZX, &CodecParams, XMEMCOMPRESS_STREAM, &DecompressionContext );
    if( FAILED( hr ) )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }
    fContextCreated = TRUE;

    pBlockSrc = ( BYTE* )malloc( dwBlockSize );
    if( pBlockSrc == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    pBlockDst = ( BYTE* )malloc( dwBlockSize );
    if( pBlockDst == NULL )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    // Create output decompressed file
    hOutFile = CreateFile( strOutFileName, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_FLAG_SEQUENTIAL_SCAN, NULL );
    if( hOutFile == INVALID_HANDLE_VALUE )
    {
        fSucceeded = FALSE;
        goto BAIL_ON_FAILURE;
    }

    DWORD dwCompressedBlockSize = 0;
    for(; FileSize.QuadPart > 0ll; FileSize.QuadPart -= dwCompressedBlockSize )
    {
        dwCompressedBlockSize = ( DWORD )min( FileSize.QuadPart, ( LONGLONG )dwBlockSize );

        // Read compressed block
        DWORD dwBytesRead;
        if( !ReadFile( hInFile, pBlockSrc, dwCompressedBlockSize, &dwBytesRead, NULL ) )
        {
            fSucceeded = FALSE;
            goto BAIL_ON_FAILURE;
        }

        // Decompress block
        DWORD dwDecompressedBytes = 0;
        while( dwDecompressedBytes < dwBytesRead )
        {
            DWORD dwDstSize = dwBlockSize;
            DWORD dwSrcSize = dwBytesRead - dwDecompressedBytes;

            hr = XMemDecompressStream( DecompressionContext, pBlockDst, &dwDstSize,
                                       pBlockSrc + dwDecompressedBytes, &dwSrcSize );
            if( FAILED( hr ) || hr == XMCDERR_MOREDATA )
            {
                fSucceeded = FALSE;
                goto BAIL_ON_FAILURE;
            }

            dwDecompressedBytes += dwSrcSize;

            if( dwDstSize > 0 )
            {
                DWORD dwBytesWritten;
                if( !WriteFile( hOutFile, pBlockDst, dwDstSize, &dwBytesWritten, NULL ) )
                {
                    fSucceeded = FALSE;
                    goto BAIL_ON_FAILURE;
                }
            }
        }
    }

BAIL_ON_FAILURE:
    if( pBlockDst )
        free( pBlockDst );

    if( pBlockSrc )
        free( pBlockSrc );

    if( fContextCreated )
        XMemDestroyDecompressionContext( DecompressionContext );

    if( hInFile != INVALID_HANDLE_VALUE )
        CloseHandle( hInFile );

    if( hOutFile != INVALID_HANDLE_VALUE )
    {
        CloseHandle( hOutFile );
        if( !fSucceeded )
            DeleteFile( strOutFileName );
    }

    return fSucceeded;
}

#pragma warning(pop)

//--------------------------------------------------------------------------------------
// Name: CreateFiles
// Desc: Create test files to be compressed and uncompressed.
//--------------------------------------------------------------------------------------
BOOL CreateFiles()
{
    g_Console.Format( "Creating test files...\n" );

    // Create compressible file
    HANDLE hFile = CreateFile( g_strCompressibleFile, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_FLAG_SEQUENTIAL_SCAN,
                               NULL );
    if( hFile == INVALID_HANDLE_VALUE )
    {
        return FALSE;
    }

    BYTE bBuffer[1024];
    for( DWORD i = 0; i < g_dwFileSize; i += sizeof( bBuffer ) )
    {
        // Set all the bytes in the buffer the same for good compression
        memset( bBuffer, rand() % 0xFF, sizeof( bBuffer ) );

        DWORD dwWritten;
        if( !WriteFile( hFile, bBuffer, sizeof( bBuffer ), &dwWritten, NULL ) )
        {
            CloseHandle( hFile );
            return FALSE;
        }
    }

    CloseHandle( hFile );

    // Create uncompressible file

    hFile = CreateFile( g_strUncompressibleFile, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_FLAG_SEQUENTIAL_SCAN,
                        NULL );
    if( hFile == INVALID_HANDLE_VALUE )
    {
        return FALSE;
    }

    for( DWORD i = 0; i < g_dwFileSize; i += sizeof( bBuffer ) )
    {
        // Set the buffer to random values
        for( DWORD k = 0; k < sizeof( bBuffer ); k++ )
        {
            bBuffer[k] = ( BYTE )( rand() % 0xFF );
        }

        DWORD dwWritten;
        if( !WriteFile( hFile, bBuffer, sizeof( bBuffer ), &dwWritten, NULL ) )
        {
            CloseHandle( hFile );
            return FALSE;
        }
    }

    CloseHandle( hFile );

    g_Console.Format( "Test files were created successfully.\n" );

    return TRUE;
}


//--------------------------------------------------------------------------------------
// Name: GetFileSizeHelper
// Desc: Return the file size in bytes.
//--------------------------------------------------------------------------------------
DWORD GetFileSizeHelper( const CHAR* strFileName )
{
    HANDLE hFile = CreateFile( strFileName, GENERIC_READ, 0, NULL, OPEN_EXISTING, 0, NULL );
    if( hFile == INVALID_HANDLE_VALUE )
    {
        return 0;
    }

    LARGE_INTEGER FileSize;
    GetFileSizeEx( hFile, ( LARGE_INTEGER* )&FileSize );

    CloseHandle( hFile );

    return FileSize.LowPart;
}


//--------------------------------------------------------------------------------------
// Name: RunTest
// Desc: Run compression and decompression test on test files.
//--------------------------------------------------------------------------------------
VOID RunTest( const CHAR* strInputFile, const CHAR* strDestinationFile )
{
    __int64 PerfFrequency, StartTime, EndTime;

    QueryPerformanceFrequency( ( LARGE_INTEGER* )&PerfFrequency );

    g_Console.Format( "\nCompressing file <%s>...\n", strInputFile );

    QueryPerformanceCounter( ( LARGE_INTEGER* )&StartTime );
    if( !CompressFile( strInputFile, strDestinationFile, g_dwCompressionBlock ) )
    {
        g_Console.Format( "Error: Compression failed.\n" );
        return;
    }
    QueryPerformanceCounter( ( LARGE_INTEGER* )&EndTime );

    g_Console.Format( "Compression done. Time taken: %0.6f s. Compression: %0.2f%%.\n",
                      ( double )( EndTime - StartTime ) / ( double )PerfFrequency,
                      100.0 * ( ( double )g_dwFileSize - ( double )GetFileSizeHelper( strDestinationFile ) ) /
                      ( double )g_dwFileSize );

    g_Console.Format( "Decompressing file <%s>...\n", strDestinationFile );

    QueryPerformanceCounter( ( LARGE_INTEGER* )&StartTime );
    if( !DecompressFile( strDestinationFile, strInputFile ) )
    {
        g_Console.Format( "Error: Decompression failed.\n" );
        return;
    }
    QueryPerformanceCounter( ( LARGE_INTEGER* )&EndTime );

    g_Console.Format( "Decompression done. Time taken: %0.6f s.\n", ( double )( EndTime - StartTime ) / ( double )
                      PerfFrequency );


    QueryPerformanceFrequency( ( LARGE_INTEGER* )&PerfFrequency );

    g_Console.Format( "\nCompressing file (streaming) <%s>...\n", strInputFile );

    QueryPerformanceCounter( ( LARGE_INTEGER* )&StartTime );
    if( !CompressFileStreaming( strInputFile, strDestinationFile, g_dwCompressionBlock ) )
    {
        g_Console.Format( "Error: Compression failed.\n" );
        return;
    }
    QueryPerformanceCounter( ( LARGE_INTEGER* )&EndTime );

    g_Console.Format( "Compression done. Time taken: %0.6f s. Compression: %0.2f%%.\n",
                      ( double )( EndTime - StartTime ) / ( double )PerfFrequency,
                      100.0 * ( ( double )g_dwFileSize - ( double )GetFileSizeHelper( strDestinationFile ) ) /
                      ( double )g_dwFileSize );

    g_Console.Format( "Decompressing file (streaming) <%s>...\n", strDestinationFile );

    QueryPerformanceCounter( ( LARGE_INTEGER* )&StartTime );
    if( !DecompressFileStreaming( strDestinationFile, strInputFile, g_dwCompressionBlock ) )
    {
        g_Console.Format( "Error: Decompression failed.\n" );
        return;
    }
    QueryPerformanceCounter( ( LARGE_INTEGER* )&EndTime );

    g_Console.Format( "Decompression done. Time taken: %0.6f s.\n", ( double )( EndTime - StartTime ) / ( double )
                      PerfFrequency );
}


//--------------------------------------------------------------------------------------
// Name: ReadFileIntoMemory
// Desc: Simply read file into memory to test transparent decompression.
//--------------------------------------------------------------------------------------
VOID ReadFileIntoMemory( const CHAR* strFile )
{
    HANDLE hFile = CreateFile( strFile, GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL );
    if( hFile == INVALID_HANDLE_VALUE )
    {
        g_Console.Format( "Error: Could not open file with transparent decompression.\n" );
        return;
    }

    DWORD dwFileSize = GetFileSize( hFile, NULL );

    CHAR pReadBuffer[4096];
    DWORD dwReadBytes = 0;

    while( dwReadBytes != dwFileSize )
    {
        DWORD dwBytes = 0;
        if( !ReadFile( hFile, pReadBuffer, sizeof( pReadBuffer ), &dwBytes, NULL ) )
        {
            g_Console.Format( "Error: Could not read file with transparent decompression.\n" );
            break;
        }

        dwReadBytes += dwBytes;
    }

    if( dwReadBytes == dwFileSize )
    {
        g_Console.Format( "Successfully read %u bytes from transparently compressed file.\n", dwReadBytes );
    }

    CloseHandle( hFile );
}


//--------------------------------------------------------------------------------------
// Name: main
// Desc: Entry point to the program
//--------------------------------------------------------------------------------------
INT __cdecl main()
{
    // Initialize the console window
    g_Console.Create( "game:\\Media\\Fonts\\Courier_New_11.xpr", 0xFF1F005F, 0xFFFFFFFF );

    // Map E: partition
    DmMapDevkitDrive();

    // Create test files
    if( CreateFiles() )
    {
        // Run compression tests
        RunTest( g_strCompressibleFile, g_strCompressibleDestFile );
        RunTest( g_strUncompressibleFile, g_strUncompressibleDestFile );
    }
    else
    {
        g_Console.Format( "Error: Could not create files.\n" );
    }

    // Initialize transparent decompression with default parameters
    g_Console.Format( "\nInitializing transparent decompression...\n" );

    if( SUCCEEDED( XFileEnableTransparentDecompression( NULL ) ) )
    {
        ReadFileIntoMemory( g_strTransparentCompressedFile );
        XFileDisableTransparentDecompression();
    }
    else
    {
        g_Console.Format( "Error: Could not initialize transparent decompression.\n" );
    }

    g_Console.Format( "\nPress A to delete files, LT + RT + RB to exit.\n" );

    // Wait for the user to press a button.
    for(; ; )
    {
        ATG::GAMEPAD* pGamepad = ATG::Input::GetMergedInput(); // Detect reboot keypress
        if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_A )
        {
            g_Console.Format( "Deleting files...\n" );
            DeleteFile( g_strCompressibleFile );
            DeleteFile( g_strUncompressibleFile );
            DeleteFile( g_strCompressibleDestFile );
            DeleteFile( g_strUncompressibleDestFile );
            g_Console.Format( "Files are deleted.\n" );
        }
    }
}
