//--------------------------------------------------------------------------------------
// TrainGesture.cpp
//
// This sample demonstrates how the time consuming art of manually fine tuning input
// parameters and thresholds for gesture detection implementations can be replaced by
// an automatic process where a computer finds the best input paramters and thresholds
// by using machine learning. The gesture detection system used in this sample consist
// of training component which runs on the PC (GenerateLabeledExamples and TrainGesture)
// and a runtime component that is used in this sample on the Xbox 360.
//
// The goal of this application is to read labeled training examples generated by
// GenerateLabeledExamples.exe as input and outputs a gesture file that can be
// used for gesture detection at runtime. An example batch file is included to show
// how to use this application
//
//      \GestureDetectorTrainer\TrainGestures.bat
//
// Advanced Technology Group (ATG)
// Copyright (C) Microsoft Corporation. All rights reserved.
//--------------------------------------------------------------------------------------

#include <stdio.h>
#include <string.h>
#include <iostream>
#include "..\..\GestureDetector\GestureDetector.h"

using namespace ATGGestureDetector;

//--------------------------------------------------------------------------------------
// Constants
//--------------------------------------------------------------------------------------

static const DOUBLE g_fDefaultAccuracyLevel                 = 0.95;
static const UINT   g_nNumWeakClassifiersAtRuntime          = 1000;
static const FLOAT  g_fWeightOfFalsePositivesWhenFiltering  = 0.5f;
static const UINT   g_uCPUAvailableForTraining              = 95;


//--------------------------------------------------------------------------------------
// Forward declarations
//--------------------------------------------------------------------------------------

BOOL ValidateCommandlineParameters( INT nNumParameters, CHAR* szParameters[] );


//--------------------------------------------------------------------------------------
// Name: main
// Desc: main entry point for application
//--------------------------------------------------------------------------------------

INT main( INT nNumParameters, CHAR* szParameters[] )
{ 
    printf( "\nTrainGesture"
            "\n------------\n" );

    if ( !ValidateCommandlineParameters( nNumParameters, szParameters ))
    {
        return -1;
    }

    DWORD dwStart = GetTickCount();

    const CHAR* szGestureName       = szParameters[ 1 ];
    const CHAR* szDataFolder        = szParameters[ 2 ];
    const CHAR* szOutputFileName    = szParameters[ 3 ];
    
    DOUBLE fAccuracyLevel = g_fDefaultAccuracyLevel;
    if ( nNumParameters > 4 )
    {
        fAccuracyLevel = atof( szParameters[ 4 ] );
    }

    UINT nNumWeakClassifiersAtRuntime = g_nNumWeakClassifiersAtRuntime;
    if ( nNumParameters > 5 )
    {
        nNumWeakClassifiersAtRuntime = (UINT)atoi( szParameters[ 5 ] );
    }

    FLOAT fWeightOfFalsePositivesWhenFiltering = g_fWeightOfFalsePositivesWhenFiltering;
    if ( nNumParameters > 6 )
    {
        fWeightOfFalsePositivesWhenFiltering = (FLOAT)atof( szParameters[ 6 ] );
    }

    BOOL bOnlyRetrainDetectionParameters = FALSE;
    if ( nNumParameters > 7 )
    {
        bOnlyRetrainDetectionParameters = ( _stricmp( szParameters[ 7 ], "true" ) == 0 );
    }

    UINT uCPUAvailableForTraining = g_uCPUAvailableForTraining;
    if ( nNumParameters > 8 )
    {
        uCPUAvailableForTraining = (UINT)atoi( szParameters[ 8 ] );
    }

    CHAR szPath[ MAX_PATH ];
    sprintf_s( szPath, sizeof( szPath ), "%s\\%s_%s.le", szDataFolder, szGestureName, g_szTraining );

    GestureDetectorTrainer gestureDetectorTrainer;

    // If we only want to retrain the detection filter parameters, then simply load in the existing
    // gesture file and run only the trainer for the parameters
    if ( bOnlyRetrainDetectionParameters )
    {
        if ( FAILED( gestureDetectorTrainer.Load( szOutputFileName ) ) )
        {
            printf( "\nERROR: Failed to load gesture detector\n" );
            return -1;
        }
    }
    
    if ( FAILED( gestureDetectorTrainer.Train( szPath, fAccuracyLevel, nNumWeakClassifiersAtRuntime, fWeightOfFalsePositivesWhenFiltering, bOnlyRetrainDetectionParameters, uCPUAvailableForTraining ) ) )
    {
        // Delete any old file so that we don't accidentally use stale data
        std::remove( szOutputFileName );
        printf( "\nERROR: Failed to train gesture detector\n" );
        return -1;
    }

    if ( FAILED( gestureDetectorTrainer.Save( szOutputFileName ) ) )
    {
        printf( "\nERROR: Failed to save training data from gesture detector\n" );
        return -1;
    }

    DWORD dwStop = GetTickCount();
    DWORD dwSeconds = ( (dwStop - dwStart ) / 1000 ) % 60;
    DWORD dwMinutes = ( (dwStop - dwStart ) / 1000) / 60;
    printf( "\nTotal Duration: %d minutes, %d seconds",  dwMinutes, dwSeconds );

    printf( "\n\n\nTesting on Training Data" );
    if ( FAILED( gestureDetectorTrainer.Test( NULL, TRUE ) ) )
    {
        printf( "\nERROR: Failed to test on training data\n" );
        return -1;
    }

    sprintf_s( szPath, sizeof( szPath ), "%s\\%s_%s.le", szDataFolder, szGestureName, g_szTesting );
    printf( "\n\nTesting on Test Data" );
    if ( FAILED( gestureDetectorTrainer.Test( szPath, FALSE ) ) )
    {
        printf( "\nWARNING: Failed to test on testing data\n" );
    }

    printf( "\n\nTop 10 contributing weak classifiers:");
    DebugOutput output;
    for ( UINT i = 0; i < 10; i++ )
    {
        printf( "\n\t%s", output.Print( (GestureDetector*)&gestureDetectorTrainer, i ) );
    }

    printf( "\n\nDone\n\n" );

    return 0;
}


//--------------------------------------------------------------------------------------
// Name: ValidateCommandlineParameters
// Desc: Validates the command line parameters
//--------------------------------------------------------------------------------------

BOOL ValidateCommandlineParameters( INT nNumParameters, CHAR* szParameters[] )
{
    BOOL bFail = FALSE;

    // Check parameters
    if ( nNumParameters < 4 ||
         nNumParameters > 9 )
    {
        bFail = TRUE;
    }
    
    if ( nNumParameters > 4 )
    {
        const DOUBLE fAccuracyLevel = atof( szParameters[ 4 ] );
        if ( fAccuracyLevel < 0.0f ||
             fAccuracyLevel > 1.0f )
        {
            bFail = TRUE;
        }
    }
    
    if ( nNumParameters > 5 )
    {
        const UINT nNumWeakClassifiersAtRuntime = (UINT)atoi( szParameters[ 5 ] );
        if ( nNumWeakClassifiersAtRuntime > 100000 )
        {
            bFail = TRUE;
        }
    }
    
    if ( nNumParameters > 6 )
    {
        const FLOAT fWeightOfFalsePositivesWhenFiltering = (FLOAT)atof( szParameters[ 6 ] );
        if ( fWeightOfFalsePositivesWhenFiltering < 0.0f ||
             fWeightOfFalsePositivesWhenFiltering > 1.0f )
        {
            bFail = TRUE;
        }
    }
    
    if ( nNumParameters > 7 )
    {
        // Nothing to verify, this is just a bool value
    }
    
    if ( nNumParameters > 8 )
    {
        const UINT g_uCPUAvailableForTraining = (UINT)atoi( szParameters[ 8 ] );
        if ( g_uCPUAvailableForTraining > 100 )
        {
            bFail = TRUE;
        }
    }

    if ( bFail )
    {
        printf( "\n\nInstructions:\n    Use the XedFileTagger sample to add gesture tags to a xed file, "
                "\n    e.g. tag the frames that represent a left punch as 'Punch_Left'." );
        printf( "\n\nUsage:\n    TrainGesture <GestureName> <FolderWithLabeledExamples> <Output> <AccuracyLevel> <NumWeakClassifiersAtRuntime> <WeightOfFalsePositivesWhenFiltering> <OnlyRetrainDetectionParameters> <CPUForTraining>\n\n"
                "     <GestureName>\n"
                "       The gesture to train. The gesture should be tagged with this name\n"
                "       using the XedFileTagger sample.\n\n"
                "     <FolderWithLabeledExamples>\n"
                "       Folder where GenerateLabeledExamples.exe saved labeled examples file.\n\n"
                "     <Output>\n"
                "       Output file with trained data for runtime detection.\n\n"
                "     <AccuracyLevel>\n"
                "       Valaue between 0..1, with 1 most accucate but very slow training\n"
                "       time. Default is %5.2f.\n\n"
                "     <NumWeakClassifiersAtRuntime>\n"
                "       Number of weak classifiers used at runtime. 0 means use all\n"
                "       classifiers. Default is %d.\n\n"
                "     <WeightOfFalsePositivesWhenFiltering>\n"
                "       Value between 0..1 indicating the weight of false positives when\n"
                "       calculating the best filtering parameters for per frame results to\n"
                "       per gesture results. 1.0 means optimize filtering parameters only for\n"
                "       false postives. Default is %5.2f.\n\n"
                "     <OnlyRetrainDetectionParameters>"
                "       When true, training will try to load an alreayd trained .gesture file\n"
                "       and only retrain the detection filter parameters to minimize the\n"
                "       error in true positives and false positives.\n\n"
                "     <CPUForTraining>\n"
                "       Value of 0..100, indicating the %% of CPU resources you want to\n"
                "       allow during training, default is %d.\n\n"
                "Example:\n"
                "   TrainGesture.exe Punch_Left .\\Data .\\Data\\Punch_Left.gesture %5.2f %d %5.2f %d\n\n",
                g_fDefaultAccuracyLevel, g_nNumWeakClassifiersAtRuntime, g_fWeightOfFalsePositivesWhenFiltering, g_uCPUAvailableForTraining,
                g_fDefaultAccuracyLevel, g_nNumWeakClassifiersAtRuntime, g_fWeightOfFalsePositivesWhenFiltering, g_uCPUAvailableForTraining );

        return FALSE;
    }

    return TRUE;
}

