//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by GestureBuilder, Version=2.0.21105.0.
//

#pragma once

namespace KickBoxing
{
    const DWORD SIGNATURE = 0x6ACE05A;

    const DWORD DIGEST[8] = {
        0xE7E0C168,
        0xBCF57E3D,
        0x3AD665CB,
        0x6EFCB04B,
        0xA4ECE2AF,
        0x15BC6289,
        0xEAD67F10,
        0xECB2500A,
    };

    enum {
        GESTURE_PUNCH_LEFT = 0,
        GESTURE_PUNCH_RIGHT,
        GESTURE_KICK_LEFT,
        GESTURE_KICK_RIGHT,
        GESTURE_PUNCHPROGRESS,
        GESTURE_KICKPROGRESS,
        GESTURE_COUNT,
    };

    typedef struct _AdaBoostTrigger {
        BOOL Value;
        FLOAT Confidence;
        BOOL FirstFrameDetected;
        BOOL Valid;
    } AdaBoostTrigger;

    typedef struct _PCAProgress {
        FLOAT Value;
        BOOL Valid;
    } PCAProgress;

    typedef struct _PLAYER_STATE {
        AdaBoostTrigger Punch_Left;
        AdaBoostTrigger Punch_Right;
        AdaBoostTrigger Kick_Left;
        AdaBoostTrigger Kick_Right;
        PCAProgress PunchProgress;
        PCAProgress KickProgress;
    } PLAYER_STATE;

    typedef struct _FRAME {
        PLAYER_STATE Players[NUI_SKELETON_MAX_TRACKED_COUNT];
    } FRAME;

    __forceinline static VOID INITIALIZE_NUI_GESTURE_FRAME(_In_ FRAME* pPayload, _Inout_ NUI_GESTURE_FRAME* pFrame)
    {
        pFrame->Signature = SIGNATURE;
        pFrame->pData = pPayload;
        pFrame->DataSize = sizeof(FRAME);
    }

}
