//--------------------------------------------------------------------------------------
// PredicatedTiling.cpp
//
// This sample shows how to use Predicated Tiling to render to a surface in tiled segments.
// This technique is essential for rendering to surfaces that are too large to fit into
// EDRAM all at once, such as a 1280x720 4x MSAA surface.  It can also be used for
// specialized offscreen rendering, such as creating a huge shadow buffer that would be
// too large for EDRAM.
//
// The sample takes tiling scenarios as input.  Examine the TILING_SCENARIO struct below
// and experiment with various scenarios by adding to the scenario lists.
//
// Predicated Tiling works by replaying a single command buffer several times.  Your
// rendering calls are largely unchanged, except they need to be surrounded by
// D3DDevice::BeginTiling() and D3DDevice::EndTiling().  Also, since Predicated Tiling
// resolves into a texture, you will need to use D3DDevice::Swap() to view the final
// image, instead of using D3DDevice::Present().
//
// Each draw command is predicated on results collected during the first pass.
// These results contain the screen space extents of each draw command (which is
// collected by the hardware), so draw commands played back for each tile only execute
// on the tile(s) that it affects.  You can override the predication by using
// D3DDevice::SetPredication(), if you are sure that a particular
// command or sequence of commands will always be on one specific tile.
// SetPredication() is demonstrated below to highlight the tile boundary.
//
// Postprocessing effects (tone mapping, etc) are ideally done using the final
// frontbuffer texture which contains the full image generated by Predicated Tiling.
//
// If you perform any rendering calls that could potentially affect your program's state,
// such as memexport shader usage or XPS procedural synthesis, keep in mind that
// Predicated Tiling will execute these rendering calls once per tile (i.e. multiple
// times per frame).  This may or may not be the desired functionality, depending on the
// situation.
//
// Xbox Advanced Technology Group.
// Copyright (C) Microsoft Corporation. All rights reserved.
//--------------------------------------------------------------------------------------
#include <xtl.h>
#include <xgraphics.h>
#include <xboxmath.h>
#include <AtgFont.h>
#include <AtgInput.h>
#include <AtgUtil.h>
#include <AtgMesh.h>
#include <AtgHelp.h>
#include <AtgApp.h>


//--------------------------------------------------------------------------------------
// Callouts for labelling the gamepad on the help screen
//--------------------------------------------------------------------------------------
ATG::HELP_CALLOUT g_HelpCallouts[] =
{
    { ATG::HELP_A_BUTTON,     ATG::HELP_PLACEMENT_1, L"Cycle scenario" },
    { ATG::HELP_Y_BUTTON,     ATG::HELP_PLACEMENT_2, L"Force\npredication" },
    { ATG::HELP_X_BUTTON,     ATG::HELP_PLACEMENT_2, L"Camera\ndistance" },
    { ATG::HELP_B_BUTTON,     ATG::HELP_PLACEMENT_1, L"Rotation" },
    { ATG::HELP_BACK_BUTTON,  ATG::HELP_PLACEMENT_2, L"Display\nhelp"  },
};
#define NUM_HELP_CALLOUTS (sizeof(g_HelpCallouts) / sizeof(g_HelpCallouts[0]))


//--------------------------------------------------------------------------------------
// Name: struct TILING_SCENARIO
// Desc: Describes a configuration of MSAA quality and tiling rectangles to be used for
//       Predicated Tiling.
//--------------------------------------------------------------------------------------
struct TILING_SCENARIO
{
    const WCHAR* strScenarioName;
    DWORD dwScreenWidth;
    DWORD dwScreenHeight;
    D3DMULTISAMPLE_TYPE MSAAType;
    DWORD dwTilingFlags;
    D3DSCREENEXTENTQUERYMODE ScreenExtentQueryMode;
    DWORD dwTileCount;
    D3DRECT TilingRects[15];
};


//--------------------------------------------------------------------------------------
// Tiling scenarios
//
// Note that the list must be NULL terminated, and that it is not necessary to
// initialize all 15 possible tiling rectangles.
//
// Also note that the tiling rectangles must be texture tile aligned (32x32), unless 
// a rectangle coordinate matches the dimensions of the front buffer (i.e. the rectangle
// touches an edge of the screen).
//--------------------------------------------------------------------------------------

const TILING_SCENARIO g_TilingScenarios[] =
{
    {
        L"1024x576 2x MSAA No tiling",
        1024,
        576,
        D3DMULTISAMPLE_2_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        1,
        {
            { 0,   0, 1024, 576 },
        }
    },
    {
        L"1024x576 4x MSAA Horizontal Split",
        1024,
        576,
        D3DMULTISAMPLE_4_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        2,
        {
            { 0,   0, 1024, 288 },
            { 0, 288, 1024, 576 }
        }
    },
    {
        L"1120x584 2x MSAA No tiling",
        1120,
        584,
        D3DMULTISAMPLE_2_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        1,
        {
            { 0,   0, 1120, 584 },
        }
    },
    {
        L"1120x576 4x MSAA Horizontal Split",
        1120,
        576,
        D3DMULTISAMPLE_4_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        2,
        {
            { 0,   0, 1120, 288 },
            { 0, 288, 1120, 576 }
        }
    },
    {
        L"1200x720 No MSAA",
        1200,
        720,
        D3DMULTISAMPLE_NONE,
        0,
        D3DSEQM_PRECLIP,
        1,
        {
            { 0,   0, 1200, 720 },
        }
    },
    {
        L"1280x720 No MSAA",
        1280,
        720,
        D3DMULTISAMPLE_NONE,
        0,
        D3DSEQM_PRECLIP,
        1,
        {
            { 0,   0, 1280, 720 },
        }
    },
    {
        L"1280x720 2xMSAA Horizontal Split",
        1280,
        720,
        D3DMULTISAMPLE_2_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        2,
        {
            { 0,   0, 1280, 384 },
            { 0, 384, 1280, 720 }
        }
    },
    {
        L"1280x720 2xMSAA Vertical Split",
        1280,
        720,
        D3DMULTISAMPLE_2_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        2,
        {
            {   0, 0,  640, 720 },
            { 640, 0, 1280, 720 }
        }
    },
    {
        L"1280x720 2xMSAA Horizontal Split, One Pass Z Pass",
        1280,
        720,
        D3DMULTISAMPLE_2_SAMPLES,
        D3DTILING_ONE_PASS_ZPASS | D3DTILING_FIRST_TILE_INHERITS_DEPTH_BUFFER,
        D3DSEQM_CULLED,
        2,
        {
            { 0,   0, 1280, 384 },
            { 0, 384, 1280, 720 }
        }
    },
    {
        L"1280x720 2xMSAA Vertical Split, One Pass Z Pass",
        1280,
        720,
        D3DMULTISAMPLE_2_SAMPLES,
        D3DTILING_ONE_PASS_ZPASS,
        D3DSEQM_CULLED,
        2,
        {
            {   0, 0,  640, 720 },
            { 640, 0, 1280, 720 }
        }
    },
    {
        L"1280x720 4xMSAA Horizontal Split",
        1280,
        720,
        D3DMULTISAMPLE_4_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        3,
        {
            { 0,   0, 1280, 256 },
            { 0, 256, 1280, 512 },
            { 0, 512, 1280, 720 },
        }
    },
    {
        L"1280x720 4xMSAA Vertical Split",
        1280,
        720,
        D3DMULTISAMPLE_4_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        4,
        {
            {   0,   0,  320, 720 },
            { 320,   0,  640, 720 },
            { 640,   0,  960, 720 },
            { 960,   0, 1280, 720 },
        }
    },
    {
        L"1920x1080 No MSAA Horizontal Split",
        1920,
        1080,
        D3DMULTISAMPLE_NONE,
        0,
        D3DSEQM_PRECLIP,
        2,
        {
            {   0,   0, 1920,  544 },
            {   0, 544, 1920, 1080 },
        }
    },
    {
        L"1920x1080 No MSAA Vertical Split",
        1920,
        1080,
        D3DMULTISAMPLE_NONE,
        0,
        D3DSEQM_PRECLIP,
        2,
        {
            {   0,   0,  960, 1080 },
            { 960,   0, 1920, 1080 },
        }
    },
    {
        L"1920x1080 2x MSAA Vertical Split",
        1920,
        1080,
        D3DMULTISAMPLE_2_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        4,
        {
            {    0,   0,  480, 1080 },
            {  480,   0,  960, 1080 },
            {  960,   0, 1440, 1080 },
            { 1440,   0, 1920, 1080 },
        }
    },
    {
        L"1920x1080 4x MSAA Horizontal Split",
        1920,
        1080,
        D3DMULTISAMPLE_4_SAMPLES,
        0,
        D3DSEQM_PRECLIP,
        7,
        {
            {    0,    0, 1920,  160 },
            {    0,  160, 1920,  320 },
            {    0,  320, 1920,  480 },
            {    0,  480, 1920,  640 },
            {    0,  640, 1920,  800 },
            {    0,  800, 1920,  960 },
            {    0,  960, 1920, 1080 },
        }
    },
    { NULL }
};


//--------------------------------------------------------------------------------------
// Name: class CRobotMesh
// Desc: This subclass of ATG::Mesh contains code that properly sends the transform
//       matrix to the vertex shader constant table before each mesh is rendered.  The
//       robot contains a hierarchy of frames, each with their own object-space
//       transform to place each body part.
//--------------------------------------------------------------------------------------
class CRobotMesh : public ATG::Mesh
{
public:
    XMMATRIX m_matWorld;
    XMMATRIX m_matViewProj;
    XMVECTOR m_vWorldLightDirection;

    virtual VOID RenderMeshCallback( DWORD dwFrame, const ATG::MESH_FRAME* pFrame, DWORD dwFlags )
    {
        XMMATRIX matWorld = m_matWorld * pFrame->m_matTransform;

        // ((M^-1)^T)^-1 = M^T
        XMMATRIX matWorldTranspose = XMMatrixTranspose( matWorld );

        XMVECTOR vLocalLightDir;
        vLocalLightDir = XMVector3TransformNormal( m_vWorldLightDirection, matWorldTranspose );
        vLocalLightDir = XMVector3Normalize( vLocalLightDir );

        ATG::g_pd3dDevice->SetVertexShaderConstantF( 4, ( FLOAT* )&vLocalLightDir, 1 );

        XMMATRIX matWVP = matWorld * m_matViewProj;
        ATG::g_pd3dDevice->SetVertexShaderConstantF( 0, ( FLOAT* )&matWVP, 4 );
    }
};


//--------------------------------------------------------------------------------------
// Name: class Sample
// Desc: The predicated tiling sample class.
//--------------------------------------------------------------------------------------
class Sample : public ATG::Application
{
public:
            Sample();
    HRESULT Initialize();
    HRESULT Update();
    HRESULT Render();
private:
    VOID    ResetDevice();
    VOID    RenderScene();
    VOID    RenderUI();

    XMMATRIX m_matWorld;
    XMMATRIX m_matView;
    XMMATRIX m_matProj;
    XMMATRIX m_matWVP;
    XMVECTOR m_vWorldLightDirection;

    D3DTexture* m_pFrontBufferTexture;
    D3DTexture* m_pSceneResolveTexture;
    D3DTexture  m_SceneResolveTextureAs16SRGB;
    D3DSurface* m_pTilingRenderTarget;
    D3DSurface* m_pTilingDepthStencil;
    D3DSurface* m_pPostRenderTarget;
    IDirect3DVertexShader9* m_pVertexShader;
    IDirect3DPixelShader9* m_pPixelShader;
    IDirect3DVertexDeclaration9* m_pVertexDecl;

    IDirect3DVertexShader9* m_pVertexShaderPost;
    IDirect3DPixelShader9* m_pPixelShaderPost;
    IDirect3DVertexDeclaration9* m_pVertexDeclPost;

    ATG::Font m_Font;
    ATG::Timer m_Timer;
    ATG::Help m_Help;
    BOOL m_bDrawHelp;
    FLOAT m_fEyeRadius;
    BOOL m_bRotating;
    BOOL m_bForcedPredication;

    DWORD m_dwScenarioIndex;
    BOOL m_bAllow1920x1080;

    DWORD m_dwFrontBufferSizeBytes;
    DWORD m_dwTileTargetSizeBytes;
    DWORD m_dwTileDepthStencilSizeBytes;
    CRobotMesh m_RobotMesh;
};


Sample::Sample() : m_pFrontBufferTexture( NULL ),
                   m_pSceneResolveTexture( NULL ),
                   m_pTilingRenderTarget( NULL ),
                   m_pTilingDepthStencil( NULL ),
                   m_pPostRenderTarget( NULL ),
                   m_pVertexShader( NULL ),
                   m_pPixelShader( NULL ),
                   m_pVertexDecl( NULL ),
                   m_pVertexShaderPost( NULL ),
                   m_pPixelShaderPost( NULL ),
                   m_pVertexDeclPost( NULL ),
                   m_bDrawHelp( FALSE ),
                   m_fEyeRadius( 8.0f ),
                   m_bRotating( TRUE ),
                   m_bForcedPredication( FALSE ),
                   m_dwScenarioIndex( 0 ),
                   m_dwFrontBufferSizeBytes( 0 ),
                   m_dwTileTargetSizeBytes( 0 ),
                   m_dwTileDepthStencilSizeBytes( 0 )
{
}


//--------------------------------------------------------------------------------------
// Vertex shader with one white directional light, and a little bit of fake
// backlighting to make the model look nicer.
//--------------------------------------------------------------------------------------
const CHAR* g_strVertexShaderProgram =
    " float4x4 matWVP : register(c0);                                            \n"
    " float3 LightDirection : register(c4);                                      \n"
    "                                                                            \n"
    " struct VS_OUT                                                              \n"
    " {                                                                          \n"
    "     float4 ProjPos  : POSITION;                                            \n"
    "     float4 Color    : COLOR;                                               \n"
    " };                                                                         \n"
    "                                                                            \n"
    " VS_OUT main( const float3 ObjPos : POSITION,                               \n"
    "              const float3 Normal : NORMAL,                                 \n"
    "              const float2 TexCoord : TEXCOORD0 )                           \n"
    " {                                                                          \n"
    "     VS_OUT Out;                                                            \n"
    "     Out.ProjPos = mul( matWVP, float4( ObjPos, 1 ) );                      \n"
    "     Out.Color = saturate( dot( Normal, -LightDirection ) );                \n"
    "     Out.Color += 0.1 * saturate( dot( Normal, LightDirection ) );          \n"
    "     return Out;                                                            \n"
    " }                                                                          \n"
    "                                                                            \n"
    " struct VS_OUT_POST                                                         \n"
    " {                                                                          \n"
    "     float4 ProjPos  : POSITION;                                            \n"
    "     float2 Tex0     : TEXCOORD0;                                           \n"
    " };                                                                         \n"
    "                                                                            \n"
    " VS_OUT_POST vs_main_post ( const float2 ObjPos: POSITION )                 \n"
    " {                                                                          \n"
    "     VS_OUT_POST Out;                                                       \n"
    "     Out.ProjPos = float4( ObjPos, 0, 1 );                                  \n"
    "     Out.Tex0 = ( ObjPos * float2( 0.5, -0.5 ) ) + float2( 0.5, 0.5 );      \n"
    "     return Out;                                                            \n"
    " }                                                                          \n";


//--------------------------------------------------------------------------------------
// Pixel shader
//--------------------------------------------------------------------------------------
const CHAR* g_strPixelShaderProgram =
    " struct PS_IN                                   \n"
    " {                                              \n"
    "     float4 Color : COLOR;                      \n"
    " };                                             \n"
    "                                                \n"
    " float4 main( PS_IN In ) : COLOR                \n"
    " {                                              \n"
    "     return In.Color;                           \n"
    " }                                              \n"
    "                                                \n"
    " struct PS_IN_POST                              \n"
    " {                                              \n"
    "     float2 Tex0 : TEXCOORD0;                   \n"
    " };                                             \n"
    "                                                \n"
    " sampler2D screen_texture : register(s0);       \n"
    "                                                \n"
    " float4 ps_main_post( PS_IN_POST In ) : COLOR   \n"
    " {                                              \n"
    "     return tex2D( screen_texture, In.Tex0 );   \n"
    " }                                              \n";


//--------------------------------------------------------------------------------------
// Name: LargestTileRectSize()
// Desc: Returns the dimensions that fit the largest rectangle(s) out of the tiling
//       rectangles.
//--------------------------------------------------------------------------------------
VOID LargestTileRectSize( const TILING_SCENARIO& Scenario, D3DPOINT* pMaxSize )
{
    pMaxSize->x = 0;
    pMaxSize->y = 0;
    for( DWORD i = 0; i < Scenario.dwTileCount; i++ )
    {
        DWORD dwWidth = Scenario.TilingRects[i].x2 - Scenario.TilingRects[i].x1;
        DWORD dwHeight = Scenario.TilingRects[i].y2 - Scenario.TilingRects[i].y1;
        if( dwWidth > ( DWORD )pMaxSize->x )
            pMaxSize->x = dwWidth;
        if( dwHeight > ( DWORD )pMaxSize->y )
            pMaxSize->y = dwHeight;
    }
}


//--------------------------------------------------------------------------------------
// Name: ResetDevice()
// Desc: Rebuilds all rendertargets and resolve textures, and  
//--------------------------------------------------------------------------------------
VOID Sample::ResetDevice()
{
    HRESULT hr;

    // Clean out the D3D device before destroying any resources.  D3D will
    // assert if a resource is destroyed while still selected into a D3D
    // device.
    m_pd3dDevice->UnsetAll();

    // Destroy resources
    SAFE_RELEASE( m_pTilingRenderTarget );
    SAFE_RELEASE( m_pTilingDepthStencil );
    SAFE_RELEASE( m_pPostRenderTarget );

    // Destroy frontbuffer and scene resolve textures.
    SAFE_RELEASE( m_pFrontBufferTexture );
    SAFE_RELEASE( m_pSceneResolveTexture );

    // Setup the presentation parameters
    const TILING_SCENARIO& CurrentScenario = g_TilingScenarios[m_dwScenarioIndex];

    DWORD dwFrontBufferWidth = CurrentScenario.dwScreenWidth;
    DWORD dwFrontBufferHeight = CurrentScenario.dwScreenHeight;

    // Set viewport.
    D3DVIEWPORT9 Viewport;
    Viewport.Width = dwFrontBufferWidth;
    Viewport.Height = dwFrontBufferHeight;
    Viewport.X = 0;
    Viewport.Y = 0;
    Viewport.MinZ = 0.0f;
    Viewport.MaxZ = 0.0f;
    m_pd3dDevice->SetViewport( &Viewport );

    // Set up tiling front buffer texture.
    // These are the size of your desired rendering surface (in this case, the whole
    // screen).
    // We also create a scene resolve texture here, which will be used to hold the
    // results of predicated tiling.  If we were tiling directly to the front buffer,
    // we would require 2 front buffers used on even-odd frames, to avoid visual
    // tearing.
    m_pd3dDevice->CreateTexture( dwFrontBufferWidth,
                                 dwFrontBufferHeight,
                                 1, 0,
                                 ( D3DFORMAT )MAKESRGBFMT( D3DFMT_LE_X8R8G8B8 ),
                                 D3DPOOL_DEFAULT,
                                 &m_pFrontBufferTexture,
                                 NULL );

    m_pd3dDevice->CreateTexture( dwFrontBufferWidth,
                                 dwFrontBufferHeight,
                                 1, 0,
                                 ( D3DFORMAT )MAKESRGBFMT( D3DFMT_X8R8G8B8 ),
                                 D3DPOOL_DEFAULT,
                                 &m_pSceneResolveTexture,
                                 NULL );

    m_SceneResolveTextureAs16SRGB = *m_pSceneResolveTexture;

    // Set up an alias of the resolve texture as an AS_16 sRGB format, since the GPU can't resolve 
    // to an AS_16_16_16_16 format. 
    // Alias this texture so there's no loss of precision when sampling the texture in the shader. If using
    // a standard SRGB format, the sRGB->Linear conversion happens with 8 bit precision, resulting 
    // in a loss of data. Using an AS_16 sRGB format causes the conversion to happen at 16-bit precision,
    // meaning no precision is lost.
    ATG::ConvertTextureToAs16SRGBFormat( &m_SceneResolveTextureAs16SRGB );

    if( NULL == m_pFrontBufferTexture || NULL == m_pSceneResolveTexture )
    {
        ATG::FatalError( "Could not create front buffer or scene resolve texture." );
    }

    // Record the size of one of the frontbuffers.
    m_dwFrontBufferSizeBytes = dwFrontBufferWidth * dwFrontBufferHeight * sizeof( DWORD );

    // Aspect ratio for HiDef displays is always 16x9 but our buffers may not be.
    FLOAT fAspectRatio = 16.0f / 9.0f; //( FLOAT )dwFrontBufferWidth / ( FLOAT )dwFrontBufferHeight;

    // Set up projection matrix
    m_matProj = XMMatrixPerspectiveFovLH( XM_PIDIV4, fAspectRatio, 1.0f, 200.0f );

    // Find largest tiling rect size
    D3DPOINT LargestTileSize;
    LargestTileRectSize( CurrentScenario, &LargestTileSize );

    // Create color and depth/stencil rendertargets.
    // These rendertargets are where Predicated Tiling will render each tile.  Therefore,
    // these rendertargets should be set up with all rendering quality settings you desire,
    // such as multisample antialiasing.
    // Note how we use the dimension of the largest tile rectangle to define how big the
    // rendertargets are.
    DWORD dwTileWidth = 0;
    DWORD dwTileHeight = 0;
    switch( CurrentScenario.MSAAType )
    {
        case D3DMULTISAMPLE_NONE:
            dwTileWidth = XGNextMultiple( LargestTileSize.x, GPU_EDRAM_TILE_WIDTH_1X );
            dwTileHeight = XGNextMultiple( LargestTileSize.y, GPU_EDRAM_TILE_HEIGHT_1X );
            break;
        case D3DMULTISAMPLE_2_SAMPLES:
            dwTileWidth = XGNextMultiple( LargestTileSize.x, GPU_EDRAM_TILE_WIDTH_2X );
            dwTileHeight = XGNextMultiple( LargestTileSize.y, GPU_EDRAM_TILE_HEIGHT_2X );
            break;
        case D3DMULTISAMPLE_4_SAMPLES:
            dwTileWidth = XGNextMultiple( LargestTileSize.x, GPU_EDRAM_TILE_WIDTH_4X );
            dwTileHeight = XGNextMultiple( LargestTileSize.y, GPU_EDRAM_TILE_HEIGHT_4X );
            break;
    }

    if( CurrentScenario.dwTileCount > 1 )
    {
        // Expand tile surface dimensions to texture tile size, if it isn't already
        dwTileWidth = XGNextMultiple( dwTileWidth, GPU_TEXTURE_TILE_DIMENSION );
        dwTileHeight = XGNextMultiple( dwTileHeight, GPU_TEXTURE_TILE_DIMENSION );
    }

    // Use custom EDRAM allocation to create the rendertargets.
    // The color rendertarget is placed at address 0 in EDRAM.
    D3DSURFACE_PARAMETERS SurfaceParams;
    memset( &SurfaceParams, 0, sizeof( D3DSURFACE_PARAMETERS ) );
    SurfaceParams.Base = 0;
    hr = m_pd3dDevice->CreateRenderTarget( dwTileWidth,
                                           dwTileHeight,
                                           ( D3DFORMAT )MAKESRGBFMT( D3DFMT_A8R8G8B8 ),
                                           CurrentScenario.MSAAType,
                                           0, FALSE,
                                           &m_pTilingRenderTarget,
                                           &SurfaceParams );
    if( FAILED( hr ) )
    {
        ATG::FatalError( "Cannot create tiling rendertarget.\n" );
    }

    // Record the size of the created rendertarget, and then set up allocation
    // for the next rendertarget right after the end of the first rendertarget.
    // Put the hierarchical Z buffer at the start of hierarchical Z memory.
    m_dwTileTargetSizeBytes = m_pTilingRenderTarget->Size;
    SurfaceParams.Base = m_dwTileTargetSizeBytes / GPU_EDRAM_TILE_SIZE;
    SurfaceParams.HierarchicalZBase = 0;

    hr = m_pd3dDevice->CreateDepthStencilSurface( dwTileWidth,
                                                  dwTileHeight,
                                                  D3DFMT_D24S8,
                                                  CurrentScenario.MSAAType,
                                                  0, FALSE,
                                                  &m_pTilingDepthStencil,
                                                  &SurfaceParams );
    if( FAILED( hr ) )
    {
        ATG::FatalError( "Cannot create tiling depth/stencil.\n" );
    }
    m_dwTileDepthStencilSizeBytes = m_pTilingDepthStencil->Size;

    // Create the post effects render target and depth/stencil surfaces.
    // These surfaces have no MSAA, and are used for post effects rendering and UI
    // rendering, after the tiled scene rendering is complete.
    SurfaceParams.Base = 0;
    hr = m_pd3dDevice->CreateRenderTarget( dwFrontBufferWidth,
                                           dwFrontBufferHeight,
                                           ( D3DFORMAT )MAKESRGBFMT( D3DFMT_A8R8G8B8 ),
                                           D3DMULTISAMPLE_NONE,
                                           0, FALSE,
                                           &m_pPostRenderTarget,
                                           &SurfaceParams );
    if( FAILED( hr ) )
    {
        ATG::FatalError( "Cannot create post effects rendertarget.\n" );
    }

    // If the front buffer size has changed, update the presentation parameters and
    // reset the D3D device.  Also set the font window to the new safe rectangle.
    if( dwFrontBufferHeight != m_d3dpp.BackBufferHeight ||
        dwFrontBufferWidth != m_d3dpp.BackBufferWidth )
    {
        m_d3dpp.BackBufferHeight = dwFrontBufferHeight;
        m_d3dpp.BackBufferWidth = dwFrontBufferWidth;
        m_pd3dDevice->Reset( &m_d3dpp );
        m_Font.SetWindow( ATG::GetTitleSafeArea() );
    }

    // Set up the screen extents query mode that tiling will use.
    m_pd3dDevice->SetScreenExtentQueryMode( CurrentScenario.ScreenExtentQueryMode );
}


//--------------------------------------------------------------------------------------
// Name: RenderScene()
// Desc: Sets some renderstate and draws the robot mesh.
//--------------------------------------------------------------------------------------
VOID Sample::RenderScene()
{
    // Set renderstate.
    m_pd3dDevice->SetRenderState( D3DRS_ZENABLE, TRUE );

    // Set shaders.
    m_pd3dDevice->SetVertexShader( m_pVertexShader );
    m_pd3dDevice->SetPixelShader( m_pPixelShader );
    m_pd3dDevice->SetVertexDeclaration( m_pVertexDecl );

    // Set shader constants.
    m_pd3dDevice->SetVertexShaderConstantF( 0, ( FLOAT* )&m_matWVP, 4 );

    // Optionally force the robot to only render on tile 1.
    if( m_bForcedPredication )
    {
        m_pd3dDevice->SetPredication( D3DPRED_TILE( 1 ) );
    }

    // Render the robot.
    m_RobotMesh.Render( ATG::MESH_NOTEXTURES | ATG::MESH_NOVERTEXDECL | ATG::MESH_NOFVF );

    // Reset predication to default.
    if( m_bForcedPredication )
    {
        m_pd3dDevice->SetPredication( 0 );
    }
}


//--------------------------------------------------------------------------------------
// Name: RenderUI()
// Desc: Draws some statistics and other UI elements
//--------------------------------------------------------------------------------------
VOID Sample::RenderUI()
{
    if( m_bDrawHelp )
    {
        m_Help.Render( &m_Font, g_HelpCallouts, NUM_HELP_CALLOUTS );
    }
    else
    {
        // Draw a title and FPS indicator.
        WCHAR strBuffer[100];
        m_Font.Begin();
        m_Font.SetScaleFactors( 1.2f, 1.2f );
        m_Font.DrawText( 0, 0, 0xffffffff, L"PredicatedTiling" );
        m_Font.SetScaleFactors( 1.0f, 1.0f );
        m_Font.DrawText( 0, 0, 0xffffff00, m_Timer.GetFrameRate(), ATGFONT_RIGHT );

        // Draw video mode stats, EDRAM usage stats, and system memory usage stats.
        FLOAT sx1 = 16.0f;
        FLOAT sx2 = 200.0f;
        FLOAT sy = 40.0f;

        const TILING_SCENARIO& CurrentScenario = g_TilingScenarios[m_dwScenarioIndex];

        m_Font.DrawText( sx1, sy, 0xffffffff, L"Scenario Name:" );
        m_Font.DrawText( sx2, sy, 0xffffff00, CurrentScenario.strScenarioName );
        sy += 25;

        DWORD dwNumSamples = 1;
        if( CurrentScenario.MSAAType == D3DMULTISAMPLE_2_SAMPLES )
            dwNumSamples = 2;
        else if( CurrentScenario.MSAAType == D3DMULTISAMPLE_4_SAMPLES )
            dwNumSamples = 4;
        swprintf_s( strBuffer, L"%d x %d x %dx MSAA", m_d3dpp.BackBufferWidth, m_d3dpp.BackBufferHeight,
                    dwNumSamples );
        m_Font.DrawText( sx1, sy, 0xffffffff, L"BackBuffer: " );
        m_Font.DrawText( sx2, sy, 0xffffff00, strBuffer );
        sy += 25;

        swprintf_s( strBuffer, L"%d %s", CurrentScenario.dwTileCount,
                    ( CurrentScenario.dwTileCount > 1 ) ? L"" : L"(tiling disabled)" );
        m_Font.DrawText( sx1, sy, 0xffffffff, L"Predicated tiles: " );
        m_Font.DrawText( sx2, sy, 0xffffff00, strBuffer );
        sy += 25;

        swprintf_s( strBuffer, L"%d out of %d tiles",
                    ( m_dwTileTargetSizeBytes + m_dwTileDepthStencilSizeBytes ) / GPU_EDRAM_TILE_SIZE,
                    GPU_EDRAM_TILES );
        m_Font.DrawText( sx1, sy, 0xffffffff, L"EDRAM usage: " );
        m_Font.DrawText( sx2, sy, 0xffffff00, strBuffer );
        sy += 25;

        swprintf_s( strBuffer, L"(%d color + %d depth/stencil)",
                    m_dwTileTargetSizeBytes / GPU_EDRAM_TILE_SIZE,
                    m_dwTileDepthStencilSizeBytes / GPU_EDRAM_TILE_SIZE );
        m_Font.DrawText( sx2, sy, 0xffffff00, strBuffer );
        sy += 25;

        swprintf_s( strBuffer, L"%d bytes (2 buffers)",
                    m_dwFrontBufferSizeBytes * 2 );
        m_Font.DrawText( sx1, sy, 0xffffffff, L"Sysmem usage: " );
        m_Font.DrawText( sx2, sy, 0xffffff00, strBuffer );
        sy += 25;

        m_Font.End();
    }
}


HRESULT Sample::Initialize()
{
    m_matWorld = XMMatrixIdentity();
    m_vWorldLightDirection = XMVectorSet( 1, 0, 1, 1 );

    // If we are outputting an interlaced mode with less than 720 lines (360 lines per field),
    // we cannot use a 1920 x 1080 front buffer because the video scaler cannot downsample
    // that far.
    XVIDEO_MODE VideoMode;
    XGetVideoMode( &VideoMode );
    DWORD dwEffectiveHeight = VideoMode.dwDisplayHeight;
    if( VideoMode.fIsInterlaced )
        dwEffectiveHeight /= 2;
    if( ( 1080.0f / ( FLOAT )dwEffectiveHeight ) > 3.0f )
        m_bAllow1920x1080 = FALSE;
    else
        m_bAllow1920x1080 = TRUE;

    // Resize the Direct3D device ring buffer.
    // Resizing the ring buffer supports a larger or smaller amount of draw calls per scene.
    // The default is 2MB of secondary ring buffer; here we'll change that to 3MB.
    D3DRING_BUFFER_PARAMETERS RBParams = { 0 };
    RBParams.PrimarySize = 0;  // Direct3D will use the default size of 32KB
    RBParams.SecondarySize = 3 * 1024 * 1024;
    RBParams.SegmentCount = 0; // Direct3D will use the default segment count of 32

    // Setting the pPrimary and pSecondary members to NULL means that Direct3D will
    // allocate the ring buffers itself.  You can optionally provide a buffer that
    // you allocated yourself (it must be write-combined physical memory, aligned to
    // GPU_COMMAND_BUFFER_ALIGNMENT).
    RBParams.pPrimary = NULL;
    RBParams.pSecondary = NULL;

    m_pd3dDevice->SetRingBufferParameters( &RBParams );

    // Create font.
    if( FAILED( m_Font.Create( "game:\\Media\\Fonts\\Arial_16.xpr" ) ) )
        ATG::FatalError( "Could not load font." );

    // Confine text drawing to the title safe area
    m_Font.SetWindow( ATG::GetTitleSafeArea() );

    // Create mesh.
    if( FAILED( m_RobotMesh.Create( "game:\\Media\\Meshes\\Robot.xbg" ) ) )
        ATG::FatalError( "Could not load mesh." );

    // Create help screen.
    if( FAILED( m_Help.Create( "game:\\Media\\Help\\Help.xpr" ) ) )
        ATG::FatalError( "Could not load help resources." );

    // Buffers to hold compiled shaders and possible error messages
    ID3DXBuffer* pShaderCode = NULL;
    ID3DXBuffer* pErrorMsg = NULL;

    HRESULT hr = S_OK;

    // Compile vertex shader.
    hr = D3DXCompileShader( g_strVertexShaderProgram,
                            ( UINT )strlen( g_strVertexShaderProgram ),
                            NULL, NULL,
                            "main", "vs_3_0",
                            0, &pShaderCode, &pErrorMsg, NULL );
    if( FAILED( hr ) )
    {
        ATG::FatalError( pErrorMsg ? ( const CHAR* )pErrorMsg->GetBufferPointer()
                         : "Vertex shader compilation error." );
    }

    // Create vertex shader.
    m_pd3dDevice->CreateVertexShader( ( DWORD* )pShaderCode->GetBufferPointer(),
                                      &m_pVertexShader );

    // Shader code is no longer required.
    pShaderCode->Release();
    pShaderCode = NULL;

    // Compile pixel shader.
    hr = D3DXCompileShader( g_strPixelShaderProgram,
                            ( UINT )strlen( g_strPixelShaderProgram ),
                            NULL, NULL,
                            "main", "ps_3_0",
                            0, &pShaderCode, &pErrorMsg, NULL );
    if( FAILED( hr ) )
    {
        ATG::FatalError( pErrorMsg ? ( const CHAR* )pErrorMsg->GetBufferPointer()
                         : "Pixel shader compilation error." );
    }

    // Create pixel shader.
    m_pd3dDevice->CreatePixelShader( ( DWORD* )pShaderCode->GetBufferPointer(),
                                     &m_pPixelShader );

    // Shader code no longer required.
    pShaderCode->Release();
    pShaderCode = NULL;

    // Define the vertex elements.
    static const D3DVERTEXELEMENT9 VertexElements[] =
    {
        { 0,  0, D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
        { 0, 12, D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL,   0 },
        { 0, 24, D3DDECLTYPE_FLOAT2,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0 },
        D3DDECL_END()
    };

    // Create a vertex declaration from the element descriptions.
    m_pd3dDevice->CreateVertexDeclaration( VertexElements, &m_pVertexDecl );

    // Create shaders for post effects.
    hr = D3DXCompileShader( g_strVertexShaderProgram,
                            ( UINT )strlen( g_strVertexShaderProgram ),
                            NULL, NULL,
                            "vs_main_post",
                            "vs_3_0",
                            0,
                            &pShaderCode,
                            &pErrorMsg,
                            NULL );
    if( FAILED( hr ) )
    {
        ATG::FatalError( pErrorMsg ? ( const CHAR* )pErrorMsg->GetBufferPointer()
                         : "Vertex shader compilation error." );
    }

    m_pd3dDevice->CreateVertexShader( ( DWORD* )pShaderCode->GetBufferPointer(),
                                      &m_pVertexShaderPost );

    pShaderCode->Release();
    pShaderCode = NULL;

    hr = D3DXCompileShader( g_strPixelShaderProgram,
                            ( UINT )strlen( g_strPixelShaderProgram ),
                            NULL, NULL,
                            "ps_main_post",
                            "ps_3_0",
                            0,
                            &pShaderCode,
                            &pErrorMsg,
                            NULL );
    if( FAILED( hr ) )
    {
        ATG::FatalError( pErrorMsg ? ( const CHAR* )pErrorMsg->GetBufferPointer()
                         : "Pixel shader compilation error." );
    }

    m_pd3dDevice->CreatePixelShader( ( DWORD* )pShaderCode->GetBufferPointer(),
                                     &m_pPixelShaderPost );

    pShaderCode->Release();
    pShaderCode = NULL;

    static const D3DVERTEXELEMENT9 VertexElementsPost[] =
    {
        { 0,  0, D3DDECLTYPE_FLOAT2,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
        D3DDECL_END()
    };

    m_pd3dDevice->CreateVertexDeclaration( VertexElementsPost,
                                           &m_pVertexDeclPost );

    ResetDevice();

    return S_OK;
}


HRESULT Sample::Update()
{
    // Update FPS in the timer class.
    m_Timer.MarkFrame();

    // Get input from controllers (check for exit button sequence).
    ATG::GAMEPAD* pGamepad = ATG::Input::GetMergedInput();

    // The A button cycles the scenario index.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_A )
    {
        m_dwScenarioIndex++;
        // If 1920 x 1080 front buffers can't be used due to the output display mode,
        // skip them in the rotation.
        while( !m_bAllow1920x1080 && g_TilingScenarios[ m_dwScenarioIndex ].dwScreenHeight == 1080 )
            m_dwScenarioIndex++;
        if( g_TilingScenarios[ m_dwScenarioIndex ].strScenarioName == NULL )
            m_dwScenarioIndex = 0;
        ResetDevice();
    }

    // The Y button toggles forced predication.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_Y )
        m_bForcedPredication = !m_bForcedPredication;

    // The Back button toggles the help screen.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_BACK )
        m_bDrawHelp = !m_bDrawHelp;

    // The X button changes camera distance.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_X )
    {
        if( m_fEyeRadius == 8.0f )
            m_fEyeRadius = 4.0f;
        else
            m_fEyeRadius = 8.0f;
    }

    // The B button toggles rotation.
    if( pGamepad->wPressedButtons & XINPUT_GAMEPAD_B )
        m_bRotating = !m_bRotating;

    // View matrix
    FLOAT fTime = ( FLOAT )m_Timer.GetAppTime();
    if( !m_bRotating )
        fTime = -XM_PIDIV2 / 0.3f;
    XMVECTOR vEyePt = XMVectorSet( cosf( 0.3f * fTime ) * m_fEyeRadius, 0.0f,
                                   sinf( 0.3f * fTime ) * m_fEyeRadius, 0.0f );
    XMVECTOR vLookatPt = XMVectorSet( 0.0f, -0.2f, 0.0f, 0.0f );
    XMVECTOR vUp = XMVectorSet( 0.0f, 1.0f, 0.0f, 0.0f );
    m_matView = XMMatrixLookAtLH( vEyePt, vLookatPt, vUp );

    // World*view*projection
    m_matWVP = m_matWorld * m_matView * m_matProj;

    // Update robot mesh constants.
    m_RobotMesh.m_matWorld = m_matWorld;
    m_RobotMesh.m_matViewProj = m_matView * m_matProj;
    m_RobotMesh.m_vWorldLightDirection = m_vWorldLightDirection;

    return S_OK;
}


HRESULT Sample::Render()
{
    // Set our tiled render target.
    m_pd3dDevice->SetRenderTarget( 0, m_pTilingRenderTarget );
    m_pd3dDevice->SetDepthStencilSurface( m_pTilingDepthStencil );

    const TILING_SCENARIO& CurrentScenario = g_TilingScenarios[m_dwScenarioIndex];

    PIXBeginNamedEvent( 0xFFFFFFFF, "Scene Render" );

    D3DVECTOR4 ClearColor = { 0, 0, 0, 0 };
    BOOL bNeedTiling = ( CurrentScenario.dwTileCount > 1 );
    if( bNeedTiling )
    {
        // Begin tiling.  We specify the tile count, the tiling rectangles, and the
        // color and Z/stencil values to clear the tiling rendertarget with for each tile.
        m_pd3dDevice->BeginTiling(
            CurrentScenario.dwTilingFlags,
            CurrentScenario.dwTileCount,
            CurrentScenario.TilingRects,
            &ClearColor, 1.0f, 0L );
    }
    else
    {
        // We're not tiling in this scenario.  Just clear the rendertargets.
        m_pd3dDevice->Clear( 0, NULL,
                             D3DCLEAR_TARGET | D3DCLEAR_ZBUFFER,
                             0, 1.0f, 0 );

    }

    // Begin Z pass.  The Z pass is a subset of the full scene rendering.
    m_pd3dDevice->BeginZPass( 0 );

    // Render the scene.
    RenderScene();

    // End Z pass.
    m_pd3dDevice->EndZPass();

    if( bNeedTiling )
    {
        // End tiling.  This will cause the accumulated command buffer to be replayed
        // for each tile, predicated upon the boundaries of each tile.  At the end of
        // each tile's rendering, it will be resolved into a section of the front buffer
        // texture.
        m_pd3dDevice->EndTiling( D3DRESOLVE_RENDERTARGET0 |
                                 D3DRESOLVE_ALLFRAGMENTS |
                                 D3DRESOLVE_CLEARRENDERTARGET |
                                 D3DRESOLVE_CLEARDEPTHSTENCIL,
                                 NULL, m_pSceneResolveTexture,
                                 &ClearColor, 1.0f, 0L, NULL );
    }
    else
    {
        // We're not tiling in this scenario.  Just resolve rendertarget 0 to the
        // scene resolve texture.
        m_pd3dDevice->Resolve( D3DRESOLVE_RENDERTARGET0 |
                               D3DRESOLVE_CLEARRENDERTARGET,
                               NULL,
                               m_pSceneResolveTexture,
                               NULL, 0, 0,
                               &ClearColor, 1.0f, 0, NULL );
    }

    PIXEndNamedEvent();

    PIXBeginNamedEvent( 0xFFFFFFFF, "Post Effects" );

    // Set the full screen rendertarget.
    m_pd3dDevice->SetRenderTarget( 0, m_pPostRenderTarget );
    m_pd3dDevice->SetDepthStencilSurface( NULL );

    // Copy scene resolve texture back into EDRAM.
    // This is where you could apply any post effects to the scene texture, such as
    // high dynamic range tone mapping, depth of field, and more.
    // In this case, we're just copying the pixels back with no modification.
    m_pd3dDevice->SetVertexShader( m_pVertexShaderPost );
    m_pd3dDevice->SetPixelShader( m_pPixelShaderPost );
    m_pd3dDevice->SetVertexDeclaration( m_pVertexDeclPost );
    m_pd3dDevice->SetTexture( 0, &m_SceneResolveTextureAs16SRGB );

    // 3 2D corners are needed to draw a rect primitive.  The vertex shader will
    // generate proper 4D positions and 2D texture coordinates from this data.
    FLOAT fRectCorners[] = { -1, 1, 1, 1, -1, -1 };
    m_pd3dDevice->DrawPrimitiveUP( D3DPT_RECTLIST,
                                   1,
                                   ( const VOID* )fRectCorners,
                                   2 * sizeof( FLOAT ) );

    PIXEndNamedEvent();

    PIXBeginNamedEvent( 0xFFFFFFFF, "UI Render" );

    // Render UI.
    RenderUI();

    PIXEndNamedEvent();

    // Synchronize to presentation interval before the final resolve, so we do
    // not see tearing at 30Hz or 60Hz presentation intervals.
    m_pd3dDevice->SynchronizeToPresentationInterval();

    // Resolve the rendered scene back to the front buffer.
    m_pd3dDevice->Resolve( D3DRESOLVE_RENDERTARGET0 | D3DRESOLVE_CLEARRENDERTARGET,
                           NULL,
                           m_pFrontBufferTexture,
                           NULL,
                           0, 0,
                           &ClearColor,
                           1.0f, 0, NULL );

    // Swap to the current front buffer, so we can see it on screen.
    m_pd3dDevice->Swap( m_pFrontBufferTexture, NULL );

    return S_OK;
}


//--------------------------------------------------------------------------------------
// Name: main()
// Desc: Entry point to the program
//--------------------------------------------------------------------------------------
INT __cdecl main()
{
    Sample PredicatedTilingSample;

    // Set up the structure used to create the D3DDevice.
    // We don't need any back buffers for predicated tiling, since we will be creating
    // our own.  We also don't need depth/stencil created for us automatically.
    D3DPRESENT_PARAMETERS& d3dpp = PredicatedTilingSample.m_d3dpp;
    ZeroMemory( &d3dpp, sizeof( D3DPRESENT_PARAMETERS ) );
    d3dpp.BackBufferWidth = 1280;
    d3dpp.BackBufferHeight = 720;
    d3dpp.BackBufferFormat = ( D3DFORMAT )MAKESRGBFMT( D3DFMT_A8R8G8B8 );
    d3dpp.MultiSampleType = D3DMULTISAMPLE_NONE;
    d3dpp.MultiSampleQuality = 0;
    d3dpp.BackBufferCount = 0;
    d3dpp.EnableAutoDepthStencil = FALSE;
    d3dpp.DisableAutoBackBuffer = TRUE;
    d3dpp.DisableAutoFrontBuffer = TRUE;
    d3dpp.AutoDepthStencilFormat = D3DFMT_D24S8;
    d3dpp.SwapEffect = D3DSWAPEFFECT_DISCARD;
    d3dpp.PresentationInterval = D3DPRESENT_INTERVAL_IMMEDIATE;

    PredicatedTilingSample.m_dwDeviceCreationFlags = D3DCREATE_BUFFER_2_FRAMES;

    PredicatedTilingSample.Run();
}
