//--------------------------------------------------------------------------------------
// CommandBufferFile.h
//
// Structures and enums for command buffer files.  The COMMANDBUFFER_FILE_HEADER struct
// is the file header for a command buffer file, as well as the runtime structure used
// for loading and playback.
//
// Microsoft Game Technology Group.
// Copyright (C) Microsoft Corporation. All rights reserved.
//--------------------------------------------------------------------------------------
#pragma once

#include <xgraphics.h>

// FIXUP_TYPE is the type of a fixup descriptor.  Fixups come in many varieties.
enum FIXUP_TYPE
{
    FIXUP_SURFACES      = 0,
    FIXUP_CLIPRECT,
    FIXUP_VIEWPORT,
    FIXUP_VERTEXSHADERCONSTANTF,
    FIXUP_PIXELSHADERCONSTANTF,
    FIXUP_VERTEXSHADER,
    FIXUP_PIXELSHADER,
    FIXUP_TEXTURE,
    FIXUP_INDEXBUFFER,
    FIXUP_VERTEXBUFFER,
    FIXUP_CONSTANTBUFFER,
    FIXUP_COMMANDBUFFER,
    FIXUP_FORCEDWORD    = 0xffffffff,
};


// FIXUP_DESC describes a single fixup.
//
// When the fixup is being created at command buffer record time, the fixup handle is
// created from the command buffer and the offline resource specified in pResource.
// The name of the resource is set into strResourceName so the resource can be found
// at runtime.
//
// When the fixup is being applied at command buffer load time, the runtime resource is
// located using the strResourceName member.  Then, using the fixup type and the fixup
// handle, the fixup is applied to the command buffer.
#define FIXUP_NAME_SIZE 256
struct FIXUP_DESC
{
    WCHAR strResourceName[FIXUP_NAME_SIZE];
    DWORD dwResourceExtraData;
    FIXUP_TYPE Type;
    DWORD dwFixupHandle;
    VOID* pResource;
};

inline VOID EndianSwapFixupDesc( FIXUP_DESC* pFixup )
{
    XGEndianSwapMemory( pFixup->strResourceName, pFixup->strResourceName, XGENDIAN_8IN16, sizeof( WCHAR ),
                        FIXUP_NAME_SIZE );
    XGEndianSwapData( &pFixup->dwResourceExtraData, &pFixup->dwResourceExtraData, XGENDIAN_8IN32 );
    XGEndianSwapData( &pFixup->Type, &pFixup->Type, XGENDIAN_8IN32 );
    XGEndianSwapData( &pFixup->dwFixupHandle, &pFixup->dwFixupHandle, XGENDIAN_8IN32 );
    XGEndianSwapData( &pFixup->pResource, &pFixup->pResource, XGENDIAN_8IN32 );
}

// COMMANDBUFFER_FILE_HEADER is the first section of data in a command buffer file
// (.cmdbuffer extension).  It is also the runtime structure used for loading and 
// manipulating a command buffer file.  
//
// A cmdbuffer file has 6 sections:
// 1. file header (COMMANDBUFFER_FILE_HEADER struct), and "extra" data if present
// 2. command buffer header (IDirect3DCommandBuffer9 struct plus dynamic fixup data generated by D3D)
// 3. command buffer data (physical data)
// 4. command buffer initialization data (static fixup data generated by D3D)
// 5. static fixup descriptor table (array of FIXUP_DESC structures)
// 6. dynamic fixup descriptor table (array of FIXUP_DESC structures)
struct COMMANDBUFFER_FILE_HEADER
{
    DWORD dwVersion;
    DWORD dwFileHeaderSize;
    DWORD dwHeaderSize;
    union
    {
        BYTE* pHeaderData;
        D3DCommandBuffer* pCommandBuffer;
    };
    DWORD dwPhysicalSize;
    BYTE* pPhysicalData;
    DWORD dwInitializationSize;
    BYTE* pInitializationData;
    DWORD dwStaticFixupCount;
    DWORD dwStaticFixupDataSize;
    FIXUP_DESC* pStaticFixupDescs;
    DWORD dwDynamicFixupCount;
    DWORD dwDynamicFixupDataSize;
    FIXUP_DESC* pDynamicFixupDescs;
    BYTE* pExtraData;
};

#define COMMANDBUFFER_FILE_VERSION      102
